fn main() {
    // `attributes` is only mutated inside the `#[cfg(windows)]` block below; on
    // other targets the binding stays untouched, so scope the `mut` lint there.
    #[cfg_attr(not(windows), allow(unused_mut))]
    let mut attributes = tauri_build::Attributes::new();

    // Windows: take manifest embedding away from `tauri-build` so the SAME
    // Common-Controls v6 manifest is linked into bins AND test binaries from a
    // single source.
    //
    // `tauri-build` embeds its manifest via `rust-embed-resource`, which uses
    // `cargo:rustc-link-arg-bins` — bins only. So `cargo test` binaries get no
    // manifest, the loader binds the static `TaskDialogIndirect` import (pulled
    // in by `rfd` + `muda`) against comctl32 v5 instead of v6, the export is
    // missing, and the test process dies at startup with
    // STATUS_ENTRYPOINT_NOT_FOUND (0xC0000139). See tauri-apps/tauri #13419 and
    // #13948.
    //
    // The fix is to disable tauri-build's auto manifest and embed our own with
    // an UNSCOPED `/MANIFEST:EMBED` link arg. Unscoped `rustc-link-arg` applies
    // to bins, tests (incl. inline `#[cfg(test)]` unit tests), examples and
    // cdylibs alike — one manifest source for every artifact. Keeping it to a
    // single source is what avoids the `CVT1100: duplicate resource` /
    // `LNK1123` collision that broke `pnpm tauri dev` when an earlier attempt
    // embedded the manifest twice (tauri-build's copy + a manual copy).
    #[cfg(windows)]
    {
        attributes = attributes
            .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest());
        embed_windows_manifest();
    }

    attributes = attributes.app_manifest(tauri_build::AppManifest::new().commands(&[
        "telemetry_otlp_export",
        "telemetry_otlp_cancel",
        "telemetry_secret_set",
        "telemetry_secret_has",
        "telemetry_secret_clear",
        "telemetry_configure_sidecar",
    ]));

    // Regenerate the "allow-all-app-commands" permission from the single source
    // of truth (the `generate_handler!` list in src/lib.rs) BEFORE tauri-build
    // reads `permissions/`. Declaring an app ACL manifest above turns Tauri's
    // ACL on for EVERY app command reached from a webview; this keeps the grant
    // in lockstep with the registered commands so adding one never silently
    // regresses into a runtime "not allowed. Command not found".
    sync_app_command_grant();

    tauri_build::try_build(attributes).expect("failed to run tauri-build");

    #[cfg(feature = "parse-liteparse")]
    copy_pdfium_next_to_binary();
}

/// Regenerate `permissions/all-app-commands.toml` from the `generate_handler!`
/// command list in `src/lib.rs`. Write-if-changed, so an up-to-date tree
/// produces no diff and no rebuild churn; only a change to the registered
/// command set rewrites it (and that diff is committed with the command).
fn sync_app_command_grant() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=permissions/all-app-commands.toml");

    let lib_src = std::fs::read_to_string("src/lib.rs").expect("cannot read src/lib.rs");
    let commands = extract_handler_commands(&lib_src);
    assert!(
        commands.iter().any(|c| c == "account_password_verify"),
        "generate_handler! parse produced no account_password_verify — the parser \
         or the src/lib.rs layout changed; fix build.rs before shipping"
    );

    const HEADER: &str = r#"# Automatically generated by build.rs from the tauri::generate_handler! list in
# src/lib.rs. DO NOT EDIT BY HAND — it is regenerated on every build.
#
# Declaring an app ACL manifest (see build.rs -> AppManifest) turns on Tauri's
# ACL for every application command invoked from a webview. This permission
# grants the trusted local app windows access to all application-defined
# commands, restoring the pre-ACL behavior. The capability's local-only context
# still blocks remote and embedded (in-app browser) content from reaching them.

[[permission]]
identifier = "allow-all-app-commands"
description = "Enables every application-defined Tauri command for trusted local app windows (auto-generated from generate_handler!)."
commands.allow = [
"#;

    let mut content = String::with_capacity(HEADER.len() + commands.len() * 40);
    content.push_str(HEADER);
    for command in &commands {
        content.push_str("  \"");
        content.push_str(command);
        content.push_str("\",\n");
    }
    content.push_str("]\n");

    let path = std::path::Path::new("permissions/all-app-commands.toml");
    let current = std::fs::read_to_string(path).ok();
    if current.as_deref() != Some(content.as_str()) {
        std::fs::write(path, &content).expect("cannot write permissions/all-app-commands.toml");
    }
}

/// Extract the sorted, de-duplicated command names registered in the
/// `tauri::generate_handler![ ... ]` block of `src/lib.rs`. Every entry is a
/// `module::path::command_name,`; the command name is the last `::` segment.
/// The block contains only command paths and `//` line comments (no `#[cfg]`
/// attributes or block comments), which keeps this text parse reliable.
fn extract_handler_commands(lib_src: &str) -> Vec<String> {
    const MARKER: &str = "generate_handler![";
    let start = lib_src
        .find(MARKER)
        .expect("generate_handler! not found in src/lib.rs")
        + MARKER.len();
    let rest = &lib_src[start..];
    let end = rest
        .find(']')
        .expect("unterminated generate_handler! block in src/lib.rs");
    let block = &rest[..end];

    let mut commands = std::collections::BTreeSet::new();
    for raw_line in block.lines() {
        let line = match raw_line.find("//") {
            Some(i) => &raw_line[..i],
            None => raw_line,
        };
        for token in line.split(',') {
            let name = token.rsplit("::").next().unwrap_or("").trim();
            let mut chars = name.chars();
            let valid_head = matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_');
            let valid_tail = chars.all(|c| c.is_ascii_alphanumeric() || c == '_');
            if valid_head && valid_tail {
                commands.insert(name.to_string());
            }
        }
    }
    commands.into_iter().collect()
}

/// `parse-liteparse` only — stage the PDFium shared library next to the
/// build outputs, mirroring `ort`'s `copy-dylibs` behavior for the
/// `ocr-paddle` feature. `liteparse-pdfium-sys`'s build script copies the
/// library into `target/<profile>/deps/`; we lift it one level up to
/// `target/<profile>/` so `cargo run` / `tauri dev` / packaged bundles find
/// it next to the executable (runtime search order: PDFIUM_LIB_PATH env →
/// compile-time cache path (build machine only) → exe-adjacent → PATH).
/// Best-effort: on a cold build the deps copy may land after this script
/// runs — the next build picks it up, and dev/test still work through the
/// compile-time cache path.
#[cfg(feature = "parse-liteparse")]
fn copy_pdfium_next_to_binary() {
    let dylib = if cfg!(target_os = "windows") {
        "pdfium.dll"
    } else if cfg!(target_os = "macos") {
        "libpdfium.dylib"
    } else {
        "libpdfium.so"
    };

    // OUT_DIR = target/<profile>/build/<pkg>-<hash>/out → profile dir is 3 up.
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let Some(profile_dir) = out_dir.ancestors().nth(3).map(std::path::Path::to_path_buf) else {
        println!("cargo:warning=parse-liteparse: cannot locate profile dir from OUT_DIR");
        return;
    };

    let src = profile_dir.join("deps").join(dylib);
    let dst = profile_dir.join(dylib);
    if dst.exists() {
        return;
    }
    if !src.exists() {
        println!(
            "cargo:warning=parse-liteparse: {} not found yet at {} — it is copied by \
             liteparse-pdfium-sys on first build; rebuild once or ship it next to the \
             executable when packaging",
            dylib,
            src.display()
        );
        return;
    }
    if let Err(e) = std::fs::copy(&src, &dst) {
        println!(
            "cargo:warning=parse-liteparse: failed to copy {} to {}: {e}",
            src.display(),
            dst.display()
        );
    }
}

#[cfg(windows)]
fn embed_windows_manifest() {
    let manifest = std::env::current_dir()
        .expect("cannot resolve build script cwd")
        .join("windows-app-manifest.xml");
    println!("cargo:rerun-if-changed={}", manifest.display());
    // Embed the application manifest into every linked artifact, tests included.
    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
}
