import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"
import prettier from "eslint-config-prettier"
import storybook from "eslint-plugin-storybook"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Story-specific lint rules (only target *.stories.* and .storybook/*).
  ...storybook.configs["flat/recommended"],
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    // Storybook static build output (`pnpm build-storybook`) — minified vendor
    // JS bundles, gitignored and never authored here. eslint's flat config does
    // not read .gitignore, so it must be listed explicitly like out/ & docs/out/.
    "storybook-static/**",
    "cli/dist/**",
    // WXT build products: `.wxt/` is the generated type surface, `build/` and
    // `.output/` the packed extension. Authored nothing, and `.wxt/` carries
    // ambient declarations that the app's config has no reason to parse.
    // (The bare `build/**` above matches only the repo root.)
    "browser-extension/.wxt/**",
    "browser-extension/build/**",
    "browser-extension/.output/**",
    // Bare `coverage/**` only matches the repo-root coverage dir; `**/coverage/**`
    // also covers per-package coverage output (e.g. packages/*/coverage/) — all
    // generated by the test runner, never authored here.
    "**/coverage/**",
    "target/**",
    "packages/**/dist/**",
    "crates/**/dist/**",
    "crates/**/extension/out/**",
    // Cognia plugins may vendor upstream skill assets and SDK declaration
    // snapshots. They are validated by the plugin CLI/package checks rather
    // than the host app's lint rules; dist/ and target/ are generated output.
    "plugins/**/skills/**",
    "plugins/**/types/**",
    "plugins/**/dist/**",
    "plugins/**/target/**",
    "next-env.d.ts",
    "docs/.next/**",
    "docs/.source/**",
    // Docs is a static export (Fumadocs → Cloudflare Pages); docs/out/ holds
    // the minified bundle, same rationale as the root out/ artifact dir.
    "docs/out/**",
    "docs/next-env.d.ts",
    // The marketing site (ADR-0092) is a static export like docs/: web/out/
    // holds the minified bundle and web/.next/ the build cache. Same rationale
    // as the root out/ artifact dir — flat config does not read .gitignore.
    "web/.next/**",
    "web/out/**",
    "web/next-env.d.ts",
    ".agents/**",
    ".claude/**",
    "sidecar/**",
    // Standalone Cloudflare worker + Vite viewer workspace with its own
    // toolchain, tsconfig, and lockfile (like sidecar/). Its src is linted
    // by its own config; its dist/ is a minified build artifact.
    "services/share-server/**",
    // Standalone Cloudflare worker (workers-rs / Rust) with its own toolchain.
    // Its build/ and .wrangler/ dirs are minified JS bundles emitted by wrangler,
    // never authored here (same rationale as services/share-server/**).
    "services/signaling-server/worker/build/**",
    "services/signaling-server/worker/.wrangler/**",
    "node_modules/**",
    // Generated catalogs emitted by scripts/build/*.mjs (e.g.
    // build-builtin-skills.mjs). They carry a `/* eslint-disable */` header so
    // generated content can't trip a rule; linting them only produces
    // "unused directive" noise and lets `eslint --fix` strip that header,
    // desyncing the file from its generator. Treat like other build artifacts.
    "**/*.generated.ts",
    // VS Code extension fixture under sidecar/vscode-ext-host — simulates
    // a real CJS extension on purpose (require("vscode")), and the .js file
    // is a pre-built artifact checked in to skip a build step in tests.
    "sidecar/vscode-ext-host/tests/fixtures/**",
    // Bundled Monaco assets copied from node_modules by
    // scripts/copy-monaco-assets.mjs — minified vendor JS, never authored here.
    "public/monaco/**",
    // Offline React artifact runtime emitted by
    // scripts/build/build-artifact-runtime.mjs — minified bundles of react,
    // react-dom and @babel/standalone. The authored source is
    // lib/artifacts/runtime/artifact-shell-entry.ts.
    "public/artifact-runtime/**",
    // Downloaded Cubism runtime binary from scripts/build/download-cubism-core.mjs.
    "public/live2d/**",
    // tesseract.js worker/core assets copied from node_modules by
    // scripts/build/copy-ocr-assets.mjs — minified vendor JS, never authored here.
    "public/ocr/**",
    // Serwist emits these minified service-worker bundles during `next build`.
    "public/sw.js",
    "public/swe-worker-*.js",
    // Capacitor mobile platform build artifacts — generated by gradle /
    // Xcode and contain bundled Next.js JS that we do not author here.
    "mobile/android/**/build/**",
    "mobile/android/.gradle/**",
    // `cap sync` copies the entire static export into the platform's
    // assets directory; treat it the same as out/.
    "mobile/android/app/src/main/assets/**",
    "mobile/ios/**/build/**",
    "mobile/ios/App/App/public/**",
    "mobile/ios/App/Pods/**",
    "mobile/ios/DerivedData/**",
    // esbuild bundle of lib/plugin/convert/**, emitted by
    // scripts/plugin/build-convert-bundle.mjs and embedded in the CLI with
    // include_str! so `cognia plugin import` needs no Node toolchain. Its
    // generator owns the format; `eslint --fix` would desync it from the
    // `plugin-convert:check` freshness gate.
    "crates/cognia-cli/assets/plugin-convert.cjs",
  ]),
  // Allow underscore-prefixed unused variables (standard convention for intentional-unused).
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  // Vendored components (ai-elements, shadcn/ui) — relaxed rules per CLAUDE.md
  {
    files: [
      "components/ai-elements/**/*.{ts,tsx}",
      "components/ui/**/*.{ts,tsx}",
      // The marketing workspace keeps its own shadcn copies (ADR-0092 §1
      // forbids importing the product's), so they need the same relaxation.
      "web/components/ui/**/*.{ts,tsx}",
    ],
    rules: {
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/immutability": "off",
      "react-hooks/static-components": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/purity": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // Jest CommonJS mock shims — runtime is Node CJS, require() is the correct call.
  {
    files: ["__mocks__/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Test files render raw <img> as fixtures/assertions; next/image optimization
  // is irrelevant in jsdom and would only complicate the test. Allow <img> here.
  {
    files: ["**/*.test.{ts,tsx}"],
    rules: {
      "@next/next/no-img-element": "off",
    },
  },
  // Test files where `require()` is the right idiom — either to re-read the
  // module after a Jest mock has been registered, or to dodge a TDZ on a
  // helper export that runs at import time. Narrow per-file overrides keep
  // the rule on everywhere else.
  {
    files: [
      "stores/canvas/index.test.ts",
      "stores/chat/chat-store.test.ts",
      "lib/claude/ipc.test.ts",
      "components/chat/message-renderer.test.tsx",
      // Project-editor component tests flatten Radix primitives via
      // `require("react")` inside jest.mock factories (hoisting-safe idiom).
      "components/agent/workspace/editor/project-root-switcher.test.tsx",
      "components/agent/workspace/editor/project-monaco.test.tsx",
      "components/agent/workspace/editor/project-file-tree.test.tsx",
    ],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
])

export default eslintConfig
