import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"
import prettier from "eslint-config-prettier"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "cli/dist/**",
    "coverage/**",
    "target/**",
    "packages/**/dist/**",
    "crates/**/extension/out/**",
    "next-env.d.ts",
    "docs/.next/**",
    "docs/.source/**",
    "docs/next-env.d.ts",
    ".agents/**",
    ".claude/**",
    "sidecar/**",
    // Standalone Cloudflare worker + Vite viewer workspace with its own
    // toolchain, tsconfig, and lockfile (like sidecar/). Its src is linted
    // by its own config; its dist/ is a minified build artifact.
    "share-server/**",
    // Standalone Cloudflare worker (workers-rs / Rust) with its own toolchain.
    // Its build/ and .wrangler/ dirs are minified JS bundles emitted by wrangler,
    // never authored here (same rationale as share-server/**).
    "signaling-server/worker/build/**",
    "signaling-server/worker/.wrangler/**",
    "node_modules/**",
    // Generated catalogs emitted by scripts/build/*.mjs (e.g.
    // build-builtin-skills.mjs). They carry a `/* eslint-disable */` header so
    // generated content can't trip a rule; linting them only produces
    // "unused directive" noise and lets `eslint --fix` strip that header,
    // desyncing the file from its generator. Treat like other build artifacts.
    "**/*.generated.ts",
    // VS Code extension fixture under sidecar/vscode-ext-host — simulates
    // a real CJS extension on purpose (require("vscode")), and the .js file
    // is a pre-built artifact checked in to skip a build step in tests.
    "sidecar/vscode-ext-host/tests/fixtures/**",
    // Bundled Monaco assets copied from node_modules by
    // scripts/copy-monaco-assets.mjs — minified vendor JS, never authored here.
    "public/monaco/**",
    // Downloaded Cubism runtime binary from scripts/build/download-cubism-core.mjs.
    "public/live2d/**",
    // Capacitor mobile platform build artifacts — generated by gradle /
    // Xcode and contain bundled Next.js JS that we do not author here.
    "mobile/android/**/build/**",
    "mobile/android/.gradle/**",
    // `cap sync` copies the entire static export into the platform's
    // assets directory; treat it the same as out/.
    "mobile/android/app/src/main/assets/**",
    "mobile/ios/**/build/**",
    "mobile/ios/App/App/public/**",
    "mobile/ios/App/Pods/**",
    "mobile/ios/DerivedData/**",
  ]),
  // Allow underscore-prefixed unused variables (standard convention for intentional-unused).
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  // Vendored components (ai-elements, shadcn/ui) — relaxed rules per CLAUDE.md
  {
    files: ["components/ai-elements/**/*.{ts,tsx}", "components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/immutability": "off",
      "react-hooks/static-components": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/purity": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // Jest CommonJS mock shims — runtime is Node CJS, require() is the correct call.
  {
    files: ["__mocks__/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Test files where `require()` is the right idiom — either to re-read the
  // module after a Jest mock has been registered, or to dodge a TDZ on a
  // helper export that runs at import time. Narrow per-file overrides keep
  // the rule on everywhere else.
  {
    files: [
      "stores/canvas/index.test.ts",
      "stores/chat/chat-store.test.ts",
      "lib/claude/ipc.test.ts",
      "components/chat/message-renderer.test.tsx",
    ],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
])

export default eslintConfig
