/**
 * Emit the generated plugin project as a file map.
 *
 * Two deliberate departures from the `--kind ts` template:
 *
 * 0. **The entry has no runtime dependency.** Every import in it is
 *    type-only or the manifest JSON, so esbuild produces `dist/index.js`
 *    from a freshly generated directory with nothing installed. That is
 *    what makes `cognia plugin import`'s trailing build a one-command
 *    promise rather than one that needs `pnpm install` first. The SDK is a
 *    devDependency for types and typechecking only.
 *
 * 1. **The entry imports `plugin.json` instead of restating it.**
 *    `PluginDefinition.manifest` is required by the type, and some
 *    first-party plugins satisfy it by pasting a second copy of the
 *    manifest into `src/index.ts` (one of them needs an `as never` to do
 *    so). A converted plugin has no logic to justify that duplication, so
 *    the entry imports the real file — `resolveJsonModule` is on and
 *    esbuild inlines it at bundle time. `plugin.json` stays the only place
 *    a contribution is declared, which matters because the author will be
 *    editing it by hand.
 *
 * 2. **`dist/` is NOT gitignored.** The in-app GitHub installer
 *    (`lib/plugin/package/github-source.ts`) does a build-free install: it
 *    reads the repo as published. A converted plugin whose `dist/` is
 *    ignored would clone into an uninstallable directory. The wasm-only
 *    git installer does build, but frontend plugins have no such path.
 */

import type { PluginManifest } from "@/types/plugin/plugin"
import { serializeManifest } from "./manifest"
import type { ConvertFileMap, ConvertSourceKind } from "./types"

/**
 * Ambient package versions mirrored from `crates/cognia-plugin-template-ts`.
 * The SDK sits here, not in `dependencies`: the generated entry imports only
 * its types, so nothing from it survives into `dist/index.js`.
 */
const DEV_DEPENDENCIES: Record<string, string> = {
  "@cognia/plugin-sdk": "^0.1.0",
  "@types/node": "^22.0.0",
  esbuild: "^0.24.0",
  typescript: "^5.6.0",
}

const ESBUILD_ARGS =
  "src/index.ts --bundle --format=cjs --platform=neutral --target=es2022 --outfile=dist/index.js --log-level=info"

/** `src/index.ts` — an empty shell; every contribution rides the manifest. */
export function renderEntry(manifest: PluginManifest, kind: ConvertSourceKind): string {
  const dispatch: Record<ConvertSourceKind, string> = {
    mcp: "`mcpServerPresets` in plugin.json is registered by the host's overlay dispatch",
    skill: "`skills` in plugin.json is registered by the host's overlay dispatch",
    cli: "`cliTools` in plugin.json is materialised by the plugin manager",
  }
  return `/**
 * ${manifest.name} — generated by \`cognia plugin import\`.
 *
 * This entry is intentionally almost empty: ${dispatch[kind]},
 * so no imperative registration is needed here. The manifest is imported
 * rather than restated so plugin.json stays the single source of truth.
 *
 * Add your own logic inside \`activate\` when you need behaviour the
 * manifest cannot express.
 */

import type { PluginContext, PluginDefinition, PluginManifest } from "@cognia/plugin-sdk"
import manifest from "../plugin.json"

const definition: PluginDefinition = {
  manifest: manifest as unknown as PluginManifest,

  activate: async (ctx: PluginContext) => {
    ctx.logger.info("${manifest.id} activated")
  },

  deactivate: async (ctx?: PluginContext) => {
    ctx?.logger.info("${manifest.id} deactivated")
  },
}

export default definition
`
}

/**
 * `dist/index.js` — the build output, emitted directly.
 *
 * `manifest.main` points here, so without it the generated project is not
 * installable, and `cognia plugin import`'s promise of a ready artifact
 * would depend on `npx --no-install esbuild` resolving in a directory that
 * has just been created and has no `node_modules`. It never does.
 *
 * Emitting it is safe precisely because the entry is ours and has no
 * runtime dependency: the only thing esbuild does to `src/index.ts` is
 * erase the type-only import and inline `plugin.json`. `scaffold.test.ts`
 * pins the equivalence by running the real esbuild over the generated
 * entry and comparing the loaded module against this one.
 *
 * The trailing esbuild step still runs when the toolchain is available, so
 * this file is a floor, not a replacement for the build.
 */
export function renderDist(manifest: PluginManifest): string {
  return `"use strict";
// Built output of src/index.ts, pre-generated by \`cognia plugin import\`.
// Re-run \`pnpm build\` after editing src/index.ts, and commit the result:
// the in-app GitHub installer performs a build-free install.
const manifest = ${JSON.stringify(manifest, null, 2)};

const definition = {
  manifest,
  activate: async (ctx) => {
    ctx.logger.info("${manifest.id} activated");
  },
  deactivate: async (ctx) => {
    ctx?.logger.info("${manifest.id} deactivated");
  },
};

module.exports = { __esModule: true, default: definition };
`
}

/** `package.json` for the generated project. */
export function renderPackageJson(manifest: PluginManifest): string {
  const pkg = {
    name: manifest.id,
    version: manifest.version,
    private: true,
    description: manifest.description,
    scripts: {
      build: `esbuild ${ESBUILD_ARGS}`,
      typecheck: "tsc --noEmit",
    },
    devDependencies: DEV_DEPENDENCIES,
  }
  return `${JSON.stringify(pkg, null, 2)}\n`
}

/** `tsconfig.json` — mirrors the ts template plus JSON module resolution. */
export function renderTsconfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      isolatedModules: true,
      strict: true,
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: false,
      outDir: "dist",
      lib: ["ES2022", "DOM"],
      types: ["node"],
    },
    include: ["src/**/*.ts", "plugin.json"],
    exclude: ["node_modules", "dist"],
  }
  return `${JSON.stringify(tsconfig, null, 2)}\n`
}

/**
 * `.gitignore`. `dist/` is absent on purpose — see the module header.
 * `.cognia/` is present because that is where `cognia plugin keygen`
 * writes a private signing key; the template that once omitted it staged
 * the key on the author's first `git add -A`.
 */
export function renderGitignore(): string {
  return ["node_modules/", "coverage/", ".cognia/", "*.log", ""].join("\n")
}

/** Per-source next-steps and field documentation. */
export function renderReadme(
  manifest: PluginManifest,
  kind: ConvertSourceKind,
  todos: string[]
): string {
  const todoSection =
    todos.length > 0
      ? `\n## Before this plugin works\n\n${todos.map((t) => `- ${t}`).join("\n")}\n`
      : ""

  return `# ${manifest.name}

${manifest.description}

Generated by \`cognia plugin import --from ${kind}\`. Nothing was executed to
produce it: the source artifact was read as text, and no value from it was
copied into \`plugin.json\`.
${todoSection}
## Layout

\`\`\`
${manifest.id}/
├── plugin.json       — the manifest; the ONLY place contributions are declared
├── src/index.ts      — empty shell; imports plugin.json, registers nothing
├── dist/index.js     — build output; committed so GitHub installs work
├── package.json
├── tsconfig.json
└── README.md
\`\`\`

## Workflow

\`\`\`bash
pnpm install           # once, to get esbuild + the SDK types
pnpm build             # esbuild → dist/index.js
cognia plugin lint     # validate plugin.json against the host schema
cognia plugin install .   # into a running cognia desktop
\`\`\`

\`dist/index.js\` is committed on purpose. The in-app GitHub installer
performs a build-free install, so a repository without it clones into an
uninstallable plugin. Re-run \`pnpm build\` and commit the result whenever
you change \`src/index.ts\`.

${SOURCE_NOTES[kind]}
`
}

const SOURCE_NOTES: Record<ConvertSourceKind, string> = {
  mcp: `## Editing the preset

\`mcpServerPresets[0]\` is what users see in Settings → MCP Servers → Add
server. \`fields[]\` declares what they must fill in; \`config\` holds only
non-user-specific defaults. Every credential from the source config was
turned into a field with no value — fill nothing in here, that is the point.

- \`placement: "env"\` — written into \`config.env[key]\`
- \`placement: "arg-replace"\` — replaces \`token\` inside \`config.args\`
- \`placement: "header"\` — written into \`config.headers[key]\`
- \`placement: "url"\` — replaces \`config.url\`
- \`secret: true\` — rendered as a password input

Set \`icon\`, \`docsUrl\`, and \`tags\` to make the gallery card readable.`,

  skill: `## Editing the skill

\`skills[0]\` is registered into the skill picker when the plugin is
enabled. An \`inline\` source carries the SKILL.md body in the manifest and
works in every shell (desktop, browser, mobile). A \`local-bundle\` source
points at a folder inside this plugin and is desktop-only, because the
resources are read through the desktop filesystem bridge.

Set \`scope\` to \`"character"\`, \`"team"\`, or \`"global"\` to control which
picker it appears in.`,

  cli: `## Filling in the tool table

\`cliTools\` is empty: a binary's \`--help\` does not state which flags take
values, which repeat, what the exit codes mean, or which output format the
agent should receive, and this converter does not run anything to find out.
Guessing would produce a tool that lints green and misbehaves.

Each entry needs a JSON Schema for its parameters plus an \`argv\` token
list. Parameters substitute as exactly one argv element each, which is what
makes the wrapper injection-safe — never concatenate values into a string.

\`\`\`jsonc
{
  "name": "ripgrep_search",
  "description": "Search file contents. Exit code 1 (no matches) is success.",
  "parameters": {
    "type": "object",
    "properties": {
      "pattern": { "type": "string", "description": "Regular expression" },
      "globs": { "type": "array", "items": { "type": "string" } },
      "ignoreCase": { "type": "boolean" }
    },
    "required": ["pattern"]
  },
  "binary": { "kind": "requires", "name": "rg" },
  "argv": [
    { "literal": "--json" },
    { "param": "ignoreCase", "eachPrefixedBy": "-i", "omitWhenEmpty": true },
    { "param": "globs", "eachPrefixedBy": "--glob", "omitWhenEmpty": true },
    { "param": "pattern", "eachPrefixedBy": "-e" },
    { "literal": "--" },
    { "param": "path", "omitWhenEmpty": true }
  ],
  "cwd": { "kind": "workspace" },
  "outputParse": "lines",
  "successExitCodes": [0, 1],
  "timeoutMs": 60000,
  "maxOutputBytes": 500000
}
\`\`\`

\`plugins/ripgrep-tools/plugin.json\` in the cognia repository is the
reference implementation. Until \`cliTools\` has at least one entry,
\`cognia plugin lint\` reports \`manifest.capability.field_missing\`.`,
}

/** Build the complete file map for a greenfield conversion. */
export function renderProject(
  manifest: PluginManifest,
  kind: ConvertSourceKind,
  todos: string[]
): ConvertFileMap {
  return new Map<string, string>([
    ["plugin.json", serializeManifest(manifest)],
    ["src/index.ts", renderEntry(manifest, kind)],
    ["dist/index.js", renderDist(manifest)],
    ["package.json", renderPackageJson(manifest)],
    ["tsconfig.json", renderTsconfig()],
    [".gitignore", renderGitignore()],
    ["README.md", renderReadme(manifest, kind, todos)],
  ])
}
