/**
 * Impeccable — generated by `cognia plugin import`.
 *
 * This entry is intentionally almost empty: `skills` in plugin.json is registered by the host's overlay dispatch,
 * so no imperative registration is needed here. The manifest is imported
 * rather than restated so plugin.json stays the single source of truth.
 *
 * Add your own logic inside `activate` when you need behaviour the
 * manifest cannot express.
 */

import type { PluginContext, PluginDefinition, PluginManifest } from "@cognia/plugin-sdk"
import manifest from "../plugin.json"

const definition: PluginDefinition = {
  manifest: manifest as unknown as PluginManifest,

  activate: async (ctx: PluginContext) => {
    ctx.logger.info("cognia-impeccable activated")
  },

  deactivate: async (ctx?: PluginContext) => {
    ctx?.logger.info("cognia-impeccable deactivated")
  },
}

export default definition
