import { defineConfig } from "tsup"

const runtimeEntries = {
  index: "src/index.ts",
  manifest: "src/manifest/index.ts",
  context: "src/context/index.ts",
  contracts: "src/contracts/catalog.ts",
  events: "src/events/index.ts",
  hooks: "src/hooks/index.ts",
  permissions: "src/permissions/index.ts",
  extensions: "src/extensions/index.ts",
  templates: "src/templates/index.ts",
  connector: "src/api/connector.ts",
  i18n: "src/api/i18n.ts",
  integration: "src/api/integration.ts",
  "context-panel": "src/api/context-panel.ts",
  editor: "src/api/editor.ts",
  webview: "src/api/webview.ts",
  "agent-team-template": "src/api/agent-team-template.ts",
  automation: "src/api/automation.ts",
  "balance-adapter": "src/api/balance-adapter.ts",
  browser: "src/api/browser.ts",
  "character-pack": "src/api/character-pack.ts",
  "cli-tool": "src/api/cli-tool.ts",
  "context-provider": "src/api/context-provider.ts",
  "external-agent-adapter": "src/api/external-agent-adapter.ts",
  "external-agent-preset": "src/api/external-agent-preset.ts",
  "host-environment": "src/api/host-environment.ts",
  "message-renderer": "src/api/message-renderer.ts",
  "ocr-provider": "src/api/ocr-provider.ts",
  sandbox: "src/api/sandbox.ts",
  "scheduled-task": "src/api/scheduled-task.ts",
  "security-findings": "src/api/security-findings.ts",
  "shared-memory-adapter": "src/api/shared-memory-adapter.ts",
  skill: "src/api/skill.ts",
  "skill-recorder": "src/api/skill-recorder.ts",
  "slash-command": "src/api/slash-command.ts",
  subagent: "src/api/subagent.ts",
  "tool-renderer": "src/api/tool-renderer.ts",
  "workflow-template": "src/api/workflow-template.ts",
}

const shared = {
  target: "es2022" as const,
  platform: "neutral" as const,
}

export default defineConfig({
  ...shared,
  entry: runtimeEntries,
  format: ["esm", "cjs"],
  dts: false,
  sourcemap: true,
  clean: true,
})
