/**
 * Lark OAuth handler — completes Phase 2 of ADR-0009 v41 / A4 (D2).
 *
 * The deep-link router (cognia://connector/oauth/lark?code=...&state=...)
 * invokes `handleLarkOAuth(code)` after validating the state. This module
 * is the platform-specific completion side:
 *
 *   1. Parse the adapterId out of the state nonce (state encodes both
 *      adapter scope + entropy via `buildLarkOAuthState`).
 *   2. Look up the AdapterInstanceRow + decrypt the app secret from the
 *      OS keyring via the existing connectors-keyring Tauri commands.
 *   3. Acquire the tenant access token (`getTenantAccessToken`).
 *   4. Swap the OAuth code for a user access token + refresh token via
 *      `exchangeCodeForUserAccessToken`.
 *   5. Persist tokens in the keyring under
 *      `<adapterId>:user_token` + `<adapterId>:user_refresh_token` so
 *      the adapter's send loop can opt-into the user-scope path for
 *      future API calls.
 *   6. Stamp the connected-user metadata onto AdapterInstanceRow.settings
 *      so the Adapters tab can render "Connected as <Name>".
 *
 * Designed to be re-entrant: a second invocation with the same code is a
 * no-op (Lark rejects re-use) — the keyring write is idempotent because
 * Dexie's `put` upserts.
 */

import { getAdapterInstance, updateAdapterInstance } from "@/lib/db/adapter-instances"
import { connectorsKeyringGet, connectorsKeyringSet } from "@/lib/connectors/tauri/commands"
import {
  exchangeCodeForUserAccessToken,
  getTenantAccessToken,
  type LarkUserAccessTokenResult,
} from "./auth"

// ---------------------------------------------------------------------------
// State encoding: `lark:<adapterId>:<nonce>`
// ---------------------------------------------------------------------------

/**
 * Build the `state` query parameter for the OAuth redirect. We bake the
 * `adapterId` into state so the deep-link router can resolve the right
 * adapter row when multiple Lark accounts are configured. The nonce is
 * generated by the caller (typically a `crypto.randomUUID()` slice) and
 * persisted in `sessionStorage` for the CSRF check.
 */
export function buildLarkOAuthState(adapterId: string, nonce: string): string {
  // Colon-delimited triple. The deep-link router currently does a flat
  // state comparison against sessionStorage; we preserve that by storing
  // the same composite string both places.
  return `lark:${adapterId}:${nonce}`
}

/**
 * Parse the composite state. Returns `null` on shape mismatch so the
 * caller can surface a "state malformed" error.
 */
export function parseLarkOAuthState(state: string): { adapterId: string; nonce: string } | null {
  const parts = state.split(":")
  if (parts.length < 3) return null
  if (parts[0] !== "lark") return null
  const [, adapterId, ...rest] = parts
  return { adapterId, nonce: rest.join(":") }
}

// ---------------------------------------------------------------------------
// Connected user metadata stamped on AdapterInstanceRow.settings
// ---------------------------------------------------------------------------

export interface LarkConnectedUser {
  openId: string
  unionId?: string
  name?: string
  avatarUrl?: string
  email?: string
  enterpriseEmail?: string
  /** Wall-clock ms at which the access token expires. */
  expiresAtMs: number
  /** Wall-clock ms at which the refresh token expires. */
  refreshExpiresAtMs: number
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export interface HandleLarkOAuthDeps {
  /** Parsed state passed by the deep-link router. */
  state: string
}

/**
 * Complete the Lark OAuth exchange end-to-end. Throws when:
 *   - state malformed,
 *   - the adapter row isn't found,
 *   - app secret isn't in the keyring,
 *   - Lark's tenant-token or OIDC endpoints return a non-zero code.
 *
 * On success the user tokens land in keyring + `AdapterInstanceRow.settings`
 * gets a `connectedUser` field.
 */
export async function handleLarkOAuth(
  code: string,
  deps: HandleLarkOAuthDeps
): Promise<LarkConnectedUser> {
  const parsedState = parseLarkOAuthState(deps.state)
  if (!parsedState) {
    throw new Error("Lark OAuth state malformed — expected `lark:<adapterId>:<nonce>`")
  }
  const { adapterId } = parsedState

  // ── Step 1: resolve adapter row ────────────────────────────────────────
  const adapter = await getAdapterInstance(adapterId)
  if (!adapter) {
    throw new Error(`Lark OAuth: adapter ${adapterId} not found`)
  }
  if (adapter.type !== "lark") {
    throw new Error(`Lark OAuth: adapter ${adapterId} is not a Lark adapter (type=${adapter.type})`)
  }

  const appId = String(adapter.settings.appId ?? "").trim()
  if (!appId) {
    throw new Error(`Lark OAuth: adapter ${adapterId} has no appId configured`)
  }

  // ── Step 2: pull app secret from keyring ───────────────────────────────
  const appSecret = await connectorsKeyringGet(adapterId, "appSecret")
  if (!appSecret) {
    throw new Error(
      `Lark OAuth: app secret not found in keyring (adapterId=${adapterId} credential=appSecret)`
    )
  }

  // ── Step 3: TAT, then exchange ─────────────────────────────────────────
  const tat = await getTenantAccessToken({ appId, appSecret })
  const tokens: LarkUserAccessTokenResult = await exchangeCodeForUserAccessToken({
    code,
    appAccessToken: tat,
  })

  // ── Step 4: persist tokens in keyring ──────────────────────────────────
  await connectorsKeyringSet(adapterId, "user_token", tokens.accessToken)
  await connectorsKeyringSet(adapterId, "user_refresh_token", tokens.refreshToken)

  // ── Step 5: stamp connected-user metadata ─────────────────────────────
  const now = Date.now()
  const connectedUser: LarkConnectedUser = {
    openId: tokens.openId,
    unionId: tokens.unionId,
    name: tokens.name,
    avatarUrl: tokens.avatarUrl,
    email: tokens.email,
    enterpriseEmail: tokens.enterpriseEmail,
    expiresAtMs: now + tokens.expiresInSec * 1000,
    refreshExpiresAtMs: now + tokens.refreshExpiresInSec * 1000,
  }
  await updateAdapterInstance(adapterId, {
    settings: { ...adapter.settings, connectedUser },
    credentialsRef: {
      ...adapter.credentialsRef,
      accounts: Array.from(
        new Set([
          ...adapter.credentialsRef.accounts,
          // Mirror the keyring credential names so anyone auditing the
          // adapter row can see which entries point into the OS keyring
          // without grepping the platform-specific OAuth handler.
          "user_token",
          "user_refresh_token",
        ])
      ),
    },
  })

  return connectedUser
}
