/**
 * Lark OAuth handler — completes the send-as-user OAuth 2.0 flow.
 *
 * The deep-link router (cognia://connector/oauth/lark?code=...&state=...)
 * invokes `handleLarkOAuth(code, {state})` after a first state check. This
 * module is the platform-specific completion side:
 *
 *   1. Parse the adapterId out of the state (state encodes both adapter scope
 *      + entropy via `buildLarkOAuthState`).
 *   2. Load the durable pending authorization (PKCE `code_verifier` + the exact
 *      `redirect_uri` used at authorize) and re-validate `state` against it —
 *      the CSRF check that survives an app restart. The record was written by
 *      `oauth-begin.ts` in THIS process, on either host.
 *   3. Look up the AdapterInstanceRow + decrypt the app secret from the OS
 *      keyring.
 *   4. Swap the OAuth code for a user access token + refresh token via the v2
 *      token endpoint (`exchangeCodeForUserAccessToken`; client_secret in body,
 *      no tenant token needed).
 *   5. Resolve the connected user's identity (`fetchLarkUserInfo`).
 *   6. Persist tokens in the keyring under `<adapterId>:user_token` +
 *      `<adapterId>:user_refresh_token` so the adapter's send loop can opt-into
 *      the user-scope path for future API calls.
 *   7. Stamp the connected-user metadata onto AdapterInstanceRow.settings so
 *      the Adapters tab can render "Connected as <Name>", and clear the pending.
 *
 * Designed to be re-entrant: a second invocation with the same code is a
 * no-op (Lark rejects re-use) — the keyring write is idempotent because
 * Dexie's `put` upserts.
 */

import { getAdapterInstance, updateAdapterInstance } from "@/lib/db/adapter-instances"
import { connectorsKeyringGet, connectorsKeyringSet } from "@/lib/connectors/tauri/commands"
import { recordGrantedScopes, type ConnectedScopes } from "@/lib/connectors/oauth-scope-audit"
import { clearUserTokenCache, exchangeCodeForUserAccessToken, fetchLarkUserInfo } from "./auth"
import { clearLarkOAuthPending, getLarkOAuthPending } from "./oauth-pending"

// ---------------------------------------------------------------------------
// State encoding: `lark:<adapterId>:<nonce>`
// ---------------------------------------------------------------------------

/**
 * Build the `state` query parameter for the OAuth redirect. We bake the
 * `adapterId` into state so the deep-link router can resolve the right
 * adapter row when multiple Lark accounts are configured. The nonce is
 * generated by `beginLarkOAuth`, which persists the composite string in the
 * pending record; the desktop deep-link router additionally mirrors it into
 * `sessionStorage` for its own pre-check.
 */
export function buildLarkOAuthState(adapterId: string, nonce: string): string {
  // Colon-delimited triple. The deep-link router currently does a flat
  // state comparison against sessionStorage; we preserve that by storing
  // the same composite string both places.
  return `lark:${adapterId}:${nonce}`
}

/**
 * Parse the composite state. Returns `null` on shape mismatch so the
 * caller can surface a "state malformed" error.
 */
export function parseLarkOAuthState(state: string): { adapterId: string; nonce: string } | null {
  const parts = state.split(":")
  if (parts.length < 3) return null
  if (parts[0] !== "lark") return null
  const [, adapterId, ...rest] = parts
  return { adapterId, nonce: rest.join(":") }
}

// ---------------------------------------------------------------------------
// Connected user metadata stamped on AdapterInstanceRow.settings
// ---------------------------------------------------------------------------

export interface LarkConnectedUser {
  openId: string
  unionId?: string
  name?: string
  avatarUrl?: string
  email?: string
  enterpriseEmail?: string
  /** Wall-clock ms at which the access token expires. */
  expiresAtMs: number
  /** Wall-clock ms at which the refresh token expires. */
  refreshExpiresAtMs: number
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export interface HandleLarkOAuthDeps {
  /** Parsed state passed by the deep-link router. */
  state: string
}

/**
 * Complete the Lark OAuth exchange end-to-end. Throws when:
 *   - state malformed,
 *   - the adapter row isn't found,
 *   - app secret isn't in the keyring,
 *   - Lark's tenant-token or OIDC endpoints return a non-zero code.
 *
 * On success the user tokens land in keyring + `AdapterInstanceRow.settings`
 * gets a `connectedUser` field.
 */
export async function handleLarkOAuth(
  code: string,
  deps: HandleLarkOAuthDeps
): Promise<LarkConnectedUser> {
  const parsedState = parseLarkOAuthState(deps.state)
  if (!parsedState) {
    throw new Error("Lark OAuth state malformed — expected `lark:<adapterId>:<nonce>`")
  }
  const { adapterId } = parsedState

  // ── Step 1: resolve adapter row ────────────────────────────────────────
  const adapter = await getAdapterInstance(adapterId)
  if (!adapter) {
    throw new Error(`Lark OAuth: adapter ${adapterId} not found`)
  }
  if (adapter.type !== "lark") {
    throw new Error(`Lark OAuth: adapter ${adapterId} is not a Lark adapter (type=${adapter.type})`)
  }

  // ── Step 2: pull credentials from keyring (appId + appSecret both live in
  // the OS keyring — settings never carries them; the adapter runtime resolves
  // them the same way) ───────────────────────────────────────────────────
  const appId = ((await connectorsKeyringGet(adapterId, "appId")) ?? "").trim()
  if (!appId) {
    throw new Error(
      `Lark OAuth: appId not found in keyring (adapterId=${adapterId} credential=appId)`
    )
  }
  const appSecret = await connectorsKeyringGet(adapterId, "appSecret")
  if (!appSecret) {
    throw new Error(
      `Lark OAuth: app secret not found in keyring (adapterId=${adapterId} credential=appSecret)`
    )
  }

  // ── Step 3: durable pending — CSRF re-check + PKCE verifier + redirect_uri
  const pending = await getLarkOAuthPending(adapterId)
  if (!pending || pending.state !== deps.state) {
    throw new Error(
      "Lark OAuth: no matching pending authorization (session expired or state tampered) — retry Connect"
    )
  }

  // ── Step 4: exchange the code for a user token (v2), then resolve identity
  const tokens = await exchangeCodeForUserAccessToken({
    code,
    appId,
    appSecret,
    redirectUri: pending.redirectUri,
    codeVerifier: pending.codeVerifier,
  })
  const userInfo = await fetchLarkUserInfo(tokens.accessToken)

  // ── Step 5: persist tokens in keyring ──────────────────────────────────
  await connectorsKeyringSet(adapterId, "user_token", tokens.accessToken)
  await connectorsKeyringSet(adapterId, "user_refresh_token", tokens.refreshToken)
  // The in-memory cache in `auth.ts` holds a cold keyring read with no known
  // expiry, and `getUserAccessToken` serves such an entry indefinitely. Without
  // this eviction a re-authorization (new scopes, a different user) kept
  // sending as the PREVIOUS token for the rest of the process lifetime —
  // visible only as "the new scope still isn't working" until a restart.
  clearUserTokenCache(adapterId)

  // ── Step 6: stamp connected-user metadata ─────────────────────────────
  const now = Date.now()
  const connectedUser: LarkConnectedUser = {
    openId: userInfo.openId,
    unionId: userInfo.unionId,
    name: userInfo.name,
    avatarUrl: userInfo.avatarUrl,
    email: userInfo.email,
    enterpriseEmail: userInfo.enterpriseEmail,
    expiresAtMs: now + tokens.expiresInSec * 1000,
    refreshExpiresAtMs: now + tokens.refreshExpiresInSec * 1000,
  }
  // Persist the granted scopes (and audit a change vs the prior grant) so the
  // Connections detail can show what this adapter was authorized for.
  const { connectedScopes } = await recordGrantedScopes({
    adapterId,
    raw: tokens.scope,
    previous: adapter.settings.connectedScopes as ConnectedScopes | undefined,
    now,
  })
  await updateAdapterInstance(adapterId, {
    settings: { ...adapter.settings, connectedUser, connectedScopes },
    credentialsRef: {
      ...adapter.credentialsRef,
      accounts: Array.from(
        new Set([
          ...adapter.credentialsRef.accounts,
          // Mirror the keyring credential names so anyone auditing the
          // adapter row can see which entries point into the OS keyring
          // without grepping the platform-specific OAuth handler.
          "user_token",
          "user_refresh_token",
        ])
      ),
    },
  })

  // Clear-on-use: the pending authorization (PKCE verifier + redirect) is spent.
  await clearLarkOAuthPending(adapterId)

  return connectedUser
}
