/**
 * Lucide icons resolved by name, from a generated data catalog.
 *
 * # Why this exists
 *
 * Icons are looked up by *name* here — an A2UI `icon` string from a plugin, a
 * context-panel descriptor, a workbench panel key. A name-keyed lookup against
 * the `lucide-react` module means importing the whole module, and that pulls
 * every one of its ~1.6k icon components into the bundle whether or not any of
 * them is ever named. `lucide-catalog.generated.json` holds the same icons as
 * plain SVG node data instead, so the cost is data the bundler can serve rather
 * than 1.6k React components it must keep.
 *
 * # Why the component is rebuilt here
 *
 * The catalog stores node data, not components, so one has to be made — and it
 * has to render byte-identically to the real `lucide-react` icon, since both
 * appear on the same screen. `createCatalogIcon` therefore reproduces lucide's
 * own factory: the svg attribute set, the `absoluteStrokeWidth` scaling, the
 * `lucide` + per-icon class names, and the aria-hidden default that only
 * applies when the caller passed no accessibility prop of its own. That is a
 * deliberate duplication of an upstream implementation detail — if a
 * `lucide-react` bump changes how an icon renders, this factory has to follow,
 * and `pnpm lucide:check` is what notices the bump.
 *
 * The catalog is regenerated by `pnpm lucide:generate` and committed; it is not
 * built during predev/prebuild, so `pnpm lucide:check` (a registered gate) is
 * what keeps it from going stale.
 */
import { createElement, forwardRef } from "react"
import type { LucideIcon, LucideProps } from "lucide-react"

import catalog from "./lucide-catalog.generated.json"

type IconNode = Array<[string, Record<string, string | number>]>

interface CatalogEntry {
  className: string
  iconNode: IconNode
}

const generated = catalog as {
  entries: Record<string, CatalogEntry>
  iconNames: string[]
  exportNames: Record<string, string>
}
const entries = generated.entries
const iconNames = new Set(generated.iconNames)
const componentCache = new Map<string, LucideIcon>()

function hasAccessibilityProp(props: Record<string, unknown>): boolean {
  return Object.keys(props).some(
    (key) => key === "role" || key === "title" || key.startsWith("aria-")
  )
}

function createCatalogIcon(name: string, entry: CatalogEntry): LucideIcon {
  const CatalogIcon = forwardRef<SVGSVGElement, LucideProps>(function CatalogIcon(
    {
      color = "currentColor",
      size = 24,
      strokeWidth = 2,
      absoluteStrokeWidth = false,
      className,
      children,
      ...props
    },
    ref
  ) {
    const numericSize = typeof size === "number" ? size : Number.parseFloat(String(size))
    const resolvedStrokeWidth =
      absoluteStrokeWidth && Number.isFinite(numericSize) && numericSize > 0
        ? (Number(strokeWidth) * 24) / numericSize
        : strokeWidth
    const accessibility = hasAccessibilityProp(props as Record<string, unknown>)
      ? {}
      : { "aria-hidden": true }

    return createElement(
      "svg",
      {
        ref,
        xmlns: "http://www.w3.org/2000/svg",
        width: size,
        height: size,
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: color,
        strokeWidth: resolvedStrokeWidth,
        strokeLinecap: "round",
        strokeLinejoin: "round",
        className: ["lucide", entry.className, className].filter(Boolean).join(" "),
        ...accessibility,
        ...props,
      },
      ...entry.iconNode.map(([tag, attributes]) => createElement(tag, attributes)),
      children
    )
  })
  CatalogIcon.displayName = name
  return CatalogIcon
}

export function hasLucideIcon(name: string): boolean {
  return iconNames.has(name)
}

export function getLucideIcon(name: string): LucideIcon | null {
  const entry = entries[name]
  if (!entry) return null
  const cached = componentCache.get(name)
  if (cached) return cached
  const component = createCatalogIcon(name, entry)
  componentCache.set(name, component)
  return component
}

export function getLucideIconNames(): readonly string[] {
  return generated.iconNames
}

export function getLucideExport(name: string): LucideIcon | null {
  const catalogName = generated.exportNames[name]
  return catalogName ? getLucideIcon(catalogName) : null
}

export function getLucideExportNames(): readonly string[] {
  return Object.keys(generated.exportNames)
}

/**
 * Name-keyed icon record — the shape `lucide-react`'s own `icons` export has.
 *
 * Same lookup as [`getLucideIcon`], reached by index rather than by call. A
 * render site that names an icon at runtime needs the indexed form: a call
 * whose result is rendered reads to `react-hooks/static-components` as a
 * component built during render, an index does not. It is backed by the same
 * cache, so a repeated name still yields the identical component.
 *
 * All four traps are implemented rather than `get` alone, so `in`,
 * `Object.keys` and spread answer as well; `configurable: true` because the
 * proxy target is genuinely empty and a non-configurable descriptor for a
 * property the target lacks fails the proxy invariant check.
 */
export const lucideIcons: Record<string, LucideIcon | undefined> = new Proxy(
  {} as Record<string, LucideIcon | undefined>,
  {
    get: (_target, property) =>
      typeof property === "string" ? (getLucideIcon(property) ?? undefined) : undefined,
    has: (_target, property) => typeof property === "string" && hasLucideIcon(property),
    ownKeys: () => [...generated.iconNames],
    getOwnPropertyDescriptor: (_target, property) =>
      typeof property === "string" && hasLucideIcon(property)
        ? { configurable: true, enumerable: true }
        : undefined,
  }
)
