import { render, screen } from "@testing-library/react"
import userEvent from "@testing-library/user-event"

import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "./collapsible"

const setup = () => userEvent.setup()

describe("Collapsible", () => {
  it("keeps its content out of the DOM while closed", () => {
    render(
      <Collapsible>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    // Not merely hidden: Radix unmounts closed content unless `forceMount` is
    // set, so nothing inside a closed region is focusable or readable.
    expect(screen.queryByText("Body")).not.toBeInTheDocument()
  })

  it("reveals the content on activation and hides it again", async () => {
    const user = setup()
    render(
      <Collapsible>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    const trigger = screen.getByRole("button", { name: "Details" })
    await user.click(trigger)
    expect(screen.getByText("Body")).toBeInTheDocument()
    await user.click(trigger)
    expect(screen.queryByText("Body")).not.toBeInTheDocument()
  })

  it("wires the trigger to the content without the caller minting an id", async () => {
    const user = setup()
    render(
      <Collapsible>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    const trigger = screen.getByRole("button", { name: "Details" })
    expect(trigger).toHaveAttribute("aria-expanded", "false")
    expect(trigger).not.toHaveAttribute("aria-controls")

    await user.click(trigger)
    expect(trigger).toHaveAttribute("aria-expanded", "true")
    // The id is generated by Radix — two plugin instances on one page cannot
    // collide the way hand-written ids would.
    expect(screen.getByText("Body")).toHaveAttribute("id", trigger.getAttribute("aria-controls"))
  })

  it("honours defaultOpen", () => {
    render(
      <Collapsible defaultOpen>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    expect(screen.getByText("Body")).toBeInTheDocument()
  })

  it("defers to the caller when open is controlled", async () => {
    const user = setup()
    const onOpenChange = jest.fn()
    render(
      <Collapsible open={false} onOpenChange={onOpenChange}>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    await user.click(screen.getByRole("button", { name: "Details" }))
    expect(onOpenChange).toHaveBeenCalledWith(true)
    // Controlled: Radix asks, the caller decides — nothing opened on its own.
    expect(screen.queryByText("Body")).not.toBeInTheDocument()
  })

  it("blocks the trigger while disabled", async () => {
    const user = setup()
    const onOpenChange = jest.fn()
    render(
      <Collapsible disabled onOpenChange={onOpenChange}>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    const trigger = screen.getByRole("button", { name: "Details" })
    expect(trigger).toBeDisabled()
    await user.click(trigger)
    expect(onOpenChange).not.toHaveBeenCalled()
  })

  it("hands presence to the caller under forceMount", () => {
    render(
      <Collapsible>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent forceMount>Body</CollapsibleContent>
      </Collapsible>
    )

    // The escape hatch for a JS-driven animation — and the sharp edge that
    // comes with it: `forceMount` makes Radix's own `hidden` unreachable, so a
    // closed region stays fully VISIBLE unless whoever took presence also
    // decides what renders. `data-state` is all Radix still says.
    const content = screen.getByText("Body")
    expect(content).toHaveAttribute("data-state", "closed")
    expect(content).toBeVisible()
  })

  it("stamps a data-slot on every part", async () => {
    const user = setup()
    const { container } = render(
      <Collapsible>
        <CollapsibleTrigger>Details</CollapsibleTrigger>
        <CollapsibleContent>Body</CollapsibleContent>
      </Collapsible>
    )

    await user.click(screen.getByRole("button", { name: "Details" }))
    for (const slot of ["collapsible", "collapsible-trigger", "collapsible-content"]) {
      expect(container.querySelector(`[data-slot='${slot}']`)).not.toBeNull()
    }
  })

  it("passes styling and DOM props straight through", async () => {
    const user = setup()
    render(
      <Collapsible className="rounded-md">
        <CollapsibleTrigger className="w-full">Details</CollapsibleTrigger>
        <CollapsibleContent className="pt-2">Body</CollapsibleContent>
      </Collapsible>
    )

    const trigger = screen.getByRole("button", { name: "Details" })
    expect(trigger.className).toBe("w-full")
    expect(trigger.parentElement?.className).toBe("rounded-md")
    await user.click(trigger)
    // Unstyled by design — the caller's class is the only one on the element.
    expect(screen.getByText("Body").className).toBe("pt-2")
  })
})
