/**
 * `/goal` Command — type model. (ADR-0013)
 *
 * Two Dexie tables back the subsystem (see `lib/db/schema.ts` v30):
 *
 *   • `chatGoals`       — one row per goal; session-scoped (one active goal
 *                         per session at a time, terminal goals stick around
 *                         for the History view).
 *   • `chatGoalEvents`  — one row per lifecycle event (created / turn /
 *                         judge / exit / user_action). Drives the Activity
 *                         tab and the audit trail.
 *
 * Lifecycle: `active` is the only non-terminal status that the turn driver
 * can pump. `paused` can be resumed back to `active`. Everything else is
 * terminal — never returns to `active`.
 *
 * The `generationId` field is the race guard: every status mutation rotates
 * it, and `turn-driver.ts` checks the captured generation before scheduling
 * the next continuation. A user `/goal pause` / `/goal stop` / `/goal
 * update` mid-turn → bumped generation → in-flight judge result is
 * silently dropped.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Goal
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Status state machine. Order in this union is also the priority order used
 * by `lib/goal/exit-conditions.ts:evaluateExitConditions`.
 *
 *   active           → driving forward
 *   paused           → resumable; turn driver yields
 *   completed        → judge said done=true (terminal)
 *   stopped          → user `/goal stop|cancel|clear` (terminal)
 *   budget_limited   → tokensUsed >= maxTokens (terminal)
 *   turn_limited     → turnsUsed >= maxTurns (terminal)
 *   timed_out        → wall-clock exceeded timeoutMs (terminal)
 *   preempted        → user typed a non-slash message mid-loop (terminal)
 */
export type GoalStatus =
  | "active"
  | "paused"
  | "completed"
  | "stopped"
  | "budget_limited"
  | "turn_limited"
  | "timed_out"
  | "preempted"

/**
 * A single decomposed step of a goal's objective (ADR-0019 "Future Work" →
 * subgoal decomposition, landed). Generated by `lib/goal/subgoals.ts` from
 * the redacted `safeObjective` and stored as a JSON array on the `Goal` row
 * (non-indexed — Dexie persists it without a schema-version bump). `done`
 * is toggled manually from the Subgoals tab or auto-marked by the judge's
 * optional `completedSubgoals` verdict.
 */
export interface GoalSubgoal {
  /** UUIDv4, stable across re-renders and toggles. */
  id: string
  /** The step text (already redacted — derived from `safeObjective`). */
  text: string
  /** Whether the step has been completed. */
  done: boolean
  /** Ascending display/order index (0-based). */
  order: number
}

/** True when the status is terminal (cannot transition out). */
export function isTerminalGoalStatus(status: GoalStatus): boolean {
  return (
    status === "completed" ||
    status === "stopped" ||
    status === "budget_limited" ||
    status === "turn_limited" ||
    status === "timed_out" ||
    status === "preempted"
  )
}

/**
 * Quiet-hours window during which the goal loop defers its next
 * continuation. Identical shape to `ConversationOverrideRow.quietHours` so
 * `lib/connectors/outbound-runner.ts:isInQuietHours` / `msUntilQuietEnd`
 * consume it unchanged.
 */
export interface GoalQuietHours {
  /** Window start, "HH:mm" 24-hour. */
  from: string
  /** Window end, "HH:mm" 24-hour. Crosses midnight when `to < from`. */
  to: string
  /** IANA time zone id, e.g. "Asia/Shanghai". */
  tz: string
}

/** Per-goal knobs — defaults come from `AppSettings.goals` via `lib/goal/runtime.ts:resolveGoalConfig`. */
export interface GoalConfig {
  /** Hard cap on completed turns. Default 20 (Hermes default). Range 1..100. */
  maxTurns: number
  /** Hard cap on cumulative tokens (input + output). Default 200_000. */
  maxTokens: number
  /**
   * Consecutive judge JSON parse failures before the goal auto-pauses
   * (fail-OPEN: never wedge on judge flakiness). Default 3 (Hermes default).
   */
  maxJudgeFailures: number
  /** Wall-clock timeout in ms. Default 30 * 60_000 (30 min). */
  timeoutMs: number
  /**
   * User-supplied "or stop after N turns" condition appended to the system
   * prompt verbatim. Claude Code-style escape hatch when the model's own
   * judgment of "done" feels unreliable for the task.
   */
  inlineStopCondition?: string

  // ── Judge customization (ADR-0019 Phase 2) ──────────────────────────────
  /**
   * Judge model id (e.g. "claude-haiku-4-5"). Undefined → the chat hook
   * builds the judge client from the session's chat model.
   */
  judgeModel?: string
  /** Provider id paired with `judgeModel`. Undefined → session/app provider. */
  judgeProvider?: string
  /** Full replacement for `JUDGE_SYSTEM_PROMPT`. Empty/undefined → built-in. */
  judgePromptOverride?: string
  /** Judge sampling temperature. Undefined → 0 (judge wants determinism). */
  judgeTemperature?: number
  /** Hard cap on judge response tokens. Undefined → 200. */
  judgeMaxTokens?: number

  // ── Pacing / manual control (ADR-0019 Phase 2) ──────────────────────────
  /**
   * When true, the loop HOLDS the continuation — the user clicks "Continue"
   * on the status pill to advance one turn. See `gateContinuation`.
   */
  manualContinue?: boolean
  /** Minimum wall-clock ms between auto-continuations. Undefined → 0 (none). */
  continuationIntervalMs?: number
  /** Defer the next continuation while inside this window. */
  quietHours?: GoalQuietHours

  // ── Completion-promise gate + adaptive pacing ────────────────────────────
  /**
   * Anti false-completion gate (Ralph-style). When set, a judge `done=true`
   * verdict does NOT terminate the goal directly: the loop runs one
   * verification turn asking the model to emit the exact
   * `<promise>TEXT</promise>` token ONLY if the objective is unequivocally
   * satisfied (with an explicit no-lying instruction). Empty/undefined →
   * the judge verdict terminates the goal exactly as before.
   */
  completionPromise?: string
  /**
   * Consecutive failed verification turns before the gate is overridden —
   * the judge has re-affirmed done that many times, so the goal completes
   * with a `promise_denied(overridden)` audit event. Undefined → 3.
   */
  maxPromiseDenials?: number
  /**
   * Opt-in adaptive pacing: continuation messages instruct the model to
   * suggest the next delay (`<next-delay minutes=N reason="..."/>`). The
   * gate honors max(continuationIntervalMs, suggestion) — the model can only
   * SLOW the loop, never speed it below the configured interval. Bounded
   * 1–60 minutes.
   */
  adaptivePacing?: boolean
}

export interface Goal {
  /** UUIDv4. Globally unique; safe to use as a Dexie primary key. */
  id: string
  /** FK → ChatSession.id. Session-scoped: at most one row with status==="active" per sessionId. */
  sessionId: string
  /**
   * Snapshot of the character at goal creation time. UI only — used by the
   * Activity tab to render the right avatar even after the user switches
   * the session's character.
   */
  characterId?: string
  /**
   * User's original objective text, preserved verbatim for the UI to
   * display ("show me what I asked for"). NEVER concatenated into a prompt
   * directly — `safeObjective` is what reaches the LLM.
   */
  rawObjective: string
  /**
   * PII-redacted objective. Goes into `<objective>` XML tag in the system
   * prompt and into judge prompts. Built by `lib/goal/redact-objective.ts`.
   */
  safeObjective: string
  /**
   * Encrypted PII↔placeholder map (base64 ciphertext + nonce + tag).
   * Tauri: encrypted with the keyring-derived data key. Web: AES-GCM with a
   * key derived from `AppSettings.id` (best-effort; the web build flags this
   * as a degraded mode in the docs). Empty string when no PII was found.
   */
  redactionMapEnc: string
  status: GoalStatus
  /** Number of model turns completed against this goal so far. */
  turnsUsed: number
  /** Cumulative input + output tokens billed against this goal. */
  tokensUsed: number
  /**
   * Consecutive judge parse failures since the last successful judge call.
   * Resets to 0 on success. When ≥ `config.maxJudgeFailures` the
   * `judge_failed_too_many` exit fires.
   */
  judgeFailureCount: number
  config: GoalConfig
  /**
   * Race guard. Every status mutation rotates this string (UUIDv4). The turn
   * driver captures the generationId at evaluation start and refuses to
   * schedule the next continuation if it changed.
   */
  generationId: string
  createdAt: number
  updatedAt: number
  /** Set when status becomes terminal. Drives History sorting + reset countdown. */
  endedAt?: number
  /**
   * Decomposed checklist of the objective (subgoal decomposition). Absent
   * until the user generates it from the Subgoals tab. Stored inline as JSON
   * — no Dexie index, so adding it needs no schema migration.
   */
  subgoals?: GoalSubgoal[]
  /** Timestamp (ms) of the last `generateSubgoals` run. Drives "regenerate" UX. */
  subgoalsGeneratedAt?: number
  /**
   * True while the completion-promise verification turn is in flight: the
   * NEXT response is graded for the `<promise>` token instead of being
   * re-judged. Persisted (inline, no schema bump) so a reload
   * mid-verification resumes correctly.
   */
  awaitingPromise?: boolean
  /**
   * Consecutive failed verification turns. Persists across re-armed gates
   * (only a confirmed promise or an objective update resets it) so repeated
   * judge-done → denial cycles eventually override at `maxPromiseDenials`.
   */
  promiseDenialCount?: number
  /**
   * Epoch ms of the next scheduled auto-continuation — set when the pacing
   * gate defers, cleared on dispatch. Drives the status pill's
   * "next continuation at…" footnote. Inline, no schema bump.
   */
  nextContinuationAt?: number
  /** Why the continuation was deferred — i18n category for the pill footnote. */
  nextContinuationSource?: "interval" | "quiet_hours" | "model_suggested"
}

// ─────────────────────────────────────────────────────────────────────────────
// GoalEvent — append-only lifecycle log
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Discriminator for `GoalEvent.payload` shape. Each kind has a payload
 * declared inline below; the union here drives `chatGoalEvents` index lookups
 * (filter by kind in the Activity tab).
 */
export type GoalEventKind =
  | "goal_created"
  | "objective_updated"
  | "turn_started"
  | "turn_completed"
  | "judge_evaluated"
  | "judge_parse_failed"
  | "exit_triggered"
  | "user_paused"
  | "user_resumed"
  | "user_stopped"
  | "config_updated"
  | "subgoals_generated"
  | "promise_requested"
  | "promise_confirmed"
  | "promise_denied"
  | "pacing_decided"

/**
 * Per-kind payloads. Keep these structurally typed (TypeScript discriminated
 * union via `kind`) — it lets the Activity tab render kind-specific cards
 * without runtime checks beyond the discriminator.
 */
export type GoalEventPayload =
  | { kind: "goal_created"; safeObjective: string; config: GoalConfig }
  | { kind: "objective_updated"; oldSafeObjective: string; newSafeObjective: string }
  | { kind: "turn_started"; turnNumber: number }
  | {
      kind: "turn_completed"
      turnNumber: number
      tokensDelta: number
      modelMessageId?: string
    }
  | {
      kind: "judge_evaluated"
      done: boolean
      reason: string
      judgeTokens: number
    }
  | { kind: "judge_parse_failed"; raw: string; failureCount: number }
  | { kind: "exit_triggered"; exit: ExitReason; reason: string }
  | { kind: "user_paused" }
  | { kind: "user_resumed" }
  | { kind: "user_stopped" }
  | { kind: "config_updated"; before: GoalConfig; after: GoalConfig }
  | { kind: "subgoals_generated"; count: number }
  | { kind: "promise_requested"; turnNumber: number }
  | { kind: "promise_confirmed"; turnNumber: number }
  | {
      kind: "promise_denied"
      turnNumber: number
      denialCount: number
      /** True when the denial cap was reached and the gate completed anyway. */
      overridden: boolean
    }
  | {
      kind: "pacing_decided"
      source: "interval" | "quiet_hours" | "model_suggested"
      untilMs: number
      /** The model-suggested delay (clamped, ms) when adaptive pacing fed the decision. */
      suggestedMs?: number
    }

export interface GoalEvent {
  /** UUIDv4 primary key. */
  id: string
  /** FK → Goal.id. Cascade-delete is performed at the CRUD layer (lib/db/goals.ts). */
  goalId: string
  kind: GoalEventKind
  ts: number
  payload: GoalEventPayload
}

// ─────────────────────────────────────────────────────────────────────────────
// Exit reasons — discriminated union returned by `evaluateExitConditions`.
// ─────────────────────────────────────────────────────────────────────────────

export type ExitReason =
  | "user_stopped"
  | "preempted"
  | "turn_limited"
  | "budget_limited"
  | "timed_out"
  | "judge_failed_too_many"
  | "judge_done"

/**
 * Maps an exit reason to the terminal/paused status the goal should land in.
 * Two non-terminal exits use `paused` so the user can manually resume.
 */
export function statusForExit(exit: ExitReason): GoalStatus {
  switch (exit) {
    case "user_stopped":
      return "stopped"
    case "preempted":
      return "preempted"
    case "turn_limited":
      return "turn_limited"
    case "budget_limited":
      return "budget_limited"
    case "timed_out":
      return "timed_out"
    case "judge_failed_too_many":
      return "paused"
    case "judge_done":
      return "completed"
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// AppSettings extension — global defaults set in Settings → Goals.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Optional `AppSettings.goals` block holding the defaults the runtime applies
 * when creating a fresh Goal. Absent → falls back to the hard-coded defaults
 * in `lib/goal/runtime.ts:DEFAULT_GOAL_CONFIG`.
 */
export interface GoalDefaults {
  maxTurns?: number
  maxTokens?: number
  maxJudgeFailures?: number
  timeoutMs?: number
  /** When true, every new goal is created paused (user must `/goal resume` to start). */
  startPaused?: boolean
  /**
   * When true, the composer pill is shown but the auto-continuation message
   * is NOT dispatched — the user must hit a "Continue" button per turn.
   * Reserved for users who want a manual loop without losing the persistent
   * objective. Wired in ADR-0019 Phase 2 via `gateContinuation`.
   */
  manualContinue?: boolean

  // ── Mirrors of the new per-goal knobs (defaults for fresh goals) ─────────
  /** Default judge model id for new goals. */
  judgeModel?: string
  /** Default judge provider id for new goals. */
  judgeProvider?: string
  /** Default judge system-prompt override for new goals. */
  judgePromptOverride?: string
  /** Default judge sampling temperature for new goals. */
  judgeTemperature?: number
  /** Default judge response-token cap for new goals. */
  judgeMaxTokens?: number
  /** Default min ms between auto-continuations for new goals. */
  continuationIntervalMs?: number
  /** Default quiet-hours window for new goals. */
  quietHours?: GoalQuietHours
  /** Default denial cap for the completion-promise gate on new goals. */
  maxPromiseDenials?: number
  /** Default adaptive-pacing opt-in for new goals. */
  adaptivePacing?: boolean
}

// ─────────────────────────────────────────────────────────────────────────────
// Continuation gate (ADR-0019 Phase 2) — pacing decision for the chat hook.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Decision returned by `lib/goal/pacing.ts:gateContinuation` after the turn
 * driver yields `{ kind: "continue" }`. The chat hook honors it:
 *   • `send`  → dispatch the continuation immediately.
 *   • `hold`  → wait for the user to click "Continue" (manualContinue).
 *   • `defer` → re-check at `untilMs` (quiet-hours window / interval gap).
 */
export type ContinuationGate =
  | { kind: "send" }
  | { kind: "hold"; reason: "manual" }
  | { kind: "defer"; untilMs: number; reason: "quiet_hours" | "interval" | "model_suggested" }

// ─────────────────────────────────────────────────────────────────────────────
// Goal templates (ADR-0019 Phase 2) — preset objectives backed by Dexie v53.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A reusable preset objective ("Review this PR", "Summarise my week"). Stored
 * in the `goalTemplates` Dexie table (v53). Built-ins are seeded on access
 * and clone-on-edit; user templates are fully mutable.
 */
export interface GoalTemplate {
  /** Stable id. Built-ins use a `gtpl_builtin_*` prefix; user rows `gtpl_<uuid>`. */
  id: string
  /** Short title shown in the picker. */
  title: string
  /** Raw objective text (PII redaction happens at `createGoal`, not here). */
  objectiveText: string
  /** Optional per-template config overrides applied when creating the goal. */
  configOverrides?: Partial<GoalConfig>
  /** True for seeded built-ins (clone-on-edit; cannot be deleted). */
  builtin: boolean
  /** User favourite — favourites sort first in the picker. */
  isFavorite: boolean
  /** Manual sort order (ascending). */
  sortOrder: number
  createdAt: number
  updatedAt: number
}
