/**
 * Pure extractor for the Claude Agent SDK's public type surface.
 *
 * Reads the shipped `sdk.d.ts` and returns the five vocabularies the unified
 * execution contract has to keep up with: `Options` fields, `Query` methods,
 * the `SDKMessage` union, `HOOK_EVENTS`, and the top-level exports.
 *
 * Why parse the `.d.ts` instead of importing the package: the gate has to run
 * in a plain `node --test` process with no TypeScript toolchain, and it has to
 * see *type-level* surface (`Options` is a type, not a runtime value) that no
 * amount of runtime reflection can recover. The file is generated by
 * api-extractor and is therefore mechanically regular — 4-space member
 * indentation, one declaration per `export declare`, `};` closing at column 0.
 *
 * No I/O here on purpose: every function takes source text so the tests can
 * feed fixtures instead of the installed package.
 */

/** Allowed `status` values for a manifest entry. */
export const SURFACE_STATUSES = ["supported", "planned", "host-only", "not-applicable"]

/** The five surface kinds, in manifest order. */
export const SURFACE_KINDS = ["options", "queryMethods", "messages", "hookEvents", "exports"]

/**
 * Kinds recorded as `name -> { status, capability? }` because each member is a
 * capability decision someone has to make. The remaining kind, `exports`, is a
 * plain sorted list: it is 238 entries, most of them type leaves like
 * `PostCompactHookInput` that exist only to type a member of a kind already
 * triaged above. Demanding a capability verdict per leaf would bury the
 * handful of entries that carry one. Drift detection still applies to it.
 */
export const TRIAGED_KINDS = ["options", "queryMethods", "messages", "hookEvents"]

/**
 * Extract the brace-delimited body of a declaration.
 *
 * Scans forward from the line whose text starts with `header`, tracking brace
 * depth from the first `{` on that line, and returns every line strictly
 * inside the outermost braces. Returns `null` when the header is absent so
 * callers can distinguish "no such declaration" from "declaration is empty".
 *
 * Brace counting ignores braces inside string literals and line comments,
 * which the SDK uses freely in doc examples (`{ Bash: 'mcp__workspace__bash' }`).
 *
 * @param {string} source
 * @param {string} header
 * @returns {string[] | null}
 */
export function extractBlock(source, header) {
  const lines = source.split("\n")
  const start = lines.findIndex((l) => l.startsWith(header))
  if (start === -1) return null

  const body = []
  let depth = 0
  let started = false

  for (let i = start; i < lines.length; i++) {
    const line = lines[i]
    const stripped = stripNonCode(line)

    let opensOnThisLine = 0
    for (const ch of stripped) {
      if (ch === "{") {
        depth++
        opensOnThisLine++
      } else if (ch === "}") {
        depth--
        if (started && depth === 0) return body
      }
    }

    if (!started && opensOnThisLine > 0) {
      started = true
      continue
    }
    if (started) body.push(line)
  }

  // Unbalanced braces mean the file is not what we think it is. Surfacing that
  // as an error beats silently returning a truncated surface that the gate
  // would then report as "fields removed".
  throw new Error(`unterminated block for declaration: ${header}`)
}

/**
 * Blank out string literals and `//` comments so brace counting only sees
 * structural braces. Preserves length so nothing else shifts.
 *
 * @param {string} line
 * @returns {string}
 */
export function stripNonCode(line) {
  let out = ""
  let quote = null

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]

    if (quote) {
      out += " "
      if (ch === "\\") {
        out += " "
        i++
      } else if (ch === quote) {
        quote = null
      }
      continue
    }

    if (ch === '"' || ch === "'" || ch === "`") {
      quote = ch
      out += " "
      continue
    }

    if (ch === "/" && line[i + 1] === "/") return out + " ".repeat(line.length - i)
    if (ch === "*" || (ch === "/" && line[i + 1] === "*")) {
      // Block-comment bodies in this file are always their own lines starting
      // with ` *`, so treating a leading `*` as comment is enough.
      if (out.trim() === "") return out + " ".repeat(line.length - i)
    }

    out += ch
  }
  return out
}

/**
 * Top-level member names of a block, i.e. lines at exactly one indent level.
 *
 * @param {string[]} body
 * @param {RegExp} pattern must capture the name in group 1
 * @returns {string[]}
 */
function topLevelMembers(body, pattern) {
  const names = []
  let depth = 0

  for (const line of body) {
    const stripped = stripNonCode(line)
    if (depth === 0) {
      const m = line.match(pattern)
      if (m) names.push(m[1])
    }
    for (const ch of stripped) {
      if (ch === "{" || ch === "(" || ch === "[") depth++
      else if (ch === "}" || ch === ")" || ch === "]") depth--
    }
  }
  return names
}

/**
 * Field names of `export declare type Options = { … }`.
 *
 * @param {string} source
 * @returns {string[]}
 */
export function extractOptionsFields(source) {
  const body = extractBlock(source, "export declare type Options = {")
  if (!body) throw new Error("sdk.d.ts: `export declare type Options` not found")
  return topLevelMembers(body, /^ {4}([A-Za-z_$][\w$]*)\??:/)
}

/**
 * Method names of the `Query` interface.
 *
 * @param {string} source
 * @returns {string[]}
 */
export function extractQueryMethods(source) {
  const body = extractBlock(source, "export declare interface Query extends")
  if (!body) throw new Error("sdk.d.ts: `export declare interface Query` not found")
  return topLevelMembers(body, /^ {4}([A-Za-z_$][\w$]*)\(/)
}

/**
 * Members of the `SDKMessage` union. Handles the declaration spanning several
 * lines, which it does whenever prettier decides the union is too wide.
 *
 * @param {string} source
 * @returns {string[]}
 */
export function extractMessageTypes(source) {
  const marker = "export declare type SDKMessage ="
  const idx = source.indexOf(marker)
  if (idx === -1) throw new Error("sdk.d.ts: `export declare type SDKMessage` not found")

  const end = source.indexOf(";", idx)
  if (end === -1) throw new Error("sdk.d.ts: unterminated SDKMessage union")

  return source
    .slice(idx + marker.length, end)
    .split("|")
    .map((s) => s.trim())
    .filter(Boolean)
}

/**
 * String literals of `export declare const HOOK_EVENTS: readonly [ … ]`.
 *
 * @param {string} source
 * @returns {string[]}
 */
export function extractHookEvents(source) {
  const marker = "export declare const HOOK_EVENTS:"
  const idx = source.indexOf(marker)
  if (idx === -1) throw new Error("sdk.d.ts: `HOOK_EVENTS` not found")

  const open = source.indexOf("[", idx)
  const close = source.indexOf("]", open)
  if (open === -1 || close === -1) throw new Error("sdk.d.ts: malformed HOOK_EVENTS array")

  return [...source.slice(open, close).matchAll(/"([^"]+)"/g)].map((m) => m[1])
}

/**
 * Names of every top-level `export declare …`.
 *
 * Types and interfaces are included: `Options`, `SessionStore` and the hook
 * input types are all type-only, and a breaking change to them is exactly what
 * this gate exists to catch.
 *
 * @param {string} source
 * @returns {string[]}
 */
export function extractExports(source) {
  const pattern =
    /^export declare (?:abstract )?(?:function|class|const|type|interface|enum)\s+([A-Za-z_$][\w$]*)/gm
  return [...source.matchAll(pattern)].map((m) => m[1])
}

/**
 * The full surface, deduplicated and sorted so the manifest diff is stable.
 *
 * @param {string} source
 * @returns {Record<string, string[]>}
 */
export function extractSurface(source) {
  const sortUnique = (xs) => [...new Set(xs)].sort()
  return {
    options: sortUnique(extractOptionsFields(source)),
    queryMethods: sortUnique(extractQueryMethods(source)),
    messages: sortUnique(extractMessageTypes(source)),
    hookEvents: sortUnique(extractHookEvents(source)),
    exports: sortUnique(extractExports(source)),
  }
}

/**
 * Diff an extracted surface against a manifest.
 *
 * `added` is the dangerous direction: a new SDK field nobody triaged is how
 * capabilities silently go unsupported. `removed` catches the opposite — the
 * manifest still promising something the SDK dropped. Both fail the gate.
 *
 * @param {Record<string, string[]>} surface
 * @param {{ surface?: Record<string, Record<string, { status?: string }>> }} manifest
 * @returns {Array<{ kind: string, added: string[], removed: string[], badStatus: string[] }>}
 */
export function diffSurface(surface, manifest) {
  const declared = manifest?.surface ?? {}
  const results = []

  for (const kind of SURFACE_KINDS) {
    const actual = new Set(surface[kind] ?? [])
    const entries = declared[kind] ?? (TRIAGED_KINDS.includes(kind) ? {} : [])
    const triaged = TRIAGED_KINDS.includes(kind)
    const recorded = new Set(triaged ? Object.keys(entries) : entries)

    const added = [...actual].filter((n) => !recorded.has(n)).sort()
    const removed = [...recorded].filter((n) => !actual.has(n)).sort()
    const badStatus = triaged
      ? Object.entries(entries)
          .filter(([, v]) => !SURFACE_STATUSES.includes(v?.status))
          .map(([n]) => n)
          .sort()
      : []

    if (added.length || removed.length || badStatus.length) {
      results.push({ kind, added, removed, badStatus })
    }
  }

  return results
}
