export type BuiltInProviderType = "cloud" | "local"
export type BuiltInProviderCategory =
  | "flagship"
  | "aggregator"
  | "specialized"
  | "local"
  | "enterprise"
export type BuiltInProviderProtocol = "openai" | "anthropic" | "gemini"
export type ProviderUseCase = "coding"
export type BuiltInProviderFamily =
  | "openai-compatible"
  | "anthropic-native"
  | "gemini-native"
  | "openrouter"
  | "local-openai-compatible"
  | "proxy-openai-compatible"
export type BuiltInProviderAdapterId =
  | "openai-compatible"
  | "anthropic"
  | "gemini"
  | "openrouter"
  | "local-openai-compatible"
  | "cliproxyapi"
export type BuiltInProviderQuickAddMode = "shortcut" | "promoted"
export type BuiltInProviderQuickAddCategory = "china" | "global" | "proxy"

export interface BuiltInProviderQuickAddMetadata {
  mode: BuiltInProviderQuickAddMode
  category: BuiltInProviderQuickAddCategory
  popular?: boolean
}

export interface BuiltInProviderQuickAddPreset {
  id: string
  name: string
  description: string
  baseURL: string
  apiProtocol: BuiltInProviderProtocol
  models: string[]
  modelEntries: BuiltInProviderModelEntry[]
  defaultModel: string
  docsUrl?: string
  dashboardUrl?: string
  category: BuiltInProviderQuickAddCategory
  popular?: boolean
}

export interface BuiltInProviderModelPricing {
  promptPer1M: number
  completionPer1M: number
  cachedInputPer1M?: number
  cacheCreationPer1M?: number
  batchInputPer1M?: number
  batchOutputPer1M?: number
  audioInputPer1M?: number
  audioOutputPer1M?: number
  currency?: "USD" | "CNY"
}

export interface BuiltInProviderModelEntry {
  id: string
  name: string
  contextLength: number
  maxOutputTokens?: number
  supportsTools: boolean
  supportsVision: boolean
  supportsAudio: boolean
  supportsVideo: boolean
  supportsStreaming: boolean
  supportsReasoning?: boolean
  supportsImageGeneration?: boolean
  supportsEmbedding?: boolean
  pricing?: BuiltInProviderModelPricing
  recommendedFor?: ProviderUseCase[]
}

export interface BuiltInProviderCodingPackage {
  id: "coding"
  label: string
  defaultModel: string
  modelIds: string[]
  mcpBundles?: BuiltInProviderCodingPackageMcpBundle[]
}

export type BuiltInProviderCodingPackageMcpTransport = "stdio" | "sse" | "streamableHttp"

export interface BuiltInProviderCodingPackageMcpCredentialBinding {
  type: "env" | "header"
  key: string
  prefix?: string
}

export interface BuiltInProviderCodingPackageMcpBundle {
  id: string
  name: string
  description: string
  transport: BuiltInProviderCodingPackageMcpTransport
  command?: string
  args?: string[]
  url?: string
  messageUrl?: string
  envKeys?: string[]
  envDefaults?: Record<string, string>
  credentialBinding?: BuiltInProviderCodingPackageMcpCredentialBinding
  fallbackToSse?: boolean
  docsUrl?: string
}

export interface BuiltInProviderOAuthConfig {
  authorizationUrl: string
  tokenUrl: string
  clientId?: string
  scope?: string
  pkceRequired?: boolean
  callbackPath: string
}

export interface BuiltInProviderCompatibilityRule {
  protocol: BuiltInProviderProtocol
  baseURLs: string[]
  nameIncludes?: string[]
  modelPrefixes?: string[]
}

export interface BuiltInProviderCatalogEntry {
  id: string
  name: string
  type: BuiltInProviderType
  protocol: BuiltInProviderProtocol
  family?: BuiltInProviderFamily
  adapter?: BuiltInProviderAdapterId
  apiKeyRequired: boolean
  baseURLRequired: boolean
  defaultModel: string
  defaultEnabled: boolean
  defaultBaseURL?: string
  defaultSettingsBaseURL?: string
  placeholderApiKey?: string
  category?: BuiltInProviderCategory
  description?: string
  website?: string
  dashboardUrl?: string
  docsUrl?: string
  pricingUrl?: string
  supportsOAuth?: boolean
  oauthConfig?: BuiltInProviderOAuthConfig
  models?: BuiltInProviderModelEntry[]
  quickAdd?: BuiltInProviderQuickAddMetadata
  codingPackage?: BuiltInProviderCodingPackage
  compatibility?: BuiltInProviderCompatibilityRule
}

function createQuickAddModelEntries(modelIds: string[]): BuiltInProviderModelEntry[] {
  return modelIds.map((modelId) => ({
    id: modelId,
    name: modelId,
    contextLength: 0,
    supportsTools: true,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsStreaming: true,
  }))
}

export const BUILT_IN_PROVIDER_IDS = [
  "openai",
  "anthropic",
  "google",
  "deepseek",
  "groq",
  "mistral",
  "xai",
  "togetherai",
  "openrouter",
  "cohere",
  "fireworks",
  "cerebras",
  "sambanova",
  "siliconflow",
  "moonshot",
  "doubao",
  "baichuan",
  "lingyi",
  "stepfun",
  "perplexity",
  "deepinfra",
  "novita",
  "lepton",
  "aiproxy",
  "ohmygpt",
  "zhipu",
  "minimax",
  "ollama",
  "lmstudio",
  "llamacpp",
  "llamafile",
  "vllm",
  "localai",
  "jan",
  "textgenwebui",
  "koboldcpp",
  "tabbyapi",
  "cliproxyapi",
  "yi",
  "qwen",
  "volcengine",
  "internlm",
  "glm4",
  // NEW: Enterprise platforms
  "bedrock",
  "azure",
  // NEW: Inference platforms
  "nvidia",
  "huggingface",
  "replicate",
  "cloudflare",
  // NEW: Developer platforms
  "github",
  "ai21",
  // NEW: Chinese providers
  "baidu",
  "tencent",
  "modelscope",
  // NEW: Specialized
  "voyage",
  "jina",
  "fal",
] as const

export type BuiltInProviderId = (typeof BUILT_IN_PROVIDER_IDS)[number]

const BUILT_IN_PROVIDER_ID_SET = new Set<string>(BUILT_IN_PROVIDER_IDS)

export function isBuiltInProviderId(providerId: string): providerId is BuiltInProviderId {
  return BUILT_IN_PROVIDER_ID_SET.has(providerId)
}

const CATALOG_ENTRIES: Record<BuiltInProviderId, BuiltInProviderCatalogEntry> = {
  openai: {
    id: "openai",
    name: "OpenAI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "gpt-4.1",
    defaultEnabled: true,
    category: "flagship",
    description: "Leading AI research organization with GPT and reasoning models",
    website: "https://openai.com",
    dashboardUrl: "https://platform.openai.com/api-keys",
    docsUrl: "https://platform.openai.com/docs",
    pricingUrl: "https://openai.com/api/pricing/",
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic",
    type: "cloud",
    protocol: "anthropic",
    family: "anthropic-native",
    adapter: "anthropic",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "claude-sonnet-4-6",
    defaultEnabled: true,
    category: "flagship",
    description: "Claude models focused on reasoning and safety",
    website: "https://anthropic.com",
    dashboardUrl: "https://console.anthropic.com/settings/keys",
    docsUrl: "https://docs.anthropic.com",
    pricingUrl: "https://www.anthropic.com/pricing",
  },
  google: {
    id: "google",
    name: "Google AI",
    type: "cloud",
    protocol: "gemini",
    family: "gemini-native",
    adapter: "gemini",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "gemini-2.5-flash",
    defaultEnabled: true,
    category: "flagship",
    description: "Gemini 3.1 Pro, 3 Flash, 2.5 Pro/Flash/Flash-Lite — all with 1M context windows",
    website: "https://ai.google.dev",
    dashboardUrl: "https://aistudio.google.com/app/apikey",
    docsUrl: "https://ai.google.dev/docs",
    pricingUrl: "https://ai.google.dev/gemini-api/docs/pricing",
    models: [
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        contextLength: 1000000,
        maxOutputTokens: 65536,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsVideo: false,
        pricing: { promptPer1M: 2, completionPer1M: 12 },
      },
      {
        id: "gemini-3.1-flash-lite-preview",
        name: "Gemini 3.1 Flash-Lite Preview",
        contextLength: 1000000,
        maxOutputTokens: 65536,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.25, completionPer1M: 1.5 },
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash Preview",
        contextLength: 1000000,
        maxOutputTokens: 65536,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsVideo: false,
        pricing: { promptPer1M: 0.5, completionPer1M: 3 },
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        contextLength: 1000000,
        maxOutputTokens: 65536,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsVideo: false,
        pricing: { promptPer1M: 1.25, completionPer1M: 10 },
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        contextLength: 1000000,
        maxOutputTokens: 65536,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsVideo: false,
        pricing: { promptPer1M: 0.3, completionPer1M: 2.5 },
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash-Lite",
        contextLength: 1000000,
        maxOutputTokens: 65536,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.1, completionPer1M: 0.4 },
      },
    ],
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "deepseek-v4-flash",
    defaultEnabled: false,
    defaultBaseURL: "https://api.deepseek.com/v1",
    category: "specialized",
    description: "DeepSeek chat and reasoning models from a Chinese AI lab",
    website: "https://deepseek.com",
    dashboardUrl: "https://platform.deepseek.com/api_keys",
    models: [
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        contextLength: 1000000,
        maxOutputTokens: 384000,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 1.74, completionPer1M: 3.48, cachedInputPer1M: 0.0145 },
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        contextLength: 1000000,
        maxOutputTokens: 384000,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 0.14, completionPer1M: 0.28, cachedInputPer1M: 0.0028 },
      },
      {
        id: "deepseek-r1-0528",
        name: "DeepSeek R1 0528",
        contextLength: 128000,
        maxOutputTokens: 163840,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 0.55, completionPer1M: 2.19, cachedInputPer1M: 0.14 },
      },
    ],
  },
  groq: {
    id: "groq",
    name: "Groq",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "llama-4-scout-17b-16e-instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api.groq.com/openai/v1",
    category: "specialized",
    description: "Ultra-fast inference on LPUs — Llama 4, Qwen3, DeepSeek distillations, and more",
    website: "https://groq.com",
    dashboardUrl: "https://console.groq.com/keys",
    pricingUrl: "https://groq.com/pricing",
    models: [
      {
        id: "llama-4-scout-17b-16e-instruct",
        name: "Llama 4 Scout 17B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.11, completionPer1M: 0.34 },
      },
      {
        id: "llama-4-maverick-17b-128e-instruct",
        name: "Llama 4 Maverick 17B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.2, completionPer1M: 0.6 },
      },
      {
        id: "meta-llama/llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.59, completionPer1M: 0.79 },
      },
      {
        id: "qwen-qwen3-32b",
        name: "Qwen3 32B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 0.19, completionPer1M: 0.28 },
      },
      {
        id: "deepseek-r1-distill-llama-70b",
        name: "DeepSeek R1 Distill 70B",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 0.75, completionPer1M: 0.99 },
      },
    ],
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "mistral-large-latest",
    defaultEnabled: false,
    category: "specialized",
    description:
      "European AI company — Mistral Large 3, Small 3.2, Codestral. Open-weight EU-hosted models.",
    website: "https://mistral.ai",
    dashboardUrl: "https://console.mistral.ai/api-keys/",
    docsUrl: "https://docs.mistral.ai",
    pricingUrl: "https://mistral.ai/pricing",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large 3",
        contextLength: 128000,
        maxOutputTokens: 32768,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 4, completionPer1M: 12 },
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small 3.2",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.2, completionPer1M: 0.6 },
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        contextLength: 256000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        recommendedFor: ["coding"],
        pricing: { promptPer1M: 0.3, completionPer1M: 0.9 },
      },
      {
        id: "mistral-saba",
        name: "Mistral Saba",
        contextLength: 32768,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.2, completionPer1M: 0.6 },
      },
    ],
  },
  xai: {
    id: "xai",
    name: "xAI (Grok)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "grok-4.1-fast",
    defaultEnabled: false,
    defaultBaseURL: "https://api.x.ai/v1",
    category: "flagship",
    description: "Grok 4.1 models from xAI — Grok 4.1, Grok 4.1 Fast, Grok 4, and Grok 3",
    website: "https://x.ai",
    dashboardUrl: "https://console.x.ai/team/api-keys",
    pricingUrl: "https://x.ai/pricing",
    models: [
      {
        id: "grok-4.1",
        name: "Grok 4.1",
        contextLength: 200000,
        maxOutputTokens: 32768,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 5, completionPer1M: 15 },
      },
      {
        id: "grok-4.1-fast",
        name: "Grok 4.1 Fast",
        contextLength: 200000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.5, completionPer1M: 1.5 },
      },
      {
        id: "grok-4",
        name: "Grok 4",
        contextLength: 200000,
        maxOutputTokens: 32768,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 3, completionPer1M: 10 },
      },
      {
        id: "grok-3",
        name: "Grok 3",
        contextLength: 131072,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 3, completionPer1M: 15 },
      },
    ],
  },
  togetherai: {
    id: "togetherai",
    name: "Together AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    defaultEnabled: false,
    defaultBaseURL: "https://api.together.xyz/v1",
    category: "aggregator",
    description: "Fast inference for 50+ open-source models — Llama 4, DeepSeek, Qwen, Mixtral",
    website: "https://together.ai",
    dashboardUrl: "https://api.together.xyz/settings/api-keys",
    docsUrl: "https://docs.together.ai",
    pricingUrl: "https://together.ai/pricing",
    models: [
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.27, completionPer1M: 0.85 },
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct-FP8",
        name: "Llama 4 Scout",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.18, completionPer1M: 0.59 },
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        contextLength: 128000,
        maxOutputTokens: 163840,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 0.8, completionPer1M: 2.4 },
      },
      {
        id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen3 Coder 480B",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        recommendedFor: ["coding"],
        pricing: { promptPer1M: 0.8, completionPer1M: 3.2 },
      },
    ],
  },
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    type: "cloud",
    protocol: "openai",
    family: "openrouter",
    adapter: "openrouter",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "anthropic/claude-sonnet-4",
    defaultEnabled: false,
    defaultBaseURL: "https://openrouter.ai/api/v1",
    category: "aggregator",
    description: "Unified API across many AI model providers",
    website: "https://openrouter.ai",
    dashboardUrl: "https://openrouter.ai/keys",
    docsUrl: "https://openrouter.ai/docs",
    pricingUrl: "https://openrouter.ai/models",
    supportsOAuth: true,
    oauthConfig: {
      authorizationUrl: "https://openrouter.ai/auth",
      tokenUrl: "https://openrouter.ai/api/v1/auth/keys",
      pkceRequired: true,
      callbackPath: "/api/oauth/openrouter/callback",
      scope: "openid profile",
    },
  },
  cohere: {
    id: "cohere",
    name: "Cohere",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "command-r-plus",
    defaultEnabled: false,
    defaultBaseURL: "https://api.cohere.com/compatibility/v1",
    category: "enterprise",
    description: "Enterprise AI — Command R+, Embed 4, and purpose-built RAG stack",
    website: "https://cohere.com",
    dashboardUrl: "https://dashboard.cohere.com/api-keys",
    docsUrl: "https://docs.cohere.com",
    pricingUrl: "https://cohere.com/pricing",
    models: [
      {
        id: "command-r-plus",
        name: "Command R+",
        contextLength: 128000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 2.5, completionPer1M: 10 },
      },
      {
        id: "command-r",
        name: "Command R",
        contextLength: 128000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.5, completionPer1M: 1.5 },
      },
      {
        id: "embed-v4.0",
        name: "Embed 4",
        contextLength: 512,
        maxOutputTokens: 0,
        supportsTools: false,
        supportsVision: false,
        supportsStreaming: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsEmbedding: true,
        pricing: { promptPer1M: 0.1, completionPer1M: 0 },
      },
    ],
  },
  fireworks: {
    id: "fireworks",
    name: "Fireworks AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api.fireworks.ai/inference/v1",
    category: "specialized",
    description: "Fast compound AI inference",
    website: "https://fireworks.ai",
    dashboardUrl: "https://fireworks.ai/account/api-keys",
    docsUrl: "https://docs.fireworks.ai",
  },
  cerebras: {
    id: "cerebras",
    name: "Cerebras",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "llama-3.3-70b",
    defaultEnabled: false,
    defaultBaseURL: "https://api.cerebras.ai/v1",
    category: "specialized",
    description: "Inference backed by custom AI chips",
    website: "https://cerebras.ai",
    dashboardUrl: "https://cloud.cerebras.ai/platform",
    docsUrl: "https://inference-docs.cerebras.ai",
  },
  sambanova: {
    id: "sambanova",
    name: "SambaNova",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "Meta-Llama-3.3-70B-Instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api.sambanova.ai/v1",
    category: "specialized",
    description: "Enterprise AI with custom hardware acceleration",
    website: "https://sambanova.ai",
    dashboardUrl: "https://cloud.sambanova.ai/apis",
    docsUrl: "https://docs.sambanova.ai",
  },
  siliconflow: {
    id: "siliconflow",
    name: "SiliconFlow (硅基流动)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "deepseek-ai/DeepSeek-V3.2",
    defaultEnabled: false,
    defaultBaseURL: "https://api.siliconflow.cn/v1",
    category: "aggregator",
    description: "High-performance inference with broad open-model coverage",
    website: "https://siliconflow.cn",
    dashboardUrl: "https://cloud.siliconflow.cn/account/ak",
    docsUrl: "https://docs.siliconflow.cn",
    quickAdd: {
      mode: "shortcut",
      category: "china",
      popular: true,
    },
    models: [
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        contextLength: 128000,
        maxOutputTokens: 163840,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
      },
      {
        id: "Pro/Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen3 Coder 480B",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        recommendedFor: ["coding"],
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
        name: "Qwen3 235B",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
      },
    ],
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.siliconflow.cn/v1"],
      nameIncludes: ["siliconflow", "硅基"],
    },
  },
  moonshot: {
    id: "moonshot",
    name: "Moonshot AI (月之暗面)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "moonshot-v1-8k",
    defaultEnabled: false,
    defaultBaseURL: "https://api.moonshot.cn/v1",
    category: "specialized",
    description: "Kimi family models with long-context options",
    website: "https://moonshot.cn",
    dashboardUrl: "https://platform.moonshot.cn/console/api-keys",
    docsUrl: "https://platform.moonshot.cn/docs",
    quickAdd: {
      mode: "shortcut",
      category: "china",
      popular: true,
    },
    models: createQuickAddModelEntries(["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.moonshot.cn/v1"],
      nameIncludes: ["moonshot", "kimi", "月之暗面"],
      modelPrefixes: ["moonshot-"],
    },
  },
  doubao: {
    id: "doubao",
    name: "Doubao (豆包)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "doubao-pro-32k",
    defaultEnabled: false,
    defaultBaseURL: "https://ark.cn-beijing.volces.com/api/v3",
    category: "specialized",
    description: "ByteDance Doubao and Ark models",
    website: "https://www.volcengine.com",
    dashboardUrl: "https://console.volcengine.com/ark",
    docsUrl: "https://www.volcengine.com/docs/82379",
    quickAdd: {
      mode: "shortcut",
      category: "china",
    },
    models: createQuickAddModelEntries(["doubao-pro-32k", "doubao-lite-32k", "doubao-pro-128k"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://ark.cn-beijing.volces.com/api/v3"],
      nameIncludes: ["doubao", "豆包", "ark"],
      modelPrefixes: ["doubao-"],
    },
  },
  baichuan: {
    id: "baichuan",
    name: "Baichuan AI (百川智能)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "Baichuan4",
    defaultEnabled: false,
    defaultBaseURL: "https://api.baichuan-ai.com/v1",
    category: "specialized",
    description: "Baichuan models optimized for Chinese scenarios",
    website: "https://www.baichuan-ai.com",
    dashboardUrl: "https://platform.baichuan-ai.com/console/apikey",
    docsUrl: "https://platform.baichuan-ai.com/docs/api",
    quickAdd: {
      mode: "shortcut",
      category: "china",
    },
    models: createQuickAddModelEntries(["Baichuan4", "Baichuan3-Turbo", "Baichuan3-Turbo-128k"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.baichuan-ai.com/v1"],
      nameIncludes: ["baichuan", "百川"],
      modelPrefixes: ["baichuan"],
    },
  },
  lingyi: {
    id: "lingyi",
    name: "01.AI (零一万物)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "yi-large",
    defaultEnabled: false,
    defaultBaseURL: "https://api.lingyiwanwu.com/v1",
    category: "specialized",
    description: "Yi family models from 01.AI",
    website: "https://www.lingyiwanwu.com",
    dashboardUrl: "https://platform.lingyiwanwu.com/apikeys",
    docsUrl: "https://platform.lingyiwanwu.com/docs",
    quickAdd: {
      mode: "shortcut",
      category: "china",
    },
    models: createQuickAddModelEntries(["yi-large", "yi-medium", "yi-spark"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.lingyiwanwu.com/v1"],
      nameIncludes: ["01.ai", "lingyi", "零一万物", "yi"],
      modelPrefixes: ["yi-"],
    },
  },
  stepfun: {
    id: "stepfun",
    name: "StepFun (阶跃星辰)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "step-1-8k",
    defaultEnabled: false,
    defaultBaseURL: "https://api.stepfun.com/v1",
    category: "specialized",
    description: "Step family models with multimodal support",
    website: "https://www.stepfun.com",
    dashboardUrl: "https://platform.stepfun.com/interface-key",
    docsUrl: "https://platform.stepfun.com/docs",
    quickAdd: {
      mode: "shortcut",
      category: "china",
    },
    models: createQuickAddModelEntries(["step-1-8k", "step-1-32k", "step-1v-8k"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.stepfun.com/v1"],
      nameIncludes: ["stepfun", "step", "阶跃"],
      modelPrefixes: ["step-"],
    },
  },
  perplexity: {
    id: "perplexity",
    name: "Perplexity AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "sonar-pro",
    defaultEnabled: false,
    defaultBaseURL: "https://api.perplexity.ai",
    category: "aggregator",
    description: "Search-augmented AI — Sonar models with real-time web grounding",
    website: "https://www.perplexity.ai",
    dashboardUrl: "https://www.perplexity.ai/settings/api",
    docsUrl: "https://docs.perplexity.ai",
    quickAdd: {
      mode: "shortcut",
      category: "global",
      popular: true,
    },
    models: [
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        contextLength: 200000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 3, completionPer1M: 15 },
      },
      {
        id: "sonar",
        name: "Sonar",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 1, completionPer1M: 1 },
      },
      {
        id: "sonar-reasoning",
        name: "Sonar Reasoning",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 5, completionPer1M: 20 },
      },
    ],
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.perplexity.ai"],
      nameIncludes: ["perplexity", "sonar"],
    },
  },
  deepinfra: {
    id: "deepinfra",
    name: "DeepInfra",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api.deepinfra.com/v1/openai",
    category: "aggregator",
    description: "Fast serverless inference across open-source models",
    website: "https://deepinfra.com",
    dashboardUrl: "https://deepinfra.com/dash/api_keys",
    docsUrl: "https://deepinfra.com/docs",
    quickAdd: {
      mode: "shortcut",
      category: "global",
      popular: true,
    },
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.35, completionPer1M: 0.4 },
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen 2.5 72B",
        contextLength: 32768,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.35, completionPer1M: 0.4 },
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 0.7, completionPer1M: 2.0 },
      },
      {
        id: "mistralai/Mistral-Small-24B-Instruct-2501",
        name: "Mistral Small 24B",
        contextLength: 32768,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.1, completionPer1M: 0.3 },
      },
    ],
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.deepinfra.com/v1/openai"],
      nameIncludes: ["deepinfra"],
    },
  },
  novita: {
    id: "novita",
    name: "Novita AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "meta-llama/llama-3.1-70b-instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api.novita.ai/v3/openai",
    category: "aggregator",
    description: "Affordable GPU cloud inference",
    website: "https://novita.ai",
    dashboardUrl: "https://novita.ai/settings",
    docsUrl: "https://novita.ai/docs",
    quickAdd: {
      mode: "shortcut",
      category: "global",
    },
    models: createQuickAddModelEntries([
      "meta-llama/llama-3.1-70b-instruct",
      "meta-llama/llama-3.1-8b-instruct",
    ]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.novita.ai/v3/openai"],
      nameIncludes: ["novita"],
    },
  },
  lepton: {
    id: "lepton",
    name: "Lepton AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "llama3-70b",
    defaultEnabled: false,
    defaultBaseURL: "https://llama3-70b.lepton.run/api/v1",
    category: "aggregator",
    description: "Photon-powered hosted inference endpoints",
    website: "https://www.lepton.ai",
    dashboardUrl: "https://dashboard.lepton.ai/workspace",
    docsUrl: "https://www.lepton.ai/docs",
    quickAdd: {
      mode: "shortcut",
      category: "global",
    },
    models: createQuickAddModelEntries(["llama3-70b", "llama3-8b", "mixtral-8x7b"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://llama3-70b.lepton.run/api/v1"],
      nameIncludes: ["lepton"],
    },
  },
  aiproxy: {
    id: "aiproxy",
    name: "AI Proxy",
    type: "cloud",
    protocol: "openai",
    family: "proxy-openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "gpt-4o",
    defaultEnabled: false,
    defaultBaseURL: "https://api.aiproxy.io/v1",
    category: "aggregator",
    description: "Proxy API for restricted regions and relayed upstream models",
    website: "https://aiproxy.io",
    docsUrl: "https://aiproxy.io/docs",
    quickAdd: {
      mode: "shortcut",
      category: "proxy",
    },
    models: createQuickAddModelEntries(["gpt-4o", "gpt-4o-mini", "claude-3-5-sonnet-20241022"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.aiproxy.io/v1"],
      nameIncludes: ["aiproxy", "proxy"],
    },
  },
  ohmygpt: {
    id: "ohmygpt",
    name: "OhMyGPT",
    type: "cloud",
    protocol: "openai",
    family: "proxy-openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "gpt-4o",
    defaultEnabled: false,
    defaultBaseURL: "https://api.ohmygpt.com/v1",
    category: "aggregator",
    description: "OpenAI API relay service",
    website: "https://www.ohmygpt.com",
    docsUrl: "https://www.ohmygpt.com",
    quickAdd: {
      mode: "shortcut",
      category: "proxy",
    },
    models: createQuickAddModelEntries(["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"]),
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.ohmygpt.com/v1"],
      nameIncludes: ["ohmygpt"],
    },
  },
  zhipu: {
    id: "zhipu",
    name: "Zhipu AI (智谱清言)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "glm-4.7-flash",
    defaultEnabled: false,
    defaultBaseURL: "https://open.bigmodel.cn/api/paas/v4",
    category: "specialized",
    description: "GLM models with strong Chinese and coding-oriented options",
    website: "https://open.bigmodel.cn",
    dashboardUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    docsUrl: "https://open.bigmodel.cn/dev/howuse/introduction",
    quickAdd: {
      mode: "promoted",
      category: "china",
    },
    models: [
      // Free models
      {
        id: "glm-4.7-flash",
        name: "GLM-4.7 Flash",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0, completionPer1M: 0 },
      },
      {
        id: "glm-4-flash-250414",
        name: "GLM-4 Flash (250414)",
        contextLength: 128000,
        maxOutputTokens: 16000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0, completionPer1M: 0 },
      },
      // Paid models
      {
        id: "glm-5",
        name: "GLM-5",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-5-turbo",
        name: "GLM-5 Turbo",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        recommendedFor: ["coding"],
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4.7-flashx",
        name: "GLM-4.7 FlashX",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4.6",
        name: "GLM-4.6",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        recommendedFor: ["coding"],
      },
      {
        id: "glm-4.5-air",
        name: "GLM-4.5 Air",
        contextLength: 128000,
        maxOutputTokens: 96000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4.5-airx",
        name: "GLM-4.5 AirX",
        contextLength: 128000,
        maxOutputTokens: 96000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4-long",
        name: "GLM-4 Long",
        contextLength: 1000000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4-flashx-250414",
        name: "GLM-4 FlashX (250414)",
        contextLength: 128000,
        maxOutputTokens: 16000,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      // Vision models
      {
        id: "glm-5v-turbo",
        name: "GLM-5V Turbo",
        contextLength: 200000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4.6v",
        name: "GLM-4.6V",
        contextLength: 128000,
        maxOutputTokens: 32000,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
      {
        id: "glm-4.6v-flash",
        name: "GLM-4.6V Flash",
        contextLength: 128000,
        maxOutputTokens: 32000,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0, completionPer1M: 0 },
      },
    ],
    codingPackage: {
      id: "coding",
      label: "Coding",
      defaultModel: "glm-5-turbo",
      modelIds: ["glm-5-turbo", "glm-4.7", "glm-4.6"],
      mcpBundles: [
        {
          id: "glm-vision",
          name: "GLM Vision MCP",
          description: "Local visual understanding MCP for screenshots, OCR, and media analysis.",
          transport: "stdio",
          command: "npx",
          args: ["-y", "@z_ai/mcp-server@latest"],
          envKeys: ["Z_AI_API_KEY", "Z_AI_MODE"],
          envDefaults: {
            Z_AI_MODE: "ZHIPU",
          },
          credentialBinding: {
            type: "env",
            key: "Z_AI_API_KEY",
          },
          docsUrl: "https://docs.bigmodel.cn/cn/coding-plan/mcp/vision-mcp-server",
        },
        {
          id: "glm-search",
          name: "GLM Search MCP",
          description: "Remote MCP for live web search within the GLM coding plan.",
          transport: "streamableHttp",
          url: "https://open.bigmodel.cn/api/mcp/web_search_prime/mcp",
          credentialBinding: {
            type: "header",
            key: "Authorization",
            prefix: "Bearer ",
          },
          fallbackToSse: true,
          docsUrl: "https://docs.bigmodel.cn/cn/coding-plan/mcp/search-mcp-server",
        },
        {
          id: "glm-reader",
          name: "GLM Reader MCP",
          description: "Remote MCP for structured webpage reading within the GLM coding plan.",
          transport: "streamableHttp",
          url: "https://open.bigmodel.cn/api/mcp/web_reader/mcp",
          credentialBinding: {
            type: "header",
            key: "Authorization",
            prefix: "Bearer ",
          },
          fallbackToSse: true,
          docsUrl: "https://docs.bigmodel.cn/cn/coding-plan/mcp/reader-mcp-server",
        },
        {
          id: "glm-zread",
          name: "GLM ZRead MCP",
          description:
            "Remote MCP for GitHub repository reading and structure lookup within the GLM coding plan.",
          transport: "streamableHttp",
          url: "https://open.bigmodel.cn/api/mcp/zread/mcp",
          credentialBinding: {
            type: "header",
            key: "Authorization",
            prefix: "Bearer ",
          },
          fallbackToSse: true,
          docsUrl: "https://docs.bigmodel.cn/cn/coding-plan/mcp/zread-mcp-server",
        },
      ],
    },
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://open.bigmodel.cn/api/paas/v4"],
      nameIncludes: ["zhipu", "glm", "bigmodel", "智谱"],
      modelPrefixes: ["glm-"],
    },
  },
  minimax: {
    id: "minimax",
    name: "MiniMax",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "MiniMax-M2.7",
    defaultEnabled: false,
    defaultBaseURL: "https://api.minimaxi.com/v1",
    category: "specialized",
    description:
      "MiniMax M2 series multimodal models. Supports both pay-as-you-go and Token Plan subscription keys.",
    website: "https://www.minimaxi.com",
    dashboardUrl: "https://platform.minimaxi.com",
    docsUrl: "https://platform.minimaxi.com/docs/api-reference/api-overview",
    pricingUrl: "https://platform.minimaxi.com/docs/pricing",
    quickAdd: {
      mode: "promoted",
      category: "china",
    },
    models: [
      {
        id: "MiniMax-M2.7",
        name: "MiniMax M2.7",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.3, completionPer1M: 1.2 },
      },
      {
        id: "MiniMax-M2.7-highspeed",
        name: "MiniMax M2.7 Highspeed",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.3, completionPer1M: 1.2 },
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.15, completionPer1M: 1.2 },
      },
      {
        id: "MiniMax-M2.5-highspeed",
        name: "MiniMax M2.5 Highspeed",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.3, completionPer1M: 2.4 },
      },
      {
        id: "MiniMax-M2.1",
        name: "MiniMax M2.1",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.27, completionPer1M: 0.95 },
        recommendedFor: ["coding"],
      },
      {
        id: "MiniMax-M2.1-highspeed",
        name: "MiniMax M2.1 Highspeed",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.27, completionPer1M: 0.95 },
        recommendedFor: ["coding"],
      },
      {
        id: "MiniMax-M2",
        name: "MiniMax M2",
        contextLength: 204800,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.255, completionPer1M: 1.0 },
        recommendedFor: ["coding"],
      },
    ],
    codingPackage: {
      id: "coding",
      label: "Coding",
      defaultModel: "MiniMax-M2.7",
      modelIds: ["MiniMax-M2.7", "MiniMax-M2.5", "MiniMax-M2.1", "MiniMax-M2"],
      mcpBundles: [
        {
          id: "minimax-coding-plan",
          name: "MiniMax Token Plan MCP",
          description:
            "Local MCP for MiniMax web search and image understanding tools (Token Plan).",
          transport: "stdio",
          command: "uvx",
          args: ["minimax-coding-plan-mcp", "-y"],
          envKeys: ["MINIMAX_API_KEY", "MINIMAX_API_HOST"],
          envDefaults: {
            MINIMAX_API_HOST: "https://api.minimaxi.com",
          },
          credentialBinding: {
            type: "env",
            key: "MINIMAX_API_KEY",
          },
          docsUrl: "https://platform.minimaxi.com/docs/guides/token-plan-mcp-guide",
        },
      ],
    },
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api.minimaxi.com/v1", "https://api.minimax.chat/v1"],
      nameIncludes: ["minimax", "abab"],
      modelPrefixes: ["MiniMax-", "minimax-", "abab"],
    },
  },
  ollama: {
    id: "ollama",
    name: "Ollama",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "llama3.2",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:11434/v1",
    defaultSettingsBaseURL: "http://localhost:11434",
    placeholderApiKey: "ollama",
    category: "local",
    description: "Run open-source models locally",
    website: "https://ollama.ai",
    docsUrl: "https://github.com/ollama/ollama",
  },
  lmstudio: {
    id: "lmstudio",
    name: "LM Studio",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:1234/v1",
    defaultSettingsBaseURL: "http://localhost:1234",
    placeholderApiKey: "lm-studio",
    category: "local",
    description: "Desktop app for running local LLMs",
    website: "https://lmstudio.ai",
    docsUrl: "https://lmstudio.ai/docs",
  },
  llamacpp: {
    id: "llamacpp",
    name: "llama.cpp",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:8080/v1",
    defaultSettingsBaseURL: "http://localhost:8080",
    placeholderApiKey: "llama-cpp",
    category: "local",
    description: "High-performance C++ inference server",
    website: "https://github.com/ggerganov/llama.cpp",
  },
  llamafile: {
    id: "llamafile",
    name: "Llamafile",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:8080/v1",
    defaultSettingsBaseURL: "http://localhost:8080",
    placeholderApiKey: "llamafile",
    category: "local",
    description: "Single-file executable local LLM server",
    website: "https://github.com/Mozilla-Ocho/llamafile",
  },
  vllm: {
    id: "vllm",
    name: "vLLM",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:8000/v1",
    defaultSettingsBaseURL: "http://localhost:8000",
    placeholderApiKey: "vllm",
    category: "local",
    description: "High-throughput GPU inference engine",
    website: "https://docs.vllm.ai",
  },
  localai: {
    id: "localai",
    name: "LocalAI",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:8080/v1",
    defaultSettingsBaseURL: "http://localhost:8080",
    placeholderApiKey: "localai",
    category: "local",
    description: "Self-hosted OpenAI alternative",
    website: "https://localai.io",
    docsUrl: "https://localai.io/docs",
  },
  jan: {
    id: "jan",
    name: "Jan",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:1337/v1",
    defaultSettingsBaseURL: "http://localhost:1337",
    placeholderApiKey: "jan",
    category: "local",
    description: "Open-source ChatGPT alternative",
    website: "https://jan.ai",
    docsUrl: "https://jan.ai/docs",
  },
  textgenwebui: {
    id: "textgenwebui",
    name: "Text Generation WebUI",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:5000/v1",
    defaultSettingsBaseURL: "http://localhost:5000",
    placeholderApiKey: "textgen",
    category: "local",
    description: "Gradio UI with OpenAI-compatible API",
    website: "https://github.com/oobabooga/text-generation-webui",
  },
  koboldcpp: {
    id: "koboldcpp",
    name: "KoboldCpp",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:5001/v1",
    defaultSettingsBaseURL: "http://localhost:5001",
    placeholderApiKey: "koboldcpp",
    category: "local",
    description: "Easy-to-use llama.cpp fork",
    website: "https://github.com/LostRuins/koboldcpp",
  },
  tabbyapi: {
    id: "tabbyapi",
    name: "TabbyAPI",
    type: "local",
    protocol: "openai",
    family: "local-openai-compatible",
    adapter: "local-openai-compatible",
    apiKeyRequired: false,
    baseURLRequired: true,
    defaultModel: "local-model",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:5000/v1",
    defaultSettingsBaseURL: "http://localhost:5000",
    placeholderApiKey: "tabbyapi",
    category: "local",
    description: "Exllamav2 API server",
    website: "https://github.com/theroyallab/tabbyAPI",
  },
  cliproxyapi: {
    id: "cliproxyapi",
    name: "CLIProxyAPI",
    type: "local",
    protocol: "openai",
    family: "proxy-openai-compatible",
    adapter: "cliproxyapi",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "gemini-2.5-flash",
    defaultEnabled: false,
    defaultBaseURL: "http://localhost:8317/v1",
    defaultSettingsBaseURL: "http://localhost:8317",
    category: "aggregator",
    description: "Self-hosted AI proxy aggregating multiple providers",
    website: "https://help.router-for.me",
    dashboardUrl: "http://localhost:8317/management.html",
    docsUrl: "https://help.router-for.me/introduction/quick-start.html",
  },
  yi: {
    id: "yi",
    name: "Yi (Lingyiwanwu)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "yi-lightning",
    defaultBaseURL: "https://api.lingyiwanwu.com/v1",
    defaultEnabled: false,
    category: "specialized",
    description: "Yi series models from 01.AI (零一万物)",
    website: "https://www.lingyiwanwu.com",
    dashboardUrl: "https://platform.lingyiwanwu.com/apikeys",
    docsUrl: "https://platform.lingyiwanwu.com/docs",
    quickAdd: { mode: "shortcut", category: "china" },
    models: [
      {
        id: "yi-lightning",
        name: "Yi Lightning",
        contextLength: 16384,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.99, completionPer1M: 0.99 },
      },
      {
        id: "yi-large",
        name: "Yi Large",
        contextLength: 32768,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 3.0, completionPer1M: 3.0 },
      },
      {
        id: "yi-medium",
        name: "Yi Medium",
        contextLength: 16384,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.5, completionPer1M: 0.5 },
      },
    ],
  },
  qwen: {
    id: "qwen",
    name: "Qwen (Tongyi)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "qwen-max",
    defaultBaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultEnabled: false,
    category: "specialized",
    description: "Qwen series models from Alibaba Cloud (阿里云通义千问)",
    website: "https://tongyi.aliyun.com",
    dashboardUrl: "https://dashscope.console.aliyun.com/apiKey",
    docsUrl: "https://help.aliyun.com/zh/model-studio/developer-reference/use-qwen-by-calling-api",
    quickAdd: { mode: "shortcut", category: "china", popular: true },
    models: [
      {
        id: "qwen-max",
        name: "Qwen Max",
        contextLength: 32768,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 2.4, completionPer1M: 9.6 },
      },
      {
        id: "qwen-plus",
        name: "Qwen Plus",
        contextLength: 131072,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.8, completionPer1M: 2.0 },
      },
      {
        id: "qwen-turbo",
        name: "Qwen Turbo",
        contextLength: 131072,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.3, completionPer1M: 0.6 },
      },
      {
        id: "qwen-long",
        name: "Qwen Long",
        contextLength: 1000000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.5, completionPer1M: 2.0 },
      },
    ],
  },
  volcengine: {
    id: "volcengine",
    name: "Volcengine Doubao",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "doubao-pro-256k",
    defaultBaseURL: "https://ark.cn-beijing.volces.com/api/v3",
    defaultEnabled: false,
    category: "specialized",
    description: "Doubao models from ByteDance Volcengine (字节跳动火山引擎豆包)",
    website: "https://www.volcengine.com/product/doubao",
    dashboardUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    docsUrl: "https://www.volcengine.com/docs/82379/1263482",
    quickAdd: { mode: "shortcut", category: "china", popular: true },
    models: [
      {
        id: "doubao-pro-256k",
        name: "Doubao Pro 256K",
        contextLength: 256000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.8, completionPer1M: 2.0 },
      },
      {
        id: "doubao-lite-128k",
        name: "Doubao Lite 128K",
        contextLength: 128000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.3, completionPer1M: 0.6 },
      },
      {
        id: "doubao-vision-pro-32k",
        name: "Doubao Vision Pro",
        contextLength: 32768,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 2.0, completionPer1M: 4.0 },
      },
    ],
  },
  internlm: {
    id: "internlm",
    name: "InternLM (书生浦语)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "internlm2.5-latest",
    defaultBaseURL: "https://internlm-chat.intern-ai.org.cn/puyu/api/v1",
    defaultEnabled: false,
    category: "specialized",
    description: "InternLM models from Shanghai AI Lab (上海人工智能实验室)",
    website: "https://internlm.intern-ai.org.cn",
    docsUrl: "https://internlm.intern-ai.org.cn/api/document",
    quickAdd: { mode: "shortcut", category: "china" },
    models: [
      {
        id: "internlm2.5-latest",
        name: "InternLM 2.5",
        contextLength: 32768,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
      },
    ],
  },
  glm4: {
    id: "glm4",
    name: "GLM-4 (智谱清言)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "glm-4-plus",
    defaultBaseURL: "https://open.bigmodel.cn/api/paas/v4",
    defaultEnabled: false,
    category: "specialized",
    description: "GLM-4 series - next-gen models from Zhipu AI (智谱)",
    website: "https://open.bigmodel.cn",
    dashboardUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    docsUrl: "https://open.bigmodel.cn/dev/api/normal-model/glm-4",
    quickAdd: { mode: "shortcut", category: "china" },
    models: [
      {
        id: "glm-4-plus",
        name: "GLM-4 Plus",
        contextLength: 128000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 7.14, completionPer1M: 7.14 },
      },
      {
        id: "glm-4-long",
        name: "GLM-4 Long",
        contextLength: 1000000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 1.43, completionPer1M: 1.43 },
      },
      {
        id: "glm-4-flash",
        name: "GLM-4 Flash",
        contextLength: 128000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.14, completionPer1M: 0.14 },
      },
      {
        id: "glm-4-flashx",
        name: "GLM-4 FlashX",
        contextLength: 128000,
        maxOutputTokens: 4096,
        supportsTools: true,
        supportsVision: false,
        supportsAudio: false,
        supportsVideo: false,
        supportsStreaming: true,
        pricing: { promptPer1M: 0.14, completionPer1M: 0.14 },
      },
    ],
  },

  // === NEW: Enterprise Platforms ===

  bedrock: {
    id: "bedrock",
    name: "Amazon Bedrock",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "us.amazon.nova-pro-v1:0",
    defaultEnabled: false,
    category: "enterprise",
    description:
      "AWS managed service for foundation models — Anthropic, Meta, Mistral, Amazon Nova, DeepSeek, and more. Uses AWS SigV4 auth; not a standard Bearer token API.",
    website: "https://aws.amazon.com/bedrock",
    dashboardUrl: "https://console.aws.amazon.com/bedrock",
    docsUrl: "https://docs.aws.amazon.com/bedrock",
    pricingUrl: "https://aws.amazon.com/bedrock/pricing/",
    models: [
      {
        id: "us.amazon.nova-pro-v1:0",
        name: "Nova Pro",
        contextLength: 300000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.8, completionPer1M: 3.2 },
      },
      {
        id: "us.amazon.nova-lite-v1:0",
        name: "Nova Lite",
        contextLength: 300000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.06, completionPer1M: 0.24 },
      },
      {
        id: "us.amazon.nova-micro-v1:0",
        name: "Nova Micro",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.035, completionPer1M: 0.14 },
      },
      {
        id: "us.amazon.nova-premier-v1:0",
        name: "Nova Premier",
        contextLength: 1000000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 2, completionPer1M: 8 },
      },
    ],
  },

  azure: {
    id: "azure",
    name: "Azure OpenAI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "gpt-5",
    defaultEnabled: false,
    category: "enterprise",
    description:
      "Microsoft Azure OpenAI Service — GPT, Codex, and embedding models with enterprise compliance. Base URL is per-resource: https://{name}.openai.azure.com/openai/v1",
    website: "https://azure.microsoft.com/en-us/products/ai-services/openai-service",
    dashboardUrl: "https://ai.azure.com",
    docsUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai",
    pricingUrl:
      "https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service",
    models: [
      {
        id: "gpt-5",
        name: "GPT-5",
        contextLength: 400000,
        maxOutputTokens: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
        pricing: { promptPer1M: 1.25, completionPer1M: 10 },
      },
      {
        id: "gpt-5-mini",
        name: "GPT-5 Mini",
        contextLength: 400000,
        maxOutputTokens: 32768,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.25, completionPer1M: 2 },
      },
      {
        id: "gpt-5-nano",
        name: "GPT-5 Nano",
        contextLength: 400000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.05, completionPer1M: 0.4 },
      },
    ],
  },

  // === NEW: Inference Platforms ===

  nvidia: {
    id: "nvidia",
    name: "NVIDIA NIM",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "nvidia/nemotron-3-super-120b-a12b",
    defaultEnabled: false,
    defaultBaseURL: "https://integrate.api.nvidia.com/v1",
    category: "specialized",
    description:
      "NVIDIA Inference Microservices — optimized open-source and Nemotron models. Free tier with 1,000 credits.",
    website: "https://build.nvidia.com",
    dashboardUrl: "https://build.nvidia.com/explore/discover",
    docsUrl: "https://docs.api.nvidia.com/nim",
    pricingUrl: "https://build.nvidia.com/pricing",
    models: [
      {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "Nemotron 3 Super 120B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.1, completionPer1M: 0.5 },
      },
      {
        id: "nvidia/nemotron-nano-9b-v2",
        name: "Nemotron Nano 9B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.04, completionPer1M: 0.16 },
      },
      {
        id: "nvidia/llama-3.1-70b-instruct",
        name: "Llama 3.1 70B",
        contextLength: 128000,
        maxOutputTokens: 8192,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        pricing: { promptPer1M: 0.35, completionPer1M: 0.4 },
      },
    ],
  },

  huggingface: {
    id: "huggingface",
    name: "Hugging Face",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "Qwen/Qwen2.5-72B-Instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api-inference.huggingface.co/v1",
    category: "aggregator",
    description:
      "Hugging Face Inference Providers — 200+ open-source models with zero markup pricing.",
    website: "https://huggingface.co",
    dashboardUrl: "https://huggingface.co/settings/tokens",
    docsUrl: "https://huggingface.co/docs/inference-providers",
    pricingUrl: "https://huggingface.co/docs/inference-providers/en/pricing",
    models: [
      {
        id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen3 Coder 480B",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        recommendedFor: ["coding"],
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        contextLength: 128000,
        maxOutputTokens: 16384,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        contextLength: 128000,
        maxOutputTokens: 163840,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        supportsAudio: false,
        supportsVideo: false,
        supportsReasoning: true,
      },
    ],
  },

  replicate: {
    id: "replicate",
    name: "Replicate",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "meta/meta-llama-3-70b-instruct",
    defaultEnabled: false,
    defaultBaseURL: "https://api.replicate.com/v1",
    category: "aggregator",
    description:
      "Run open-source ML models in the cloud. Pay-per-second GPU billing. Uses non-standard prediction API, not fully OpenAI-compatible for chat.",
    website: "https://replicate.com",
    dashboardUrl: "https://replicate.com/account/api-tokens",
    docsUrl: "https://replicate.com/docs",
    pricingUrl: "https://replicate.com/pricing",
  },

  cloudflare: {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "@cf/meta/llama-3.1-70b-instruct-fp8-fast",
    defaultEnabled: false,
    category: "specialized",
    description:
      "Serverless AI inference on Cloudflare global edge network. 10,000 Neurons/day free. Base URL requires account ID.",
    website: "https://developers.cloudflare.com/workers-ai",
    dashboardUrl: "https://dash.cloudflare.com",
    docsUrl: "https://developers.cloudflare.com/workers-ai",
    pricingUrl: "https://developers.cloudflare.com/workers-ai/platform/pricing",
  },

  // === NEW: Developer Platforms ===

  github: {
    id: "github",
    name: "GitHub Models",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "gpt-4o",
    defaultEnabled: false,
    defaultBaseURL: "https://models.inference.ai.azure.com",
    category: "aggregator",
    description:
      "GitHub Models marketplace — free rate-limited access to GPT, Claude, Llama, DeepSeek, and more.",
    website: "https://github.com/marketplace?type=models",
    dashboardUrl: "https://github.com/settings/tokens",
    docsUrl: "https://docs.github.com/en/github-models",
  },

  ai21: {
    id: "ai21",
    name: "AI21 Labs",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "jamba-1.5-large",
    defaultEnabled: false,
    defaultBaseURL: "https://api.ai21.com/studio/v1",
    category: "specialized",
    description: "Jamba family models with 256K context windows. $10 free credits for new users.",
    website: "https://www.ai21.com",
    dashboardUrl: "https://studio.ai21.com",
    docsUrl: "https://docs.ai21.com",
    pricingUrl: "https://ai21.com/pricing",
  },

  // === NEW: Chinese Providers ===

  baidu: {
    id: "baidu",
    name: "Baidu ERNIE (百度文心)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "ernie-4.5-21b-a3b",
    defaultEnabled: false,
    defaultBaseURL: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat",
    category: "specialized",
    description:
      "Baidu ERNIE Bot models. Non-standard auth (API Key + Secret Key → OAuth token). For OpenAI-compatible access, use a proxy or gateway.",
    website: "https://ernie.baidu.com",
    dashboardUrl: "https://console.bce.baidu.com/qianfan",
    docsUrl: "https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html",
    quickAdd: { mode: "shortcut", category: "china" },
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat"],
      nameIncludes: ["baidu", "ernie", "wenxin", "百度", "文心"],
    },
  },

  tencent: {
    id: "tencent",
    name: "Tencent Hunyuan (腾讯混元)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: true,
    defaultModel: "hunyuan-a13b",
    defaultEnabled: false,
    defaultBaseURL: "https://hunyuan.tencentcloudapi.com",
    category: "specialized",
    description:
      "Tencent Hunyuan models. Uses Tencent Cloud auth (SecretId + SecretKey). For OpenAI-compatible access, use a proxy or gateway.",
    website: "https://cloud.tencent.com/product/hunyuan",
    dashboardUrl: "https://console.cloud.tencent.com/hunyuan",
    docsUrl: "https://cloud.tencent.com/document/product/1729",
    quickAdd: { mode: "shortcut", category: "china" },
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://hunyuan.tencentcloudapi.com"],
      nameIncludes: ["tencent", "hunyuan", "腾讯", "混元"],
    },
  },

  modelscope: {
    id: "modelscope",
    name: "ModelScope (魔搭)",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    defaultEnabled: false,
    defaultBaseURL: "https://api-inference.modelscope.cn/v1",
    category: "aggregator",
    description:
      "Alibaba ModelScope inference API — free access to Qwen, GLM, MiniMax, and other open-source models.",
    website: "https://modelscope.cn",
    dashboardUrl: "https://modelscope.cn/my/overview",
    docsUrl: "https://modelscope.cn/docs/api",
    quickAdd: { mode: "shortcut", category: "china", popular: true },
    compatibility: {
      protocol: "openai",
      baseURLs: ["https://api-inference.modelscope.cn/v1"],
      nameIncludes: ["modelscope", "魔搭"],
    },
  },

  // === NEW: Specialized ===

  voyage: {
    id: "voyage",
    name: "Voyage AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "voyage-4-large",
    defaultEnabled: false,
    defaultBaseURL: "https://api.voyageai.com/v1",
    category: "specialized",
    description:
      "Best-in-class embedding and reranker models for search and RAG. Not a chat completion API.",
    website: "https://www.voyageai.com",
    dashboardUrl: "https://www.voyageai.com/dashboard",
    docsUrl: "https://docs.voyageai.com",
    pricingUrl: "https://docs.voyageai.com/docs/pricing",
  },

  jina: {
    id: "jina",
    name: "Jina AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "jina-embeddings-v5-text-small",
    defaultEnabled: false,
    defaultBaseURL: "https://api.jina.ai/v1",
    category: "specialized",
    description:
      "Multilingual embeddings and reranker models for enterprise search. Not a chat completion API.",
    website: "https://jina.ai",
    dashboardUrl: "https://cloud.jina.ai",
    docsUrl: "https://docs.jina.ai",
    pricingUrl: "https://cloud.jina.ai/pricing",
  },

  fal: {
    id: "fal",
    name: "Fal AI",
    type: "cloud",
    protocol: "openai",
    family: "openai-compatible",
    adapter: "openai-compatible",
    apiKeyRequired: true,
    baseURLRequired: false,
    defaultModel: "fal-ai/flux/dev",
    defaultEnabled: false,
    defaultBaseURL: "https://rest.alpha.fal.ai",
    category: "specialized",
    description:
      "High-performance AI inference for media generation — image, video, audio. Not a chat completion API.",
    website: "https://fal.ai",
    dashboardUrl: "https://fal.ai/dashboard",
    docsUrl: "https://fal.ai/docs",
    pricingUrl: "https://fal.ai/pricing",
  },
}

export function getBuiltInProviderCatalog(): BuiltInProviderCatalogEntry[] {
  return BUILT_IN_PROVIDER_IDS.map((providerId) => CATALOG_ENTRIES[providerId])
}

export function getQuickAddProviderCatalogEntries(): BuiltInProviderCatalogEntry[] {
  return getBuiltInProviderCatalog().filter((entry) => entry.quickAdd?.mode === "shortcut")
}

export function buildQuickAddProviderPresets(): BuiltInProviderQuickAddPreset[] {
  return getQuickAddProviderCatalogEntries()
    .filter((entry) => Boolean(entry.defaultBaseURL))
    .map((entry) => ({
      id: entry.id,
      name: entry.name,
      description: entry.description || entry.name,
      baseURL: entry.defaultBaseURL as string,
      apiProtocol: entry.protocol,
      models: entry.models?.map((model) => model.id) || [entry.defaultModel],
      modelEntries: entry.models || createQuickAddModelEntries([entry.defaultModel]),
      defaultModel: entry.defaultModel,
      docsUrl: entry.docsUrl,
      dashboardUrl: entry.dashboardUrl,
      category: entry.quickAdd?.category || "global",
      popular: entry.quickAdd?.popular,
    }))
}

export function getBuiltInProviderCatalogEntry(
  providerId: string
): BuiltInProviderCatalogEntry | undefined {
  return isBuiltInProviderId(providerId) ? CATALOG_ENTRIES[providerId] : undefined
}

export function getBuiltInProviderDefaultModel(providerId: string): string | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.defaultModel
}

export function getBuiltInProviderDefaultBaseURL(providerId: string): string | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.defaultBaseURL
}

export function getBuiltInProviderSettingsBaseURL(providerId: string): string | undefined {
  const entry = getBuiltInProviderCatalogEntry(providerId)
  return entry?.defaultSettingsBaseURL || entry?.defaultBaseURL
}

export function getBuiltInProviderProtocol(
  providerId: string
): BuiltInProviderProtocol | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.protocol
}

export function getBuiltInProviderFamily(providerId: string): BuiltInProviderFamily | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.family
}

export function getBuiltInProviderAdapter(
  providerId: string
): BuiltInProviderAdapterId | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.adapter
}

export function getBuiltInProviderCodingPackage(
  providerId: string
): BuiltInProviderCodingPackage | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.codingPackage
}

export function getBuiltInProviderCodingPackageBundle(
  providerId: string,
  bundleId: string
): BuiltInProviderCodingPackageMcpBundle | undefined {
  return getBuiltInProviderCodingPackage(providerId)?.mcpBundles?.find(
    (bundle) => bundle.id === bundleId
  )
}

export function getBuiltInProviderPlaceholderApiKey(providerId: string): string | undefined {
  return getBuiltInProviderCatalogEntry(providerId)?.placeholderApiKey
}

export function buildDefaultBuiltInProviderSettings(): Record<
  BuiltInProviderId,
  {
    providerId: BuiltInProviderId
    apiKey?: string
    baseURL?: string
    defaultModel: string
    enabled: boolean
  }
> {
  return Object.fromEntries(
    BUILT_IN_PROVIDER_IDS.map((providerId) => {
      const entry = CATALOG_ENTRIES[providerId]
      return [
        providerId,
        {
          providerId,
          apiKey: entry.apiKeyRequired ? "" : undefined,
          baseURL: entry.baseURLRequired
            ? getBuiltInProviderSettingsBaseURL(providerId)
            : undefined,
          defaultModel: entry.defaultModel,
          enabled: entry.defaultEnabled,
        },
      ]
    })
  ) as Record<
    BuiltInProviderId,
    {
      providerId: BuiltInProviderId
      apiKey?: string
      baseURL?: string
      defaultModel: string
      enabled: boolean
    }
  >
}
