// Re-export shim: canonical source moved to @cognia/provider-types (Stage 1).
export {
  BUILTIN_API_PROTOCOLS,
  PROVIDERS,
  getAllProviders,
  getModelConfig,
  getProviderConfig,
} from "@cognia/provider-types/provider"
export type {
  ApiKeyRotationStrategy,
  ApiKeyUsageStats,
  ApiProtocol,
  BYOKKeyEntry,
  BYOKProvider,
  BuiltInApiProtocol,
  CLIProxyAPIProviderSettings,
  CustomModelMetadata,
  CustomProviderSettings,
  Model,
  ModelConfig,
  ModelInferenceParams,
  ModelPricing,
  OAuthCallbackConfig,
  OAuthConfig,
  OAuthExchangeConfig,
  OAuthRuleTransform,
  OAuthRuleValue,
  OAuthValueFromRule,
  OAuthValueLiteralRule,
  OpenRouterProviderSettings,
  ProviderConfig,
  ProviderConnectionParams,
  ProviderHealth,
  ProviderHealthStatus,
  ProviderInferenceDefaults,
  ProviderMetadata,
  ProviderModelDiscoveryEntry,
  ProviderModelUsageEntry,
  ProviderName,
  ProviderType,
  ProviderUIPreferences,
  ProviderVerificationStatus,
  UserProviderSettings,
} from "@cognia/provider-types/provider"
