#!/usr/bin/env node
/**
 * Product footage recorder (ADR-0092, product footage amendment).
 *
 * Plays the signature task in a running E2E build of the real application and
 * records it, one locale at a time, into the HyperFrames project's source
 * folder: `web/video/recordings/<locale>.mp4` plus `<locale>.timing.json`,
 * which says when each stage and each story beat began so the film's camera
 * and callouts land on the real moments.
 *
 * Why CDP screencast and not Playwright's `recordVideo`: `recordVideo` encodes
 * VP8 at a fixed low bitrate, which is fine for a failing-test artefact and
 * visibly soft once the film zooms into a diff. The screencast hands over every
 * composited frame as a high-quality JPEG with its timestamp; ffmpeg then lays
 * them on a constant 30fps timeline, holding each frame until the next one
 * arrived, which is exactly what the screen showed.
 *
 * Recordings are intermediates (git-ignored). The committed outputs are the
 * rendered films under `web/public/video/`, produced by `render-video.mjs`.
 *
 * Prerequisites (checked and reported, never installed):
 *   - a product build with NEXT_PUBLIC_E2E=1 serving at --base-url
 *     (`pnpm test:e2e:build` then `pnpm test:e2e:static`, or `pnpm dev` with
 *     the variable set)
 *   - ffmpeg on PATH
 *
 * Usage:
 *   node web/scripts/record-product.mjs --base-url http://localhost:3000
 *   node web/scripts/record-product.mjs --locale zh
 */

import { spawnSync } from "node:child_process"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { BEAT_FOCUS, LOCALES } from "./demo-transcript.mjs"

const WEB_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
export const RECORDINGS_DIR = join(WEB_ROOT, "video", "recordings")

/** The viewport the product is recorded at. DPR 2, so frames are 2880×1800. */
export const VIEWPORT = { width: 1440, height: 900 }
export const SCALE = 2
export const FPS = 30

/** Camera time on the opening frame before the first stage plays. */
export const LEAD_IN_MS = 1200

/**
 * Every recording runs exactly this long. The locales stream different text
 * at the same rate, so their natural lengths differ by seconds; the last stage
 * (the approval halt) holds until the target instead, which lets one film
 * composition with one fixed duration serve both. The halt is a still picture,
 * so holding it longer changes nothing but the length.
 */
export const TARGET_DURATION_MS = 34_000

/**
 * How long to hold the final stage: its own hold, or longer when the
 * recording has not reached `targetMs` yet. Fails when the recording already
 * ran past the target, because a film cut to a fixed length would then drop
 * the end of the task.
 */
export function finalHold(elapsedMs, minHoldMs, targetMs = TARGET_DURATION_MS) {
  const hold = Math.max(minHoldMs, targetMs - elapsedMs)
  if (elapsedMs + minHoldMs > targetMs) {
    throw new Error(
      `the recording reached ${Math.round(elapsedMs + minHoldMs)}ms, past the ${targetMs}ms target`
    )
  }
  return hold
}

/**
 * The script the film composition loads for its per-locale beat times
 * (`web/video/recordings/timing.js`). Plain JS assigning a global, because a
 * composition may not fetch at render time.
 */
export function timingScript(timings) {
  return `// Generated by web/scripts/record-product.mjs. Do not edit.\nwindow.__cogniaFootageTiming = ${JSON.stringify(timings, null, 2)}\n`
}

export function parseArgs(argv) {
  const args = { baseUrl: "http://localhost:3000", locale: null, theme: "dark" }
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--base-url") args.baseUrl = argv[++i]
    else if (argv[i] === "--locale") args.locale = argv[++i]
    else if (argv[i] === "--theme") args.theme = argv[++i]
  }
  if (args.locale !== null && !LOCALES.includes(args.locale)) {
    throw new Error(`unsupported locale ${args.locale}; expected one of ${LOCALES.join(", ")}`)
  }
  if (args.theme !== "dark" && args.theme !== "light") {
    throw new Error(`unsupported theme ${args.theme}; expected dark or light`)
  }
  return args
}

/**
 * The ffmpeg concat-demuxer list for a screencast: each frame held until the
 * next one arrived, the last one held until `endTs`. Timestamps are seconds.
 * The demuxer ignores the final entry's duration, so the last file is listed
 * twice — the documented way to make it count.
 *
 * @param {Array<{ file: string, ts: number }>} frames in capture order
 * @param {number} endTs
 */
export function framesToConcat(frames, endTs) {
  if (frames.length === 0) throw new Error("no frames were captured")
  const lines = ["ffconcat version 1.0"]
  frames.forEach((frame, i) => {
    const until = i + 1 < frames.length ? frames[i + 1].ts : endTs
    // A frame the compositor delivered out of order, or twice at one instant,
    // holds for zero time rather than rewinding the clock.
    const duration = Math.max(0, until - frame.ts)
    lines.push(`file '${frame.file.replaceAll("'", "'\\''")}'`)
    lines.push(`duration ${duration.toFixed(6)}`)
  })
  lines.push(`file '${frames.at(-1).file.replaceAll("'", "'\\''")}'`)
  return `${lines.join("\n")}\n`
}

/**
 * The timing manifest the film reads: every stage's start and every beat's
 * start in seconds from the recording's first frame.
 *
 * @param {number} t0 the first frame's timestamp, seconds
 * @param {number[]} stageStarts wall-clock seconds each stage began
 * @param {Array<{ beat: string, stage: number }>} beats
 * @param {number} endTs
 */
export function buildTiming(t0, stageStarts, beats, endTs, focus = {}) {
  const rel = (ts) => Number(Math.max(0, ts - t0).toFixed(3))
  return {
    fps: FPS,
    width: VIEWPORT.width * SCALE,
    height: VIEWPORT.height * SCALE,
    durationS: rel(endTs),
    stages: stageStarts.map((ts, index) => ({ index, startS: rel(ts) })),
    beats: beats.map(({ beat, stage }) => {
      if (stage >= stageStarts.length) throw new Error(`beat ${beat} points past the last stage`)
      return { beat, startS: rel(stageStarts[stage]), focus: focus[beat] ?? null }
    }),
  }
}

/**
 * The viewport rectangle (CSS px) of a beat's focus element, clipped to the
 * viewport, or null when it is not on screen.
 */
export async function measureFocus(page, { selector, which }) {
  return page.evaluate(
    ({ sel, pick }) => {
      const all = [...document.querySelectorAll(sel)].filter((el) => {
        const r = el.getBoundingClientRect()
        return r.width > 0 && r.height > 0
      })
      const el = pick === "last" ? all.at(-1) : all[0]
      if (!el) return null
      const r = el.getBoundingClientRect()
      const x = Math.max(0, r.left)
      const y = Math.max(0, r.top)
      const w = Math.min(window.innerWidth, r.right) - x
      const h = Math.min(window.innerHeight, r.bottom) - y
      if (w <= 0 || h <= 0) return null
      return { x: Math.round(x), y: Math.round(y), w: Math.round(w), h: Math.round(h) }
    },
    { sel: selector, pick: which }
  )
}

/**
 * The hero loop's four shots, cut from a locale's recording (`compositions/hero-loop.html`,
 * STORYBOARD frames 11–14). A composition cannot seek a media clip to a
 * computed offset — `data-media-start` is read before scripts run — so each
 * shot is its own short file starting exactly on its payload, and the
 * composition plays every one from zero. Each cut runs a little longer than
 * its clip so the dissolve into the next shot never runs out of frames.
 *
 * @param {{ durationS: number, beats: Record<string, { startS: number }> }} timing
 */
export function heroShots(timing) {
  const at = (beat) => {
    const b = timing.beats[beat]
    if (!b) throw new Error(`hero shots: no ${beat} beat in the timing`)
    return b.startS
  }
  const shots = [
    // The held halt, which is also the loop seam: the last settled second.
    { name: "seam", startS: timing.durationS - 1.2, durationS: 1.1 },
    // Just before the failing output lands.
    { name: "reproduce", startS: at("reproduce") + 1.2, durationS: 3.1 },
    // The fix narration, then the diff.
    { name: "fix", startS: at("fix") + 0.2, durationS: 3.8 },
    // The hand-off line and the dialog opening, into the hold.
    { name: "halt", startS: at("approval") - 0.2, durationS: 4.0 },
  ]
  for (const shot of shots) {
    if (shot.startS < 0 || shot.startS + shot.durationS > timing.durationS) {
      throw new Error(`hero shot ${shot.name} falls outside the ${timing.durationS}s recording`)
    }
  }
  return shots
}

/** ffmpeg arguments that cut one hero shot, frame-accurate, at intermediate quality. */
export function heroCutArgs(source, shot, outFile) {
  return [
    "-y",
    "-loglevel",
    "error",
    "-i",
    source,
    "-ss",
    shot.startS.toFixed(3),
    "-t",
    shot.durationS.toFixed(3),
    "-an",
    "-c:v",
    "libx264",
    "-preset",
    "slow",
    "-crf",
    "14",
    "-pix_fmt",
    "yuv420p",
    "-movflags",
    "+faststart",
    outFile,
  ]
}

/** The ffmpeg arguments that turn a concat list into the intermediate. */
export function ffmpegArgs(listFile, outFile) {
  return [
    "-y",
    "-loglevel",
    "error",
    "-f",
    "concat",
    "-safe",
    "0",
    "-i",
    listFile,
    "-vf",
    `fps=${FPS},scale=${VIEWPORT.width * SCALE}:${VIEWPORT.height * SCALE}:flags=lanczos,format=yuv420p`,
    "-c:v",
    "libx264",
    "-preset",
    "slow",
    "-crf",
    "14",
    "-movflags",
    "+faststart",
    outFile,
  ]
}

function assertFfmpeg() {
  const probe = spawnSync("ffmpeg", ["-version"], { encoding: "utf8" })
  if (probe.status !== 0) throw new Error("ffmpeg is not on PATH; install it to record")
}

async function recordLocale(browser, { baseUrl, locale, theme }) {
  const { openDemoSession } = await import("./demo-session.mjs")
  const context = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: SCALE,
    colorScheme: theme,
    reducedMotion: "no-preference",
  })
  const page = await context.newPage()
  const frameDir = mkdtempSync(join(tmpdir(), `cognia-footage-${locale}-`))

  try {
    const session = await openDemoSession(page, { baseUrl, locale, theme })
    // Let the empty session settle so the film opens on a still frame.
    await page.waitForTimeout(800)

    const cdp = await context.newCDPSession(page)
    /** @type {Array<{ file: string, ts: number }>} */
    const frames = []
    const pending = []
    cdp.on("Page.screencastFrame", ({ data, metadata, sessionId }) => {
      const file = join(frameDir, `${String(frames.length).padStart(6, "0")}.jpg`)
      frames.push({ file, ts: metadata.timestamp ?? Date.now() / 1000 })
      writeFileSync(file, Buffer.from(data, "base64"))
      pending.push(cdp.send("Page.screencastFrameAck", { sessionId }).catch(() => undefined))
    })
    await cdp.send("Page.startScreencast", {
      format: "jpeg",
      quality: 92,
      maxWidth: VIEWPORT.width * SCALE,
      maxHeight: VIEWPORT.height * SCALE,
      everyNthFrame: 1,
    })

    await page.waitForTimeout(LEAD_IN_MS)
    const stageStarts = []
    const { holds, beats, script } = session.transcript
    // The film's clock starts on the first frame the screencast delivered;
    // after the lead-in there is always one.
    if (frames.length === 0)
      throw new Error("the screencast delivered no frames during the lead-in")
    const startedAt = frames[0].ts
    const beatAt = new Map(beats.map((b) => [b.stage, b.beat]))
    /** @type {Record<string, { x: number, y: number, w: number, h: number } | null>} */
    const focus = {}
    let currentBeat = null
    const settleFocus = async () => {
      if (currentBeat) focus[currentBeat] = await measureFocus(page, BEAT_FOCUS[currentBeat])
    }
    for (let i = 0; i < script.stages.length; i += 1) {
      if (beatAt.has(i)) {
        // The beat that is ending has settled; measure where its subject sits.
        await settleFocus()
        currentBeat = beatAt.get(i)
      }
      stageStarts.push(Date.now() / 1000)
      const { index } = await session.advance()
      if (index !== i) throw new Error(`stage ${i} reported index ${index}`)
      const last = i === script.stages.length - 1
      if (last) {
        // The halt: let the dialog finish opening, then measure it.
        await page.waitForTimeout(600)
        await settleFocus()
      }
      const elapsedMs = (Date.now() / 1000 - startedAt) * 1000
      await page.waitForTimeout(last ? finalHold(elapsedMs, Math.max(0, holds[i] - 600)) : holds[i])
    }
    const endTs = startedAt + TARGET_DURATION_MS / 1000

    await cdp.send("Page.stopScreencast")
    await Promise.all(pending)
    if (frames.length === 0) throw new Error("the screencast delivered no frames")

    // Screencast timestamps and Date.now() share the wall clock; anchoring on
    // the first frame keeps both on one timeline.
    const t0 = frames[0].ts
    mkdirSync(RECORDINGS_DIR, { recursive: true })
    const listFile = join(frameDir, "frames.ffconcat")
    writeFileSync(listFile, framesToConcat(frames, endTs))
    const outFile = join(RECORDINGS_DIR, `${locale}.mp4`)
    const encode = spawnSync("ffmpeg", ffmpegArgs(listFile, outFile), { encoding: "utf8" })
    if (encode.status !== 0) throw new Error(`ffmpeg failed: ${encode.stderr}`)

    const timing = buildTiming(t0, stageStarts, beats, endTs, focus)
    const unmeasured = timing.beats.filter((b) => !b.focus).map((b) => b.beat)
    if (unmeasured.length > 0) throw new Error(`no focus measured for ${unmeasured.join(", ")}`)
    writeFileSync(
      join(RECORDINGS_DIR, `${locale}.timing.json`),
      `${JSON.stringify({ locale, theme, frames: frames.length, ...timing }, null, 2)}\n`
    )
    writeTimingScript()

    const heroDir = join(RECORDINGS_DIR, "hero", locale)
    mkdirSync(heroDir, { recursive: true })
    for (const shot of heroShots(timing)) {
      const cut = spawnSync(
        "ffmpeg",
        heroCutArgs(outFile, shot, join(heroDir, `${shot.name}.mp4`)),
        {
          encoding: "utf8",
        }
      )
      if (cut.status !== 0)
        throw new Error(`ffmpeg failed cutting hero shot ${shot.name}: ${cut.stderr}`)
    }
    console.log(`[record] ${locale}: ${frames.length} frames, ${timing.durationS}s → ${outFile}`)
  } finally {
    await context.close()
    rmSync(frameDir, { recursive: true, force: true })
  }
}

/** Rebuild `timing.js` from every locale's timing file on disk. */
function writeTimingScript() {
  const timings = {}
  for (const locale of LOCALES) {
    const file = join(RECORDINGS_DIR, `${locale}.timing.json`)
    if (!existsSync(file)) continue
    const { durationS, width, height, beats } = JSON.parse(readFileSync(file, "utf8"))
    timings[locale] = {
      durationS,
      // Focus rectangles are in the recorded viewport's CSS pixels.
      viewport: { width: width / SCALE, height: height / SCALE },
      beats: Object.fromEntries(beats.map((b) => [b.beat, { startS: b.startS, focus: b.focus }])),
    }
  }
  writeFileSync(join(RECORDINGS_DIR, "timing.js"), timingScript(timings))
}

async function main() {
  const args = parseArgs(process.argv.slice(2))
  assertFfmpeg()
  const { loadChromium } = await import("./capture-og.mjs")
  const chromium = await loadChromium()
  if (!chromium) {
    console.error("[record] neither `playwright` nor `@playwright/test` resolves here")
    process.exit(1)
  }

  const locales = args.locale ? [args.locale] : LOCALES
  const browser = await chromium.launch()
  const failures = []
  try {
    for (const locale of locales) {
      try {
        await recordLocale(browser, { baseUrl: args.baseUrl, locale, theme: args.theme })
      } catch (error) {
        failures.push(`${locale}: ${error instanceof Error ? error.message : String(error)}`)
        console.error(`[record] FAILED ${locale}`)
      }
    }
  } finally {
    await browser.close()
  }
  for (const failure of failures) console.error(`[record] ${failure}`)
  if (failures.length > 0) process.exit(1)
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  await main()
}
