import assert from "node:assert/strict"
import test from "node:test"

import {
  FPS,
  SCALE,
  VIEWPORT,
  TARGET_DURATION_MS,
  buildTiming,
  ffmpegArgs,
  finalHold,
  framesToConcat,
  heroCutArgs,
  heroShots,
  parseArgs,
  timingScript,
} from "./record-product.mjs"

test("parseArgs defaults to the dark theme, every locale, the default dev origin", () => {
  assert.deepEqual(parseArgs([]), {
    baseUrl: "http://localhost:3000",
    locale: null,
    theme: "dark",
  })
})

test("parseArgs reads the flags and refuses unknown values", () => {
  assert.deepEqual(parseArgs(["--base-url", "http://x:1", "--locale", "zh", "--theme", "light"]), {
    baseUrl: "http://x:1",
    locale: "zh",
    theme: "light",
  })
  assert.throws(() => parseArgs(["--locale", "fr"]), /unsupported locale fr/)
  assert.throws(() => parseArgs(["--theme", "sepia"]), /unsupported theme sepia/)
})

test("framesToConcat holds each frame until the next and the last until the end", () => {
  const list = framesToConcat(
    [
      { file: "/f/0.jpg", ts: 10 },
      { file: "/f/1.jpg", ts: 10.5 },
      { file: "/f/2.jpg", ts: 12 },
    ],
    13.25
  )
  assert.equal(
    list,
    [
      "ffconcat version 1.0",
      "file '/f/0.jpg'",
      "duration 0.500000",
      "file '/f/1.jpg'",
      "duration 1.500000",
      "file '/f/2.jpg'",
      "duration 1.250000",
      "file '/f/2.jpg'",
      "",
    ].join("\n")
  )
})

test("framesToConcat never gives a frame negative time", () => {
  const list = framesToConcat(
    [
      { file: "a.jpg", ts: 5 },
      { file: "b.jpg", ts: 4.9 },
    ],
    6
  )
  assert.match(list, /file 'a.jpg'\nduration 0.000000/)
})

test("framesToConcat quotes paths with apostrophes and refuses an empty capture", () => {
  assert.match(framesToConcat([{ file: "/it's/0.jpg", ts: 0 }], 1), /file '\/it'\\''s\/0.jpg'/)
  assert.throws(() => framesToConcat([], 1), /no frames/)
})

test("buildTiming puts stages and beats on the first frame's clock", () => {
  const timing = buildTiming(
    100,
    [101.2, 102, 104.5],
    [
      { beat: "request", stage: 0 },
      { beat: "fix", stage: 2 },
    ],
    110
  )
  assert.deepEqual(timing, {
    fps: FPS,
    width: VIEWPORT.width * SCALE,
    height: VIEWPORT.height * SCALE,
    durationS: 10,
    stages: [
      { index: 0, startS: 1.2 },
      { index: 1, startS: 2 },
      { index: 2, startS: 4.5 },
    ],
    beats: [
      { beat: "request", startS: 1.2, focus: null },
      { beat: "fix", startS: 4.5, focus: null },
    ],
  })
})

test("buildTiming attaches each beat's measured focus rectangle", () => {
  const rect = { x: 10, y: 20, w: 300, h: 120 }
  const timing = buildTiming(0, [1], [{ beat: "fix", stage: 0 }], 2, { fix: rect })
  assert.deepEqual(timing.beats, [{ beat: "fix", startS: 1, focus: rect }])
})

test("buildTiming refuses a beat past the last stage", () => {
  assert.throws(() => buildTiming(0, [1], [{ beat: "x", stage: 3 }], 2), /beat x points past/)
})

test("ffmpegArgs encodes a constant-rate yuv420p H.264 intermediate at capture size", () => {
  const args = ffmpegArgs("/l.ffconcat", "/o.mp4")
  assert.equal(args.at(-1), "/o.mp4")
  assert.ok(args.includes("/l.ffconcat"))
  const vf = args[args.indexOf("-vf") + 1]
  assert.match(vf, new RegExp(`fps=${FPS}`))
  assert.match(vf, /scale=2880:1800/)
  assert.match(vf, /format=yuv420p/)
  assert.equal(args[args.indexOf("-c:v") + 1], "libx264")
})

test("finalHold stretches the last stage to the target length", () => {
  assert.equal(finalHold(29_500, 4_500, 34_000), 4_500)
  assert.equal(finalHold(25_000, 4_500, 34_000), 9_000)
  assert.equal(finalHold(29_500, 4_500), TARGET_DURATION_MS - 29_500)
})

test("finalHold refuses a recording that would overrun the target", () => {
  assert.throws(() => finalHold(31_000, 4_500, 34_000), /35500ms, past the 34000ms target/)
})

test("timingScript assigns the per-locale timings to one global, loadable without fetch", () => {
  const script = timingScript({ en: { durationS: 34, beats: { fix: 15 } } })
  assert.match(script, /^\/\/ Generated by web\/scripts\/record-product\.mjs/)
  const sandbox = {}
  new Function("window", script)(sandbox)
  assert.deepEqual(sandbox.__cogniaFootageTiming, { en: { durationS: 34, beats: { fix: 15 } } })
})

const TIMING = {
  durationS: 34,
  beats: { reproduce: { startS: 6.5 }, fix: { startS: 15 }, approval: { startS: 27 } },
}

test("heroShots cuts the seam from the settled end and each shot just before its payload", () => {
  assert.deepEqual(heroShots(TIMING), [
    { name: "seam", startS: 32.8, durationS: 1.1 },
    { name: "reproduce", startS: 7.7, durationS: 3.1 },
    { name: "fix", startS: 15.2, durationS: 3.8 },
    { name: "halt", startS: 26.8, durationS: 4 },
  ])
})

test("heroShots refuses a timing without a beat it needs or a shot past the end", () => {
  assert.throws(() => heroShots({ durationS: 34, beats: {} }), /no reproduce beat/)
  assert.throws(
    () => heroShots({ ...TIMING, beats: { ...TIMING.beats, approval: { startS: 31 } } }),
    /hero shot halt falls outside/
  )
})

test("heroCutArgs seeks after the input for a frame-accurate, silent cut", () => {
  const args = heroCutArgs("/r/en.mp4", { name: "fix", startS: 15.2, durationS: 3.8 }, "/o/fix.mp4")
  assert.ok(args.indexOf("-i") < args.indexOf("-ss"))
  assert.equal(args[args.indexOf("-ss") + 1], "15.200")
  assert.equal(args[args.indexOf("-t") + 1], "3.800")
  assert.ok(args.includes("-an"))
  assert.equal(args.at(-1), "/o/fix.mp4")
})
