import type { PluginContext, PluginDefinition } from "@cognia/plugin-sdk"
import baseManifest from "../plugin.json"

type WorldPalette = {
  background: string
  card: string
  popover: string
  muted: string
  border: string
  input: string
  primary: string
  primaryForeground: string
  secondary: string
  accent: string
  accentForeground: string
  brandApproval: string
  brandWash: string
  sidebar: string
  sidebarAccent: string
  sidebarBorder: string
}

const baseTokens = {
  "--background": "#0E1118",
  "--foreground": "#F4F7FC",
  "--card": "#171C26",
  "--card-foreground": "#F4F7FC",
  "--popover": "#1B2230",
  "--popover-foreground": "#F4F7FC",
  "--muted": "#262E3D",
  "--muted-foreground": "#B7C1D0",
  "--border": "#3C4658",
  "--input": "#30394A",
  "--ring": "#8EC5FF",
  "--primary": "#8EC5FF",
  "--primary-foreground": "#06101A",
  "--secondary": "#30394A",
  "--secondary-foreground": "#F4F7FC",
  "--accent": "#B79CFF",
  "--accent-foreground": "#110A22",
  "--brand-action": "#8EC5FF",
  "--brand-approval": "#E7C873",
  "--brand-wash": "#20293A",
  "--destructive": "#FF7180",
  "--destructive-foreground": "#1B0508",
  "--success": "#78D7A5",
  "--success-foreground": "#05150D",
  "--warning": "#E7C873",
  "--warning-foreground": "#181204",
  "--info": "#78C8FF",
  "--info-foreground": "#06131D",
  "--sidebar": "#090D14",
  "--sidebar-foreground": "#EAF0F8",
  "--sidebar-primary": "#8EC5FF",
  "--sidebar-primary-foreground": "#06101A",
  "--sidebar-accent": "#222B3A",
  "--sidebar-accent-foreground": "#F4F7FC",
  "--sidebar-border": "#313B4B",
  "--sidebar-ring": "#8EC5FF",
  "--chart-1": "#8EC5FF",
  "--chart-2": "#B79CFF",
  "--chart-3": "#E7C873",
  "--chart-4": "#78D7A5",
  "--chart-5": "#FF7180",
  "--wf-trigger": "#78D7A5",
  "--wf-action": "#78C8FF",
  "--wf-ai": "#B79CFF",
  "--wf-flow": "#E7C873",
  "--wf-data": "#FF8294",
  "--wf-io": "#72D7E0",
  "--wf-annotation": "#A8B2C2",
  "--wf-status-idle": "#A8B2C2",
  "--wf-status-running": "#E7C873",
  "--wf-status-succeeded": "#78D7A5",
  "--wf-status-failed": "#FF7180",
  "--wf-status-skipped": "#6D7788",
  "--wf-status-waiting": "#78C8FF",
  "--effort-ultra": "#B79CFF",
  "--effort-ultra-muted": "#41355F",
}

function createWorldTheme(id: string, name: string, palette: WorldPalette) {
  return {
    id,
    name,
    isDark: true,
    cssVariables: {
      ...baseTokens,
      "--background": palette.background,
      "--card": palette.card,
      "--popover": palette.popover,
      "--muted": palette.muted,
      "--border": palette.border,
      "--input": palette.input,
      "--ring": palette.primary,
      "--primary": palette.primary,
      "--primary-foreground": palette.primaryForeground,
      "--secondary": palette.secondary,
      "--accent": palette.accent,
      "--accent-foreground": palette.accentForeground,
      "--brand-action": palette.primary,
      "--brand-approval": palette.brandApproval,
      "--brand-wash": palette.brandWash,
      "--sidebar": palette.sidebar,
      "--sidebar-primary": palette.primary,
      "--sidebar-primary-foreground": palette.primaryForeground,
      "--sidebar-accent": palette.sidebarAccent,
      "--sidebar-border": palette.sidebarBorder,
      "--sidebar-ring": palette.primary,
      "--chart-1": palette.primary,
      "--chart-2": palette.accent,
      "--chart-3": palette.brandApproval,
      "--wf-action": palette.primary,
      "--wf-ai": palette.accent,
      "--wf-flow": palette.brandApproval,
      "--wf-status-running": palette.brandApproval,
      "--wf-status-waiting": palette.primary,
      "--effort-ultra": palette.accent,
    },
  }
}

const worldThemes = [
  createWorldTheme("finality-cosmos", "Finality · Lunar Cosmos", {
    background: "#111020",
    card: "#1B1930",
    popover: "#211E38",
    muted: "#2D2946",
    border: "#4C456B",
    input: "#373151",
    primary: "#C8B2FF",
    primaryForeground: "#130C22",
    secondary: "#373151",
    accent: "#89CFFF",
    accentForeground: "#07151E",
    brandApproval: "#F0C7A5",
    brandWash: "#25213D",
    sidebar: "#0A0914",
    sidebarAccent: "#29243E",
    sidebarBorder: "#3C3654",
  }),
  createWorldTheme("resonance-tide", "Resonance · Black Shores", {
    background: "#09151D",
    card: "#10232D",
    popover: "#142C37",
    muted: "#1C3944",
    border: "#315563",
    input: "#244550",
    primary: "#7FE5E8",
    primaryForeground: "#041719",
    secondary: "#244550",
    accent: "#A8B7FF",
    accentForeground: "#0A1021",
    brandApproval: "#E8D29B",
    brandWash: "#16313D",
    sidebar: "#061016",
    sidebarAccent: "#193541",
    sidebarBorder: "#284955",
  }),
  createWorldTheme("construct-signal", "Construct · Signal Grey", {
    background: "#111316",
    card: "#1B1E23",
    popover: "#22262C",
    muted: "#2D333B",
    border: "#4B535E",
    input: "#383F48",
    primary: "#E7EDF5",
    primaryForeground: "#111419",
    secondary: "#353B43",
    accent: "#76C9FF",
    accentForeground: "#06141D",
    brandApproval: "#F5B26D",
    brandWash: "#252A31",
    sidebar: "#090A0D",
    sidebarAccent: "#292E35",
    sidebarBorder: "#3B424B",
  }),
  createWorldTheme("elmo-expedition", "Elmo · Expedition Amber", {
    background: "#17130F",
    card: "#251E18",
    popover: "#2E251D",
    muted: "#3B3026",
    border: "#5D4B3A",
    input: "#46382C",
    primary: "#F0BE78",
    primaryForeground: "#1C1005",
    secondary: "#46382C",
    accent: "#A9D9D3",
    accentForeground: "#071817",
    brandApproval: "#F0BE78",
    brandWash: "#31271F",
    sidebar: "#0E0B08",
    sidebarAccent: "#342A21",
    sidebarBorder: "#493B2E",
  }),
  createWorldTheme("containment-frost", "Containment · Frostline", {
    background: "#0C141C",
    card: "#14222D",
    popover: "#192A36",
    muted: "#223844",
    border: "#375664",
    input: "#294552",
    primary: "#83D7FF",
    primaryForeground: "#05151E",
    secondary: "#294552",
    accent: "#AAB7FF",
    accentForeground: "#0A1020",
    brandApproval: "#E4C98D",
    brandWash: "#182F3B",
    sidebar: "#071017",
    sidebarAccent: "#1D3542",
    sidebarBorder: "#2C4A57",
  }),
  createWorldTheme("ark-scarlet", "Ark · Scarlet Dawn", {
    background: "#181012",
    card: "#27191D",
    popover: "#301E23",
    muted: "#3D292F",
    border: "#63414A",
    input: "#493139",
    primary: "#FF8995",
    primaryForeground: "#21070B",
    secondary: "#493139",
    accent: "#D6B2FF",
    accentForeground: "#170B24",
    brandApproval: "#EBC880",
    brandWash: "#342127",
    sidebar: "#0F090B",
    sidebarAccent: "#382329",
    sidebarBorder: "#50333B",
  }),
  createWorldTheme("academy-blue-hour", "Academy · Blue Hour", {
    background: "#0B1321",
    card: "#121F33",
    popover: "#172740",
    muted: "#203653",
    border: "#345578",
    input: "#294363",
    primary: "#79D5FF",
    primaryForeground: "#05141D",
    secondary: "#294363",
    accent: "#F29DCE",
    accentForeground: "#230A18",
    brandApproval: "#F3CD7D",
    brandWash: "#182D49",
    sidebar: "#070D18",
    sidebarAccent: "#1B304C",
    sidebarBorder: "#294565",
  }),
  createWorldTheme("minos-noir", "Minos · Rain Noir", {
    background: "#111013",
    card: "#1D1A20",
    popover: "#252129",
    muted: "#312C37",
    border: "#514957",
    input: "#3C3542",
    primary: "#C9AEDC",
    primaryForeground: "#180D20",
    secondary: "#3C3542",
    accent: "#78B9D1",
    accentForeground: "#07151B",
    brandApproval: "#DDBD83",
    brandWash: "#29242D",
    sidebar: "#09080B",
    sidebarAccent: "#2C2731",
    sidebarBorder: "#403A47",
  }),
]

type WallpaperSpec = {
  id: string
  name: string
  asset: string
  themeId: string
  packName: string
  description: string
  density: "cinematic-calm" | "tactical-compact"
  radius: number
  motionSpeed: number
}

const wallpaperSpecs: WallpaperSpec[] = [
  {
    id: "kiana-finality-lunar-dawn",
    name: "Kiana · Lunar Dawn",
    asset: "assets/honkai-impact-3rd/kiana-finality-lunar-dawn.webp",
    themeId: "finality-cosmos",
    packName: "FINALITY // Lunar Dawn",
    description: "A quiet violet sunrise beyond the lunar observation deck.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "mei-origin-hyperion-rain",
    name: "Raiden Mei · Hyperion Rain",
    asset: "assets/honkai-impact-3rd/mei-origin-hyperion-rain.webp",
    themeId: "finality-cosmos",
    packName: "ORIGIN // Hyperion Rain",
    description: "Rain, tea, and restrained violet light on the garden deck.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
  {
    id: "elysia-ego-crystal-garden",
    name: "Elysia · Crystal Garden",
    asset: "assets/honkai-impact-3rd/elysia-ego-crystal-garden.webp",
    themeId: "finality-cosmos",
    packName: "EGO // Crystal Garden",
    description: "Soft rose crystal light with generous, luminous workspace.",
    density: "cinematic-calm",
    radius: 0.875,
    motionSpeed: 0.75,
  },
  {
    id: "shorekeeper-black-shores-blue-hour",
    name: "Shorekeeper · Black Shores Blue Hour",
    asset: "assets/wuthering-waves/shorekeeper-black-shores-blue-hour.webp",
    themeId: "resonance-tide",
    packName: "BLACK SHORES // Blue Hour",
    description: "A star-blue coast and a single luminous butterfly.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "camellya-rain-greenhouse",
    name: "Camellya · Rain Greenhouse",
    asset: "assets/wuthering-waves/camellya-rain-greenhouse.webp",
    themeId: "resonance-tide",
    packName: "CAMELLYA // Rain Greenhouse",
    description: "Wet glass, quiet foliage, and restrained crimson accents.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.75,
  },
  {
    id: "jinhsi-jinzhou-dawn",
    name: "Jinhsi · Jinzhou Dawn",
    asset: "assets/wuthering-waves/jinhsi-jinzhou-dawn.webp",
    themeId: "resonance-tide",
    packName: "JINZHOU // Dawn Briefing",
    description: "Warm mountain air and pale ceremonial teal at sunrise.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "lucia-crimson-weave-metro-dawn",
    name: "Lucia · Metro Dawn",
    asset: "assets/punishing-gray-raven/lucia-crimson-weave-metro-dawn.webp",
    themeId: "construct-signal",
    packName: "CRIMSON WEAVE // Metro Dawn",
    description: "A measured maintenance break in a rain-dark service bay.",
    density: "tactical-compact",
    radius: 0.375,
    motionSpeed: 0.5,
  },
  {
    id: "bianca-stigmata-cathedral-light",
    name: "Bianca · Cathedral Light",
    asset: "assets/punishing-gray-raven/bianca-stigmata-cathedral-light.webp",
    themeId: "construct-signal",
    packName: "STIGMATA // Cathedral Light",
    description: "Graphite surfaces shaped by quiet silver window light.",
    density: "tactical-compact",
    radius: 0.5,
    motionSpeed: 0.5,
  },
  {
    id: "selena-capriccio-empty-stage",
    name: "Selena · Empty Stage",
    asset: "assets/punishing-gray-raven/selena-capriccio-empty-stage.webp",
    themeId: "construct-signal",
    packName: "CAPRICCIO // Empty Stage",
    description: "A dark concert hall balanced by cyan frame light.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
  {
    id: "groza-elmo-briefing",
    name: "Groza · Elmo Briefing",
    asset: "assets/girls-frontline-2/groza-elmo-briefing.webp",
    themeId: "elmo-expedition",
    packName: "ELMO // Warm Briefing Bay",
    description: "Amber expedition light over disciplined tactical surfaces.",
    density: "tactical-compact",
    radius: 0.375,
    motionSpeed: 0.5,
  },
  {
    id: "suomi-snow-outpost",
    name: "Suomi · Snow Outpost",
    asset: "assets/girls-frontline-2/suomi-snow-outpost.webp",
    themeId: "elmo-expedition",
    packName: "SUOMI // Snow Lantern",
    description: "A warm lantern against a blue winter outpost.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "makiatto-rain-overwatch",
    name: "Makiatto · Rain Overwatch",
    asset: "assets/girls-frontline-2/makiatto-rain-overwatch.webp",
    themeId: "elmo-expedition",
    packName: "MAKIATTO // Rain Overwatch",
    description: "A muted rooftop pause with a distant city horizon.",
    density: "tactical-compact",
    radius: 0.375,
    motionSpeed: 0.5,
  },
  {
    id: "lyfe-infinite-sight-lab-dawn",
    name: "Lyfe · Lab Dawn",
    asset: "assets/snowbreak/lyfe-infinite-sight-lab-dawn.webp",
    themeId: "containment-frost",
    packName: "INFINITE SIGHT // Lab Dawn",
    description: "Crystal-blue calibration light inside a living laboratory.",
    density: "tactical-compact",
    radius: 0.5,
    motionSpeed: 0.5,
  },
  {
    id: "chenxing-jade-arc-lantern-rain",
    name: "Chenxing · Lantern Rain",
    asset: "assets/snowbreak/chenxing-jade-arc-lantern-rain.webp",
    themeId: "containment-frost",
    packName: "JADE ARC // Lantern Rain",
    description: "Warm archive lanterns framed by a rain-blue mountain city.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
  {
    id: "katya-blue-bolt-frost-terminal",
    name: "Katya · Frost Terminal",
    asset: "assets/snowbreak/katya-blue-bolt-frost-terminal.webp",
    themeId: "containment-frost",
    packName: "BLUE BOLT // Frost Terminal",
    description: "Clean glacial light and a spacious silent terminal.",
    density: "tactical-compact",
    radius: 0.5,
    motionSpeed: 0.75,
  },
  {
    id: "rapi-red-hood-ark-hangar",
    name: "Rapi: Red Hood · Ark Hangar",
    asset: "assets/nikke/rapi-red-hood-ark-hangar.webp",
    themeId: "ark-scarlet",
    packName: "RED HOOD // Ark Sunrise",
    description: "Scarlet equipment light against a warm hangar sunrise.",
    density: "tactical-compact",
    radius: 0.375,
    motionSpeed: 0.5,
  },
  {
    id: "cinderella-glass-observatory",
    name: "Cinderella · Glass Observatory",
    asset: "assets/nikke/cinderella-glass-observatory.webp",
    themeId: "ark-scarlet",
    packName: "CINDERELLA // Glass Observatory",
    description: "Moonlit white machinery reflected across silent glass.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "dorothy-eden-rain-garden",
    name: "Dorothy · Eden Rain Garden",
    asset: "assets/nikke/dorothy-eden-rain-garden.webp",
    themeId: "ark-scarlet",
    packName: "EDEN // After the Rain",
    description: "Rose-white garden light and a calm skyline after rain.",
    density: "cinematic-calm",
    radius: 0.875,
    motionSpeed: 0.75,
  },
  {
    id: "hoshino-abydos-afternoon",
    name: "Hoshino · Abydos Afternoon",
    asset: "assets/blue-archive/hoshino-abydos-afternoon.webp",
    themeId: "academy-blue-hour",
    packName: "ABYDOS // Sleepy Afternoon",
    description: "A warm empty classroom with a gentle pink-cyan balance.",
    density: "cinematic-calm",
    radius: 0.875,
    motionSpeed: 0.75,
  },
  {
    id: "aris-millennium-night",
    name: "Aris · Millennium Night",
    asset: "assets/blue-archive/aris-millennium-night.webp",
    themeId: "academy-blue-hour",
    packName: "MILLENNIUM // Night Repair",
    description: "Deep blue clubroom light with crisp cyan focus accents.",
    density: "tactical-compact",
    radius: 0.625,
    motionSpeed: 0.75,
  },
  {
    id: "hina-gehenna-before-dawn",
    name: "Hina · Gehenna Before Dawn",
    asset: "assets/blue-archive/hina-gehenna-before-dawn.webp",
    themeId: "academy-blue-hour",
    packName: "GEHENNA // Before Dawn",
    description: "A quiet violet office designed for focused late work.",
    density: "tactical-compact",
    radius: 0.5,
    motionSpeed: 0.5,
  },
  {
    id: "shalom-mbcc-rain-corridor",
    name: "Shalom · MBCC Rain Corridor",
    asset: "assets/path-to-nowhere/shalom-mbcc-rain-corridor.webp",
    themeId: "minos-noir",
    packName: "MBCC // Rain Corridor",
    description: "Controlled graphite noir with a restrained wine accent.",
    density: "tactical-compact",
    radius: 0.25,
    motionSpeed: 0.5,
  },
  {
    id: "adela-fog-salon",
    name: "Adela · Fog Salon",
    asset: "assets/path-to-nowhere/adela-fog-salon.webp",
    themeId: "minos-noir",
    packName: "ADELA // Fog Salon",
    description: "Midnight salon mirrors, pale structure, and blue steel.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
  {
    id: "hamel-silent-theater",
    name: "Hamel · Silent Theater",
    asset: "assets/path-to-nowhere/hamel-silent-theater.webp",
    themeId: "minos-noir",
    packName: "HAMEL // Silent Theater",
    description: "Violet stage water and a broad meditative workspace.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "bronya-truth-snow-workshop",
    name: "Bronya · Snow Workshop",
    asset: "assets/honkai-impact-3rd/bronya-truth-snow-workshop.webp",
    themeId: "finality-cosmos",
    packName: "TRUTH // Snow Workshop",
    description: "Clean cyan machinery against a broad winter morning.",
    density: "tactical-compact",
    radius: 0.5,
    motionSpeed: 0.5,
  },
  {
    id: "fu-hua-vicissitude-tea-pavilion",
    name: "Fu Hua · Tea Pavilion",
    asset: "assets/honkai-impact-3rd/fu-hua-vicissitude-tea-pavilion.webp",
    themeId: "finality-cosmos",
    packName: "VICISSITUDE // Tea Pavilion",
    description: "Warm phoenix dusk and a calm mountain workspace.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
  {
    id: "changli-jinzhou-summer-rain",
    name: "Changli · Jinzhou Summer Rain",
    asset: "assets/wuthering-waves/changli-jinzhou-summer-rain.webp",
    themeId: "resonance-tide",
    packName: "CHANGLI // Summer Rain",
    description: "A warm strategy room framed by cool Jinzhou rain.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
  {
    id: "phoebe-basilica-morning",
    name: "Phoebe · Basilica Morning",
    asset: "assets/wuthering-waves/phoebe-basilica-morning.webp",
    themeId: "resonance-tide",
    packName: "PHOEBE // Basilica Morning",
    description: "Airy gold-blue garden light with generous quiet space.",
    density: "cinematic-calm",
    radius: 0.875,
    motionSpeed: 0.5,
  },
  {
    id: "liv-babylonia-healing-garden",
    name: "Liv · Healing Garden",
    asset: "assets/punishing-gray-raven/liv-babylonia-healing-garden.webp",
    themeId: "construct-signal",
    packName: "LIV // Healing Garden",
    description: "Soft white medical light settling into a living garden.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "vera-rozen-night-garage",
    name: "Vera Rozen · Night Garage",
    asset: "assets/punishing-gray-raven/vera-rozen-night-garage.webp",
    themeId: "construct-signal",
    packName: "VERA ROZEN // Night Garage",
    description: "Cerberus red task lights over a focused graphite bay.",
    density: "tactical-compact",
    radius: 0.25,
    motionSpeed: 0.5,
  },
  {
    id: "daiyan-elmo-rain-melody",
    name: "Daiyan · Elmo Rain Melody",
    asset: "assets/girls-frontline-2/daiyan-elmo-rain-melody.webp",
    themeId: "elmo-expedition",
    packName: "DAIYAN // Rain Melody",
    description: "A quiet cabin melody overlooking a rain-softened route.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "klukai-safehouse-dawn",
    name: "Klukai · Safehouse Dawn",
    asset: "assets/girls-frontline-2/klukai-safehouse-dawn.webp",
    themeId: "elmo-expedition",
    packName: "KLUKAI // Safehouse Dawn",
    description: "Warm blind light and disciplined purple tactical surfaces.",
    density: "tactical-compact",
    radius: 0.375,
    motionSpeed: 0.75,
  },
  {
    id: "fenny-coronet-training-break",
    name: "Fenny Coronet · Training Break",
    asset: "assets/snowbreak/fenny-coronet-training-break.webp",
    themeId: "containment-frost",
    packName: "FENNY // Training Break",
    description: "A warm empty training hall with bright field accents.",
    density: "tactical-compact",
    radius: 0.5,
    motionSpeed: 0.75,
  },
  {
    id: "mauxir-shadow-ka-desert-twilight",
    name: "Mauxir Shadow Ka · Desert Twilight",
    asset: "assets/snowbreak/mauxir-shadow-ka-desert-twilight.webp",
    themeId: "containment-frost",
    packName: "SHADOW KA // Desert Twilight",
    description: "Warm desert distance balanced by restrained cyan containment light.",
    density: "tactical-compact",
    radius: 0.375,
    motionSpeed: 0.5,
  },
  {
    id: "scarlet-black-shadow-snow-shrine",
    name: "Scarlet: Black Shadow · Snow Shrine",
    asset: "assets/nikke/scarlet-black-shadow-snow-shrine.webp",
    themeId: "ark-scarlet",
    packName: "BLACK SHADOW // Snow Shrine",
    description: "Blue winter silence held beside a low scarlet hearth.",
    density: "cinematic-calm",
    radius: 0.5,
    motionSpeed: 0.5,
  },
  {
    id: "modernia-ark-greenhouse",
    name: "Modernia · Ark Greenhouse",
    asset: "assets/nikke/modernia-ark-greenhouse.webp",
    themeId: "ark-scarlet",
    packName: "MODERNIA // Ark Greenhouse",
    description: "Soft glasshouse daylight across graphite-gold machinery.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.5,
  },
  {
    id: "shiroko-abydos-bike-dawn",
    name: "Shiroko · Abydos Bike Dawn",
    asset: "assets/blue-archive/shiroko-abydos-bike-dawn.webp",
    themeId: "academy-blue-hour",
    packName: "ABYDOS // Bike Dawn",
    description: "Cyan morning air over an open desert-school rooftop.",
    density: "cinematic-calm",
    radius: 0.75,
    motionSpeed: 0.75,
  },
  {
    id: "mika-trinity-rain-courtyard",
    name: "Mika · Trinity Rain Courtyard",
    asset: "assets/blue-archive/mika-trinity-rain-courtyard.webp",
    themeId: "academy-blue-hour",
    packName: "TRINITY // Rain Courtyard",
    description: "Pale violet rain and a softly rounded academy workspace.",
    density: "cinematic-calm",
    radius: 0.875,
    motionSpeed: 0.5,
  },
  {
    id: "zoya-syndicate-garage-dawn",
    name: "Zoya · Syndicate Garage Dawn",
    asset: "assets/path-to-nowhere/zoya-syndicate-garage-dawn.webp",
    themeId: "minos-noir",
    packName: "SYNDICATE // Garage Dawn",
    description: "Hard graphite structure cut by a single warm sunrise.",
    density: "tactical-compact",
    radius: 0.25,
    motionSpeed: 0.5,
  },
  {
    id: "cabernet-after-banquet",
    name: "Cabernet · After the Banquet",
    asset: "assets/path-to-nowhere/cabernet-after-banquet.webp",
    themeId: "minos-noir",
    packName: "CABERNET // After the Banquet",
    description: "Wine-red elegance in a quiet New City night kitchen.",
    density: "cinematic-calm",
    radius: 0.625,
    motionSpeed: 0.5,
  },
]

const assetBase = "/plugins/cognia-game-worlds-theme/"

const wallpapers = wallpaperSpecs.map(({ id, name, asset }) => ({
  id,
  name,
  source: {
    kind: "image",
    relPath: asset,
    mime: "image/webp",
    width: 1672,
    height: 941,
  },
}))

const densityPresets = [
  {
    name: "cinematic-calm",
    vars: {
      "--density-spacing": "1rem",
      "--density-input-height": "2.625rem",
      "--density-row-padding": "0.625rem",
      "--density-gap": "0.875rem",
      "--density-line-height": "1.6",
    },
  },
  {
    name: "tactical-compact",
    vars: {
      "--density-spacing": "0.75rem",
      "--density-input-height": "2.25rem",
      "--density-row-padding": "0.4375rem",
      "--density-gap": "0.625rem",
      "--density-line-height": "1.45",
    },
  },
]

const themePacks = wallpaperSpecs.map((spec) => ({
  id: spec.id,
  name: spec.packName,
  description: spec.description,
  preview: {
    light: `${assetBase}${spec.asset}`,
    dark: `${assetBase}${spec.asset}`,
  },
  applies: {
    themeId: spec.themeId,
    wallpaperId: spec.id,
    density: spec.density,
    radius: spec.radius,
    motionSpeed: spec.motionSpeed,
  },
}))

export const gameWorldsManifest = {
  ...baseManifest,
  themes: worldThemes,
  wallpapers,
  densityPresets,
  themePacks,
}

const definition: PluginDefinition = {
  manifest: gameWorldsManifest as never,
  activate: async (ctx: PluginContext) => {
    ctx.logger?.info("Game Worlds appearance contributions registered")
  },
  deactivate: async (ctx?: PluginContext) => {
    ctx?.logger?.info("Game Worlds appearance contributions removed")
  },
}

export default definition
