/**
 * QR pair payload (Wave 1.7).
 *
 * Encodes the data the mobile app needs to complete a one-shot pair:
 *   - `baseUrl`: where to reach the desktop server (LAN URL or tunnel URL)
 *   - `pairJwt`: the short-lived (5 min) pair JWT issued by `/auth/pair/issue`
 *   - `version`: server app version, used to gate breaking changes
 *   - `fingerprint`: SHA-256 of the server's TLS SubjectPublicKeyInfo (Wave 1.4)
 *
 * Encoding: JSON → base64url (no padding) so the payload is QR-friendly.
 * The QR code itself is generated by `qrcode.react` on the desktop side.
 */

import { Buffer } from "buffer"

export interface PairPayload {
  baseUrl: string
  pairJwt: string
  version: string
  /** Lower-case hex SHA-256 of the server's TLS SPKI. May be empty if TLS
   *  isn't enabled (legacy / debug). */
  fingerprint: string
}

const PAYLOAD_VERSION = 2 as const
const HEADER = `cgnp${PAYLOAD_VERSION}|`

function toBase64Url(input: string): string {
  // jsdom + node both expose Buffer; in Node browser bundles `buffer` is
  // imported above for parity.
  return Buffer.from(input, "utf8")
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "")
}

function fromBase64Url(input: string): string {
  const padding = (4 - (input.length % 4)) % 4
  const padded = input.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat(padding)
  return Buffer.from(padded, "base64").toString("utf8")
}

export function encodePairPayload(payload: PairPayload): string {
  const json = JSON.stringify({
    base: payload.baseUrl,
    jwt: payload.pairJwt,
    ver: payload.version,
    fp: payload.fingerprint,
  })
  return HEADER + toBase64Url(json)
}

export type DecodeOutcome =
  | { kind: "ok"; payload: PairPayload }
  | { kind: "wrong_format" }
  | { kind: "version_mismatch"; got: number }
  | { kind: "invalid"; message: string }

export function decodePairPayload(raw: string): DecodeOutcome {
  // Allow either the `cgnp2|...` form or a bare base64url for backwards
  // compatibility with the M3.4 textbox stub which used JSON-only.
  const trimmed = raw.trim()

  if (trimmed.startsWith("cgnp")) {
    const match = /^cgnp(\d+)\|(.+)$/.exec(trimmed)
    if (!match) return { kind: "wrong_format" }
    const version = Number.parseInt(match[1], 10)
    if (version !== PAYLOAD_VERSION) {
      return { kind: "version_mismatch", got: version }
    }
    return parseBody(match[2])
  }

  // Legacy (M3.4): bare JSON object pasted into the textbox.
  if (trimmed.startsWith("{")) {
    return parseLegacyJson(trimmed)
  }

  // Or bare base64url with no header.
  return parseBody(trimmed)
}

function parseBody(b64url: string): DecodeOutcome {
  let json: string
  try {
    json = fromBase64Url(b64url)
  } catch (err: unknown) {
    return { kind: "invalid", message: err instanceof Error ? err.message : String(err) }
  }
  return parseLegacyJson(json)
}

function parseLegacyJson(jsonText: string): DecodeOutcome {
  let parsed: unknown
  try {
    parsed = JSON.parse(jsonText)
  } catch (err: unknown) {
    return { kind: "invalid", message: err instanceof Error ? err.message : String(err) }
  }
  if (!parsed || typeof parsed !== "object") {
    return { kind: "invalid", message: "payload is not an object" }
  }
  const obj = parsed as Record<string, unknown>
  const baseUrl = pickString(obj, ["base", "baseUrl"])
  const pairJwt = pickString(obj, ["jwt", "pairJwt"])
  const version = pickString(obj, ["ver", "version"]) ?? ""
  const fingerprint = pickString(obj, ["fp", "fingerprint"]) ?? ""
  if (!baseUrl || !pairJwt) {
    return { kind: "invalid", message: "missing baseUrl or pairJwt" }
  }
  return {
    kind: "ok",
    payload: { baseUrl, pairJwt, version, fingerprint },
  }
}

function pickString(obj: Record<string, unknown>, keys: string[]): string | undefined {
  for (const k of keys) {
    const v = obj[k]
    if (typeof v === "string" && v.length > 0) return v
  }
  return undefined
}
