/** @jest-environment jsdom */

import { getDb } from "@/lib/db/schema"
import { createDbTestFixture } from "@/lib/db/test-fixture"
import { formatContextSelectionsForLLM } from "@/lib/artifacts/format-selection-context"
import { citationsForSelections } from "@/lib/chat/mentions/selection-citations"
import { isEntitySelectionStale } from "@/lib/chat/mentions/entity-sources"
import type { EntitySelectionRef } from "@/types/artifact/artifact"
import {
  buildMessageExcerptSelection,
  comparableExcerptText,
  loadMessageBodies,
  messageExcerptHref,
  refreshMessageExcerpt,
} from "./message-excerpt"

jest.setTimeout(30_000)

const dbFixture = createDbTestFixture()
beforeAll(dbFixture.initialize)
beforeEach(async () => {
  await dbFixture.restore()
  await getDb().messages.clear()
})
afterAll(dbFixture.dispose)

async function seed(
  id: string,
  text: string,
  { sessionId = "s1", role = "assistant", createdAt = 1 } = {}
) {
  await getDb().messages.put({
    id,
    sessionId,
    projectId: "p",
    role,
    parts: [{ type: "text", text }],
    createdAt,
  } as never)
}

async function edit(id: string, text: string) {
  await getDb().messages.update(id, { parts: [{ type: "text", text }] } as never)
}

type Excerpt = EntitySelectionRef & { excerpt: NonNullable<EntitySelectionRef["excerpt"]> }

describe("buildMessageExcerptSelection", () => {
  it("stages a quote as a message reference that names the part, not the message", async () => {
    await seed("m1", "Run **pnpm build** before tagging. Then push.")
    const sel = await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["m1"],
      text: "Run pnpm build before tagging.",
      excerpt: { derivation: "quote", quote: "Run pnpm build before tagging." },
      capturedAt: 5,
    })
    expect(sel).toMatchObject({
      kind: "entity",
      entityKind: "message",
      entityId: "s1#m1",
      title: "Run pnpm build before tagging.",
      capturedAt: 5,
      href: messageExcerptHref("s1", "m1"),
      sourceSessionId: "s1",
      excerpt: { derivation: "quote" },
    })
    // Transcript text is untrusted like any other message body.
    expect(sel!.snapshot).toContain("[Untrusted content below")
    expect(sel!.snapshot).toContain("Run pnpm build before tagging.")
    expect(sel!.fingerprint).toEqual(expect.any(String))
    expect(sel!.members).toBeUndefined()
  })

  it("names every message a selection runs across, in order, and cites each", async () => {
    await seed("m1", "the question", { role: "user", createdAt: 1 })
    await seed("m2", "the answer", { createdAt: 2 })
    const sel = await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["m1", "m2", "m1"],
      text: "question\nthe answer",
      excerpt: { derivation: "quote", quote: "question\nthe answer" },
    })
    expect(sel!.members).toEqual([
      { entityId: "s1#m1", title: "user: the question", href: messageExcerptHref("s1", "m1") },
      { entityId: "s1#m2", title: "assistant: the answer", href: messageExcerptHref("s1", "m2") },
    ])
    expect(citationsForSelections([sel!]).map((ref) => ref.id)).toEqual([
      "message:s1#m1",
      "message:s1#m2",
    ])
  })

  it("stages a generated body under the text it was generated from", async () => {
    await seed("m1", "a long passage about caching")
    const sel = await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["m1"],
      text: "Caching, briefly.",
      excerpt: { derivation: "summary", quote: "a long passage about caching" },
    })
    expect(sel!.title).toBe("a long passage about caching")
    expect(sel!.snapshot).toContain("Caching, briefly.")
    expect(formatContextSelectionsForLLM([sel!], { sessionId: "s1" })).toContain(
      "A summary, generated by the app, of text the user selected from a message earlier in this conversation"
    )
  })

  // A message still streaming may not be stored yet. Recording its absence would
  // flag the chip stale the moment the row lands.
  it("stores no fingerprint for a message that is not stored yet", async () => {
    const sel = await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["live-tail"],
      text: "streaming words",
      excerpt: { derivation: "quote", quote: "streaming words" },
    })
    expect(sel).not.toBeNull()
    expect(sel).not.toHaveProperty("fingerprint")
    await expect(isEntitySelectionStale(sel!)).resolves.toBe(false)
  })

  it.each([
    ["no message", { messageIds: [] }],
    ["an empty body", { text: "   " }],
    ["an empty quote", { excerpt: { derivation: "quote" as const, quote: " " } }],
  ])("stages nothing for %s", async (_label, over) => {
    await seed("m1", "text")
    await expect(
      buildMessageExcerptSelection({
        sessionId: "s1",
        messageIds: ["m1"],
        text: "text",
        excerpt: { derivation: "quote", quote: "text" },
        ...over,
      })
    ).resolves.toBeNull()
  })
})

describe("loadMessageBodies", () => {
  it("reads the stored text of each message, in order", async () => {
    await seed("m1", "the question", { role: "user", createdAt: 1 })
    await seed("m2", "the answer", { createdAt: 2 })
    await expect(loadMessageBodies("s1", ["m2", "m1"])).resolves.toBe("the answer\n\nthe question")
  })

  it("is null when none of them is stored, so the caller can fall back", async () => {
    await expect(loadMessageBodies("s1", ["streaming"])).resolves.toBeNull()
    await expect(loadMessageBodies("s1", [])).resolves.toBeNull()
  })

  it("does not read a message from another conversation", async () => {
    await seed("m1", "private", { sessionId: "other" })
    await expect(loadMessageBodies("s1", ["m1"])).resolves.toBeNull()
  })
})

describe("staleness", () => {
  it("goes stale when any message the selection runs across is edited", async () => {
    await seed("m1", "first", { createdAt: 1 })
    await seed("m2", "second", { createdAt: 2 })
    const sel = await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["m1", "m2"],
      text: "first second",
      excerpt: { derivation: "quote", quote: "first second" },
    })
    await expect(isEntitySelectionStale(sel!)).resolves.toBe(false)
    await edit("m2", "second, corrected")
    await expect(isEntitySelectionStale(sel!)).resolves.toBe(true)
  })
})

describe("comparableExcerptText", () => {
  // A selection is copied off the rendered message; the row stores Markdown.
  it("reads rendered text and its Markdown source as the same words", () => {
    expect(comparableExcerptText("**Run** `pnpm build` — [docs](https://x.dev)")).toContain(
      comparableExcerptText("Run pnpm build — docs")
    )
  })

  it("keeps CJK text", () => {
    expect(comparableExcerptText("变量，名称")).toBe("变量名称")
  })
})

describe("refreshMessageExcerpt", () => {
  async function staged(text: string, quote = text): Promise<Excerpt> {
    return (await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["m1"],
      text,
      excerpt: { derivation: "quote", quote },
      capturedAt: 1,
    })) as Excerpt
  }

  it("keeps the body and re-captures the fingerprint when the selected text is still there", async () => {
    await seed("m1", "Keep the **cache warm**. Other words.")
    const sel = { ...(await staged("Keep the cache warm.")), stale: true }
    await edit("m1", "Keep the **cache warm**. Other words, reworded.")
    const outcome = await refreshMessageExcerpt(sel)
    expect(outcome.kind).toBe("current")
    if (outcome.kind !== "current") return
    expect(outcome.selection.snapshot).toBe(sel.snapshot)
    expect(outcome.selection).not.toHaveProperty("stale")
    expect(outcome.selection.fingerprint).not.toBe(sel.fingerprint)
    await expect(isEntitySelectionStale(outcome.selection)).resolves.toBe(false)
  })

  it("says the message changed when it no longer says what was selected", async () => {
    await seed("m1", "Keep the cache warm.")
    const sel = await staged("Keep the cache warm.")
    await edit("m1", "Let the cache go cold.")
    await expect(refreshMessageExcerpt(sel)).resolves.toEqual({ kind: "changed" })
  })

  it("says the message is gone when it was deleted", async () => {
    await seed("m1", "Keep the cache warm.")
    const sel = await staged("Keep the cache warm.")
    await getDb().messages.delete("m1")
    await expect(refreshMessageExcerpt(sel)).resolves.toEqual({ kind: "gone" })
  })

  it("checks a derived excerpt against the text it was generated from", async () => {
    await seed("m1", "The original passage.")
    const sel = (await buildMessageExcerptSelection({
      sessionId: "s1",
      messageIds: ["m1"],
      text: "Le passage original.",
      excerpt: { derivation: "translation", quote: "The original passage.", language: "fr" },
    })) as Excerpt
    const outcome = await refreshMessageExcerpt(sel)
    expect(outcome.kind).toBe("current")
  })
})
