#!/usr/bin/env node

import { execFileSync } from "node:child_process"
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = resolve(packageRoot, "../..")
const authorTypesPath = resolve(repoRoot, "crates/cognia-cli/assets/author-types.json")
const distPath = resolve(packageRoot, "dist")

const facadeEntries = {
  manifest: ["definePlugin"],
  context: [],
  events: ["SystemEvents"],
  hooks: [],
  permissions: [],
  extensions: ["CANONICAL_EXTENSION_POINTS", "EXTENSION_POINT_FORM_FACTORS"],
}

function runTsup() {
  execFileSync("pnpm", ["exec", "tsup"], {
    cwd: packageRoot,
    stdio: "inherit",
    env: {
      ...process.env,
      NODE_OPTIONS: "--max-old-space-size=12288",
    },
  })
}

function collectFacadeTypes(entry) {
  const source = readFileSync(resolve(packageRoot, `src/${entry}/index.ts`), "utf8")
  const names = new Set()
  for (const match of source.matchAll(/export\s+type\s*\{([\s\S]*?)\}\s+from/g)) {
    for (const part of match[1].split(",")) {
      const name = part
        .replace(/\/\/.*$/gm, "")
        .trim()
        .split(/\s+as\s+/)
        .pop()
      if (name && /^[A-Za-z_$][\w$]*$/.test(name)) names.add(name)
    }
  }
  for (const match of source.matchAll(/export\s+(?:type|interface)\s+([A-Za-z_$][\w$]*)/g)) {
    names.add(match[1])
  }
  return [...names].sort()
}

runTsup()

const authorTypes = JSON.parse(readFileSync(authorTypesPath, "utf8"))
const rootDeclaration = authorTypes.files?.["types/cognia-plugin-sdk.d.ts"]
if (typeof rootDeclaration !== "string" || rootDeclaration.length === 0) {
  throw new Error(`Missing plugin SDK declaration in ${authorTypesPath}`)
}
writeFileSync(resolve(distPath, "index.d.ts"), rootDeclaration)

for (const entry of [
  "contracts",
  "templates",
  "connector",
  "integration",
  "context-panel",
  "editor",
  "webview",
]) {
  writeFileSync(
    resolve(distPath, `${entry}.d.ts`),
    `// Generated by packages/plugin-sdk/scripts/build-package.mjs.\nexport * from "./index.js"\n`
  )
}

for (const [entry, values] of Object.entries(facadeEntries)) {
  const types = collectFacadeTypes(entry)
  const lines = ["// Generated by packages/plugin-sdk/scripts/build-package.mjs."]
  if (types.length > 0) lines.push(`export type { ${types.join(", ")} } from "./index.js"`)
  if (values.length > 0) lines.push(`export { ${values.join(", ")} } from "./index.js"`)
  writeFileSync(resolve(distPath, `${entry}.d.ts`), `${lines.join("\n")}\n`)
}
