#!/usr/bin/env node

import { execFileSync } from "node:child_process"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = resolve(packageRoot, "../..")
const authorTypesPath = resolve(repoRoot, "crates/cognia-cli/assets/author-types.json")
const distPath = resolve(packageRoot, "dist")

const facadeEntries = {
  manifest: ["definePlugin"],
  context: [],
  events: ["SystemEvents"],
  hooks: [],
  permissions: [],
  extensions: ["CANONICAL_EXTENSION_POINTS", "EXTENSION_POINT_FORM_FACTORS"],
}

function runTsup() {
  execFileSync("pnpm", ["exec", "tsup"], {
    cwd: packageRoot,
    stdio: "inherit",
    env: {
      ...process.env,
      NODE_OPTIONS: "--max-old-space-size=16384",
    },
  })
}

function collectFacadeTypes(entry) {
  const source = readFileSync(resolve(packageRoot, `src/${entry}/index.ts`), "utf8")
  const names = new Set()
  for (const match of source.matchAll(/export\s+type\s*\{([\s\S]*?)\}\s+from/g)) {
    for (const part of match[1].split(",")) {
      const name = part
        .replace(/\/\/.*$/gm, "")
        .trim()
        .split(/\s+as\s+/)
        .pop()
      if (name && /^[A-Za-z_$][\w$]*$/.test(name)) names.add(name)
    }
  }
  for (const match of source.matchAll(/export\s+(?:type|interface)\s+([A-Za-z_$][\w$]*)/g)) {
    names.add(match[1])
  }
  return [...names].sort()
}

runTsup()

const authorTypes = JSON.parse(readFileSync(authorTypesPath, "utf8"))
const rootDeclaration = authorTypes.files?.["types/cognia-plugin-sdk.d.ts"]
if (typeof rootDeclaration !== "string" || rootDeclaration.length === 0) {
  throw new Error(`Missing plugin SDK declaration in ${authorTypesPath}`)
}
writeFileSync(resolve(distPath, "index.d.ts"), rootDeclaration)

for (const [entry, values] of Object.entries({
  abort: ["combineAbortSignals"],
  download: ["downloadBlob"],
})) {
  writeFileSync(
    resolve(distPath, `${entry}.d.ts`),
    `// Generated by packages/plugin-sdk/scripts/build-package.mjs.\nexport { ${values.join(", ")} } from "./index.js"\n`
  )
}

for (const entry of [
  "contracts",
  "templates",
  "connector",
  "integration",
  "context-panel",
  "editor",
  "webview",
]) {
  writeFileSync(
    resolve(distPath, `${entry}.d.ts`),
    `// Generated by packages/plugin-sdk/scripts/build-package.mjs.\nexport * from "./index.js"\n`
  )
}

for (const [entry, values] of Object.entries(facadeEntries)) {
  const types = collectFacadeTypes(entry)
  const lines = ["// Generated by packages/plugin-sdk/scripts/build-package.mjs."]
  if (types.length > 0) lines.push(`export type { ${types.join(", ")} } from "./index.js"`)
  if (values.length > 0) lines.push(`export { ${values.join(", ")} } from "./index.js"`)
  writeFileSync(resolve(distPath, `${entry}.d.ts`), `${lines.join("\n")}\n`)
}

// Declared rather than re-exported, because this is the one subpath whose
// surface is deliberately NOT on the root barrel: publishing these two from
// there would pull the settings and agent-runtime stores into the module graph
// of every plugin that imports a type. `export * from "./index.js"`, the
// fallback the entries above use, would therefore emit a declaration missing
// exactly the two names an author came here for, which is worse than no
// declaration at all.
writeFileSync(
  resolve(distPath, "effort-surface.d.ts"),
  [
    "// Generated by packages/plugin-sdk/scripts/build-package.mjs.",
    'import type { EffortSurface } from "./index.js"',
    'export type { EffortSurface, EffortSurfaceInput } from "./index.js"',
    "export declare function effortSurfaceForSession(",
    "  session: { id: string; model?: string; providerOverride?: string } | null | undefined",
    "): EffortSurface",
    "export declare function subscribeEffortSurface(",
    "  sessionId: string | undefined,",
    "  listener: () => void",
    "): () => void",
    "",
  ].join("\n")
)

/**
 * Say which subpaths ship without types.
 *
 * `tsup` runs with `dts: false`, so every declaration under `dist/` is one of
 * the ones written above. The `exports` map names a `types` file for all ~49
 * subpaths, and most of them have never had one: a warning rather than a throw
 * because closing that gap means auditing each surface (several are NOT
 * subsets of the root barrel, as the entry above shows), and failing the
 * package build on inherited debt helps nobody. What it does buy is that the
 * next subpath added without a declaration says so at build time.
 */
const packageJson = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"))
const untyped = Object.entries(packageJson.exports ?? {})
  .map(([subpath, conditions]) => [subpath, conditions?.types])
  .filter(([, types]) => typeof types === "string" && types.endsWith(".d.ts"))
  .filter(([, types]) => !existsSync(resolve(packageRoot, types)))
if (untyped.length > 0) {
  console.warn(
    `[plugin-sdk] ${untyped.length} subpath(s) declare a types file that was not generated:\n` +
      untyped.map(([subpath, types]) => `  ${subpath} -> ${types}`).join("\n")
  )
}
