// Build the Cognia Managed IDE Broker extension and package it as a .vsix.
//
//   1. esbuild-bundle `src/extension.mjs` → `dist/extension.js` (CJS, `vscode`
//      external — the host provides it at runtime).
//   2. Assemble a VSIX (a ZIP in the Open Packaging Conventions layout that
//      `code-server --install-extension` accepts) with `vsix-zip.mjs`.
//
// The produced `.vsix` is a build artifact, not a committed one: it is shipped
// as a Tauri resource (`src-tauri/tauri.conf.json` → `bundle.resources`), so
// `beforeDevCommand` / `beforeBuildCommand` run this before the resource walk,
// and `pnpm dev:headless` runs it too. `codeserver::process` side-loads the
// result on first spawn.

import { build } from "esbuild"
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { buildZip } from "./vsix-zip.mjs"

const root = dirname(fileURLToPath(import.meta.url))
const dist = join(root, "dist")
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"))
// Stable filename (version lives inside the manifest) so bumping the extension
// version never churns the Tauri resource path or the Rust install constant.
const vsixName = "cognia-managed-broker.vsix"
const vsixPath = join(root, vsixName)

// 1. Bundle.
rmSync(dist, { recursive: true, force: true })
mkdirSync(dist, { recursive: true })
await build({
  entryPoints: [join(root, "src/extension.mjs")],
  outfile: join(dist, "extension.js"),
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  // `vscode` is injected by the extension host; never bundle it.
  external: ["vscode"],
  legalComments: "none",
})
await build({
  entryPoints: [join(root, "src/proxy-extension.mjs")],
  outfile: join(dist, "proxy.js"),
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  external: ["vscode"],
  legalComments: "none",
})

// 2. Assemble the VSIX.
//
// Built in memory from an explicit part list rather than staged to disk and
// walked: the set is fixed, and naming it here is what makes the archive's
// contents and their order reviewable in one place. `[Content_Types].xml`
// leads, as the OPC layout expects.
//
// The localization bundles travel inside the package. The workbench reads them
// BEFORE activating the extension to substitute the manifest's `%key%`
// placeholders, so leaving them out silently ships the raw keys to every
// non-English user. Generated by `scripts/i18n/build-vscode-nls.mjs` (part of
// `pnpm i18n:build`), and a missing one is fatal rather than skipped: the
// default bundle is what every unmatched locale falls back to.
const nlsFiles = ["package.nls.json", "package.nls.zh-cn.json"]
for (const name of nlsFiles) {
  if (!existsSync(join(root, name))) {
    throw new Error(`${name} is missing — run \`pnpm i18n:build\` before packaging`)
  }
}

const parts = [
  { name: "[Content_Types].xml", data: Buffer.from(contentTypes(), "utf8") },
  { name: "extension.vsixmanifest", data: Buffer.from(vsixManifest(pkg), "utf8") },
  { name: "extension/package.json", data: readFileSync(join(root, "package.json")) },
  ...nlsFiles.map((name) => ({ name: `extension/${name}`, data: readFileSync(join(root, name)) })),
  { name: "extension/dist/extension.js", data: readFileSync(join(dist, "extension.js")) },
  { name: "extension/dist/proxy.js", data: readFileSync(join(dist, "proxy.js")) },
]

writeFileSync(vsixPath, buildZip(parts))

console.log(`built ${vsixName}`)

function vsixManifest(pkg) {
  const engine = pkg.engines?.vscode ?? "^1.80.0"
  return `<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="${pkg.name}" Version="${pkg.version}" Publisher="${pkg.publisher}" />
    <DisplayName>${pkg.displayName}</DisplayName>
    <Description xml:space="preserve">${pkg.description}</Description>
    <Tags>cognia</Tags>
    <Categories>Other</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Properties>
      <Property Id="Microsoft.VisualStudio.Code.Engine" Value="${engine}" />
      <Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="" />
    </Properties>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code" />
  </Installation>
  <Dependencies />
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
  </Assets>
</PackageManifest>
`
}

function contentTypes() {
  return `<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json" />
  <Default Extension="js" ContentType="application/javascript" />
  <Default Extension="vsixmanifest" ContentType="text/xml" />
</Types>
`
}
