apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognia-diagnostics.fullname" . }}
  labels:
    {{- include "cognia-diagnostics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cognia-diagnostics.selectorLabels" . | nindent 4 }}
