/**
 * Host-owned storage contract for external-agent configurations.
 *
 * Today a configuration lives in the renderer's `localStorage` (the
 * `cognia-external-agents` zustand slice). That works while the only thing
 * running an agent is the same renderer that owns the settings page. It breaks
 * the moment a browser Composer asks a paired brain to run one: the browser
 * holds the configuration, the brain holds the process, and nothing reconciles
 * them — so the brain would be handed a config blob per turn and could not
 * check that the thing it is about to spawn is still the thing the user
 * approved.
 *
 * So the selected host owns them, in its own database, as a head plus an
 * append-only revision log:
 *
 *   - A **revision** is immutable. Once written it is never edited, because a
 *     run that has been admitted holds a lease on exactly one of them; that is
 *     what makes "the config did not change under a running turn" checkable
 *     rather than hoped for.
 *   - A **head** names the current revision. Updates compare-and-swap it, so
 *     two editors cannot silently overwrite each other — the loser is told.
 *   - `lifecycleGeneration` moves on a **readiness** change only (enabled,
 *     credentials, runtime), never on an ordinary text edit. The two are
 *     genuinely different questions: a revision proves the configuration is
 *     unchanged, the generation proves it is still runnable. A single counter
 *     would force a rename to invalidate an in-flight admission for no reason,
 *     and a single revision check would let a revoked credential through.
 *   - A delete **tombstones** the head instead of dropping it. Leases and
 *     audit outlive the configuration, and a reused id would let a stale
 *     admission address a different agent entirely — which is why ids are
 *     generated here and never reused.
 *
 * Readiness vocabulary is NOT redefined here. `ExternalAgentLifecycleStatus`
 * already distinguishes `needs-credentials` / `needs-consent` / `needs-runtime`
 * / `blocked` from `ready`, and the reconciliation that produces those verdicts
 * already exists in `lib/ai/agent/external/lifecycle/`. A second, parallel set
 * of readiness strings would be two sources of truth for one question.
 */

import type { StoredExternalAgentConfig } from "@/stores/agent/external-agent-store/types"
import type { ExternalAgentLifecycleStatus } from "@/types/agent/external-agent-lifecycle"

/** `eac_<random>` — generated by the owning host, never reused after a delete. */
export type ExternalAgentConfigId = string

/** `eacr_<random>` — identifies one immutable revision. */
export type ExternalAgentConfigRevisionId = string

/**
 * One immutable snapshot of a configuration.
 *
 * The stored config is already credential-scrubbed: secrets live in the
 * keyring behind `credentialRefs`, and `scrubInlineCredentials` is what puts
 * them there. A revision must never be the thing that reintroduces an inline
 * secret, because revisions are retained for as long as a run references them.
 */
export interface ExternalAgentConfigRevisionRow {
  revisionId: ExternalAgentConfigRevisionId
  configId: ExternalAgentConfigId
  /** Monotonic per configuration; `1` is the create. */
  seq: number
  config: StoredExternalAgentConfig
  createdAt: number
  /**
   * Run ids currently pinning this revision. A revision is collectable only
   * when this is empty AND it is no longer the head AND it is past retention.
   * Indexed multi-entry so a run's leases can be released without a scan.
   */
  leaseRuns: string[]
}

/** The current state of one configuration. */
export interface ExternalAgentConfigHeadRow {
  configId: ExternalAgentConfigId
  /** The revision this configuration currently resolves to. CAS target. */
  revision: ExternalAgentConfigRevisionId
  /** Incremented on a readiness change only. See the module header. */
  lifecycleGeneration: number
  /** Set by a delete. A tombstoned head is never resolved for a new run. */
  tombstonedAt?: number
  createdAt: number
  updatedAt: number
}

/** A head joined to the revision it points at — what callers actually read. */
export interface ExternalAgentConfigRecord {
  configId: ExternalAgentConfigId
  revision: ExternalAgentConfigRevisionId
  lifecycleGeneration: number
  seq: number
  config: StoredExternalAgentConfig
  /** Convenience projections of the resolved config, never stored separately. */
  enabled: boolean
  lifecycleStatus: ExternalAgentLifecycleStatus
  tombstonedAt?: number
  createdAt: number
  updatedAt: number
}

/**
 * What a run must present to be admitted.
 *
 * Both halves are required and both are checked. A caller that knew only the
 * revision could be admitted against a configuration whose credentials were
 * revoked a moment ago; a caller that knew only the generation could be
 * admitted against text it never saw.
 */
export interface ExternalAgentConfigStamp {
  configId: ExternalAgentConfigId
  revision: ExternalAgentConfigRevisionId
  lifecycleGeneration: number
}

/** Why an admission or a compare-and-swap was refused. */
export const EXTERNAL_AGENT_CONFIG_REJECTIONS = [
  /** No head with that id — or it was never on this host. */
  "unknown-config",
  /** The head is tombstoned; the configuration was deleted. */
  "deleted",
  /** The caller's revision is not the head's. Someone edited it. */
  "stale-revision",
  /** The revision matches but readiness moved (disabled, credential revoked). */
  "stale-generation",
  /** Resolved, but the configuration is disabled. */
  "disabled",
  /** Resolved and enabled, but reconciliation says it cannot run yet. */
  "not-ready",
] as const

export type ExternalAgentConfigRejection = (typeof EXTERNAL_AGENT_CONFIG_REJECTIONS)[number]

/** Admission verdict. `ok` carries the immutable revision the run will use. */
export type ExternalAgentConfigAdmission =
  | { ok: true; record: ExternalAgentConfigRecord }
  | {
      ok: false
      reason: ExternalAgentConfigRejection
      /** The current record, when one exists — lets a caller retry informed. */
      current?: ExternalAgentConfigRecord
    }
