import type { MetadataRoute } from "next"

/**
 * Web App Manifest (Wave 4 / ADR-0026).
 *
 * Next.js's metadata-based manifest API generates `manifest.webmanifest`
 * at build time. Pairs with the Serwist SW (see `app/sw.ts`) so the
 * browser can offer "Install Cognia" on web and the desktop Tauri shell
 * gets a manifest for completeness.
 *
 * Icons live under `public/icons/` (192/512 standard + 512 maskable),
 * rasterised from `mobile/resources/splash.png` — the same source that
 * feeds the desktop (`src-tauri/icons/`) and Android (`mipmap-*`) icons.
 * The Apple Touch Icon is served via the Next.js `app/apple-icon.png`
 * file convention and the favicon via `app/favicon.ico`.
 */
// Required by Next.js 16 when `output: "export"` is set in next.config.ts —
// the manifest returns a fully static object so we opt in explicitly.
export const dynamic = "force-static"

export default function manifest(): MetadataRoute.Manifest {
  return {
    // Explicit identity: without `id`, Chrome derives the app identity from
    // `start_url`, so any later start_url change would orphan every existing
    // install (a "new" app, fresh storage partition).
    id: "/",
    name: "Cognia",
    short_name: "Cognia",
    description: "Local-first AI companion — chat, workflows, twin, and connectors.",
    // Single static manifest → single language. The UI itself is en/zh-CN via
    // next-intl; per-locale manifests would need a route per locale, which is
    // not worth it for install-dialog copy.
    lang: "en",
    dir: "ltr",
    categories: ["productivity", "utilities"],
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#0a0a0a",
    // A chat app should never spawn a second standalone window per launch —
    // shortcuts/deep links re-focus the running one instead.
    launch_handler: { client_mode: "focus-existing" },
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/icons/icon-512-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Icon context-menu entries (right-click dock/taskbar icon, long-press on
    // Android). Deep links into routes that exist in the static export.
    shortcuts: [
      {
        name: "New chat",
        url: "/",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Inbox",
        url: "/inbox",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
    ],
    // Rich install dialog on Chrome desktop/Android requires description +
    // screenshots. PNGs are generated by `pnpm screenshots:pwa`
    // (scripts/screenshots/capture-pwa-screenshots.mjs) into public/pwa/.
    screenshots: [
      {
        src: "/pwa/screenshots/chat-wide.png",
        sizes: "1280x800",
        type: "image/png",
        form_factor: "wide",
        label: "Multi-agent chat workspace",
      },
      {
        src: "/pwa/screenshots/chat-narrow.png",
        sizes: "750x1334",
        type: "image/png",
        form_factor: "narrow",
        label: "Chat on the go",
      },
    ],
    // Registered on install: `web+cognia://...` links open the PWA, which
    // rewrites them into `cognia://` and hands them to the same plugin URI
    // dispatch the Tauri deep link uses (`app/deep-link/page.tsx`).
    protocol_handlers: [{ protocol: "web+cognia", url: "/deep-link?u=%s" }],
    // Web Share Target. `app/share-target/page.tsx` has existed since Wave 3
    // with a full session picker, but only the Android native SEND intent
    // could ever reach it: `MainActivity` rewrites that intent into a
    // `cognia://share` deep link. An installed web PWA had no route in at all,
    // so the page was unreachable for every browser user.
    //
    // `method: "GET"` is forced, not chosen. A POST target needs a server to
    // receive the form, and this app is a Next.js static export with no
    // `app/api/` at runtime. GET puts the payload in the query string, which
    // is exactly what the page already reads.
    share_target: {
      action: "/share-target",
      method: "GET",
      params: {
        title: "title",
        text: "text",
        url: "url",
      },
    },
  }
}
