/**
 * `@msg:` — one message from another conversation, optionally with the turns
 * around it.
 *
 * The granularity `@chat:` could not express. A conversation reference stages
 * the tail of a whole session with tool outputs dropped; the thing people
 * actually want to reuse is usually one exchange, and frequently the thing a
 * tool returned inside it. So this projection is the mirror image of the search
 * one: narrow in scope, complete in body.
 *
 * Identity is `<sessionId>#<messageId>`, not a bare message id. A message id is
 * unique in this database, but the reference has to survive round-tripping
 * through `EntitySelectionRef.entityId` and a `ContextRef`, and both of those
 * are read by things that need the owning conversation without a second lookup
 * — the chip's link, the permalink in the prompt, the backlink index.
 */

import type { UIMessage } from "ai"
import { normalizeToolName, type ToolPartLike } from "@/lib/chat/tool-summary"
import { promptPreambleOfParts, stripPromptPreambleFromParts } from "@/lib/chat/prompt-preamble"
import { isToolPart, projectToolOutputText } from "./tool-output-text"

export { contentFingerprint } from "./content-fingerprint"

/**
 * Separator between the session and the message in a `@msg:` id.
 *
 * `#` because that is what the permalink fragment convention already implies
 * and because neither id contains one.
 */
export const MESSAGE_REF_SEPARATOR = "#"

/**
 * Turns reachable on each side of the anchor.
 *
 * A span is for "this exchange", not "this conversation" — `@chat:` is right
 * there for the latter, and a wide span would silently become a worse version
 * of it (no dedupe against the current transcript, and the 20k clamp cutting an
 * arbitrary conversation in half).
 */
export const MAX_MESSAGE_SPAN = 10

export interface MessageSpan {
  /** Messages before the anchor. */
  before: number
  /** Messages after it. */
  after: number
}

export const NO_SPAN: MessageSpan = { before: 0, after: 0 }

export function messageRefId(sessionId: string, messageId: string): string {
  return `${sessionId}${MESSAGE_REF_SEPARATOR}${messageId}`
}

/**
 * Split a `@msg:` id back into its two halves, or null when it is not one.
 *
 * Split on the FIRST separator: the session id is generated by this app and
 * never contains one, while a message id from an imported transcript is
 * whatever the exporting tool chose.
 */
export function parseMessageRefId(id: string): { sessionId: string; messageId: string } | null {
  const at = id.indexOf(MESSAGE_REF_SEPARATOR)
  if (at <= 0 || at === id.length - 1) return null
  return { sessionId: id.slice(0, at), messageId: id.slice(at + 1) }
}

/** Clamp a span to what the picker is allowed to ask for. */
export function clampSpan(span: MessageSpan): MessageSpan {
  const bound = (n: number) => Math.max(0, Math.min(MAX_MESSAGE_SPAN, Math.trunc(n) || 0))
  return { before: bound(span.before), after: bound(span.after) }
}

interface BodyMessage {
  role: string
  parts: unknown
}

/** Longest tool input echoed into a reference. The output is what matters. */
export const REFERENCE_TOOL_INPUT_MAX_CHARS = 1_000

/**
 * Said in place of the context block a referenced user turn carried.
 *
 * The block is stripped because it is the app's framing, not the user's words —
 * and inlining another turn's references into this one would nest references
 * inside references. But silently dropping it would let the model read a
 * question like "compare these two" as if it had been asked about nothing.
 */
export const REFERENCE_PREAMBLE_OMITTED_NOTE =
  "[This message was sent with attached context, which is not included here.]"

function asString(value: unknown): string {
  return typeof value === "string" ? value : ""
}

function toolInputText(input: unknown): string {
  if (input === undefined || input === null) return ""
  if (typeof input === "string") return input.slice(0, REFERENCE_TOOL_INPUT_MAX_CHARS)
  try {
    const json = JSON.stringify(input)
    if (!json || json === "{}") return ""
    return json.length > REFERENCE_TOOL_INPUT_MAX_CHARS
      ? `${json.slice(0, REFERENCE_TOOL_INPUT_MAX_CHARS)}…`
      : json
  } catch {
    return ""
  }
}

/**
 * One part as a reference reads it.
 *
 * Not `projectSearchText`, which this used to be. That projection collapses all
 * whitespace (a search haystack has no use for newlines) and cuts each message
 * at 8k characters without saying so — both right for an index and both wrong
 * for text a model is asked to reason about: a code reply turned into one line,
 * and a long answer silently lost its end. The snapshot's own clamp
 * (`clampEntitySnapshot`) bounds the total and says when it cut.
 *
 * Reasoning is left out on purpose. It is the model's scratch work, frequently
 * longer than the answer, and the turn's conclusion is already in its text; the
 * message "quote" action has always excluded it for the same reason.
 */
export function projectReferencePart(part: unknown): string {
  if (!part || typeof part !== "object") return ""
  const p = part as Record<string, unknown>
  switch (p.type) {
    case "text":
      return asString(p.text).trim()
    case "markdown":
      return asString(p.md).trim()
    case "code": {
      const text = asString(p.text) || asString(p.code)
      const language = asString(p.language)
      return text ? `\`\`\`${language}\n${text}\n\`\`\`` : ""
    }
    case "image": {
      const alt = asString(p.alt)
      return alt ? `[image: ${alt}]` : "[image]"
    }
    case "file": {
      const name = asString(p.filename) || asString(p.mediaType) || "file"
      return `[attached file: ${name}]`
    }
    case "a2ui":
      return (asString(p.plainTextMirror) || asString(p.text)).trim()
    case "sources": {
      const sources = Array.isArray(p.sources) ? p.sources : []
      const lines = sources.flatMap((s) => {
        if (!s || typeof s !== "object") return []
        const { title, url } = s as { title?: unknown; url?: unknown }
        const label = asString(title) || asString(url)
        if (!label) return []
        return [asString(url) && asString(url) !== label ? `- ${label} (${url})` : `- ${label}`]
      })
      return lines.length > 0 ? `Sources:\n${lines.join("\n")}` : ""
    }
    default:
      if (isToolPart(p)) {
        const name = normalizeToolName(p as unknown as ToolPartLike)
        const input = toolInputText(p.input)
        return input ? `[tool ${name}] ${input}` : `[tool ${name}]`
      }
      return ""
  }
}

/**
 * One message as the model should read it: its readable parts plus every tool
 * output, in document order, newlines intact.
 *
 * The composer's context envelope is stripped from a user turn (see
 * {@link REFERENCE_PREAMBLE_OMITTED_NOTE} for why it is noted rather than
 * silently dropped).
 */
export function projectMessageBody(parts: unknown): string {
  if (!Array.isArray(parts)) return ""
  const hadPreamble = promptPreambleOfParts(parts) !== null
  const buf: string[] = []
  for (const part of stripPromptPreambleFromParts(parts)) {
    if (!part || typeof part !== "object") continue
    const readable = projectReferencePart(part)
    if (readable) buf.push(readable)
    if (isToolPart(part as { type?: unknown })) {
      const output = projectToolOutputText(part as { output?: unknown; state?: unknown })
      // Labelled, because the line above already contributed the tool name and
      // its arguments — without the label the two run together and the model
      // cannot tell what was asked from what came back.
      if (output) buf.push(`→ ${output}`)
    }
  }
  if (hadPreamble && buf.length > 0) buf.push(REFERENCE_PREAMBLE_OMITTED_NOTE)
  return buf.join("\n").trim()
}

/** Format the anchor plus its neighbours, marking which one was pointed at. */
export function formatMessageReference(
  messages: readonly BodyMessage[],
  anchorIndex: number
): string | null {
  const blocks: string[] = []
  for (const [index, message] of messages.entries()) {
    const body = projectMessageBody(message.parts)
    // A message that projects to nothing (an image with no alt, a tool call
    // still running) contributes an empty turn; skipping it beats padding the
    // block with blank role labels.
    if (!body) continue
    // The marker earns its place only when there is something to distinguish
    // the anchor FROM. On a bare single-message reference it would be noise.
    const marker = messages.length > 1 && index === anchorIndex ? " ← referenced message" : ""
    blocks.push(`${message.role}${marker}: ${body}`)
  }
  // Every message projected to nothing. Returning null makes the caller say the
  // record is unreadable instead of staging a chip that claims to carry one.
  return blocks.length > 0 ? blocks.join("\n\n") : null
}

export interface MessageReferenceInput {
  sessionId: string
  messageId: string
  span?: MessageSpan
}

/**
 * Load and format one message reference, or null when the message is gone.
 *
 * Re-read rather than cached: this is called again whenever the user widens the
 * span on the staged chip, and the widened body has to come from the same place
 * the first one did.
 *
 * The neighbour read is bounded by the span, so a `{0,0}` reference costs one
 * `get`. Only a widened one pages the session — and then only `span+1` rows on
 * each side, never the whole conversation.
 */
export async function buildMessageReferenceText({
  sessionId,
  messageId,
  span = NO_SPAN,
}: MessageReferenceInput): Promise<string | null> {
  const { getDb } = await import("@/lib/db/schema")
  const db = getDb()
  const anchor = await db.messages.get(messageId)
  if (!anchor || anchor.sessionId !== sessionId) return null

  const { before, after } = clampSpan(span)
  if (before === 0 && after === 0) {
    return formatMessageReference([{ role: anchor.role, parts: anchor.parts }], 0)
  }

  // Walk outwards on `[sessionId+createdAt]` from the anchor's own timestamp.
  // Bounds are inclusive of the anchor's instant on both sides because several
  // messages routinely share a millisecond; the anchor is filtered out of each
  // side by id rather than by time.
  const table = db.messages.where("[sessionId+createdAt]")
  const earlier =
    before > 0
      ? (
          await table
            .between([sessionId, 0], [sessionId, anchor.createdAt], true, true)
            .reverse()
            .limit(before + 1)
            .toArray()
        )
          .filter((row) => row.id !== messageId)
          .slice(0, before)
          .reverse()
      : []
  const later =
    after > 0
      ? (
          await table
            .between(
              [sessionId, anchor.createdAt],
              [sessionId, Number.MAX_SAFE_INTEGER],
              true,
              true
            )
            .limit(after + 1)
            .toArray()
        )
          .filter((row) => row.id !== messageId)
          .slice(0, after)
      : []

  const window = [...earlier, anchor, ...later]
  if (!window.some(hasBranchMetadata)) {
    return formatMessageReference(
      window.map((row) => ({ role: row.role, parts: row.parts })),
      earlier.length
    )
  }

  // The window touched an edited or regenerated turn. Its hidden siblings share
  // the timeline with the visible one, so a time-ordered walk would read "the
  // turn before" as a version the user never sees. Visibility can only be
  // decided over the whole conversation — a sibling's owner may sit outside the
  // window — so only this case pays for the full read.
  const [{ selectVisibleMessages, useChatStore }, rows] = await Promise.all([
    import("@/stores/chat/chat-store"),
    table.between([sessionId, 0], [sessionId, Number.MAX_SAFE_INTEGER], true, true).toArray(),
  ])
  const activeBranches = useChatStore.getState().sessions[sessionId]?.activeBranchByGroup ?? {}
  const visible = selectVisibleMessages(rows as unknown as UIMessage[], activeBranches)
  const at = visible.findIndex((row) => row.id === messageId)
  // The anchor is itself a hidden version (a search hit on an older answer).
  // Its own time-ordered neighbours are the honest context for it.
  if (at < 0) {
    return formatMessageReference(
      window.map((row) => ({ role: row.role, parts: row.parts })),
      earlier.length
    )
  }
  const start = Math.max(0, at - before)
  const slice = visible.slice(start, at + after + 1)
  return formatMessageReference(
    slice.map((row) => ({ role: row.role, parts: row.parts })),
    at - start
  )
}

function hasBranchMetadata(row: { metadata?: unknown }): boolean {
  const meta = row.metadata as { branchGroupId?: unknown; branchOwnerId?: unknown } | undefined
  return Boolean(meta && (meta.branchGroupId !== undefined || meta.branchOwnerId !== undefined))
}
