/** Generated by scripts/build/gen-companion-api.mjs. Do not edit. */
export const HEADLESS_CONTRACT_VERSION = 1 as const
export const HEADLESS_CATALOG_HASH = "a942067f9dc6bd35fe9ba76dc0f87c63c73b8c4f952719ea66d94d8dece7a3b9" as const
