/** Generated by scripts/build/gen-companion-api.mjs. Do not edit. */
export const HEADLESS_CONTRACT_VERSION = 3 as const
export const HEADLESS_CATALOG_HASH = "ba2986603a289589c9d38a137cf0b6d4a99712469bed791bcb5dcca71b93d3dd" as const
