/** Generated by scripts/build/gen-companion-api.mjs. Do not edit. */
export const HEADLESS_CONTRACT_VERSION = 1 as const
export const HEADLESS_CATALOG_HASH = "09534a7b036487068ae61397c95d7f2b0f9175647bc3802780619137a6101a56" as const
