import assert from "node:assert/strict"
import { mkdtemp, mkdir, readFile, readdir, rename, rm, symlink, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import test from "node:test"
import JSZip from "jszip"
import { devShellCache, installedDevShellMatches } from "./android-dev-shell.mjs"

async function fixture(t) {
  const root = await mkdtemp(path.join(os.tmpdir(), "cognia-dev-cache-"))
  t.after(() => rm(root, { recursive: true, force: true }))
  const put = async (name, value) => {
    const file = path.join(root, name)
    await mkdir(path.dirname(file), { recursive: true })
    await writeFile(file, value)
  }
  const env = {
    COGNIA_MOBILE_DEV_URL: "http://localhost:3002",
    JAVA_HOME: path.join(root, "jdk"),
    GRADLE_USER_HOME: path.join(root, "gradle-user"),
  }
  const config = {
    appId: "com.cognia.mobile",
    server: { url: env.COGNIA_MOBILE_DEV_URL, cleartext: true },
    android: { webContentsDebuggingEnabled: true },
  }
  await put(
    "mobile/package.json",
    JSON.stringify({ dependencies: { "local-plugin": "workspace:*" } })
  )
  await put("mobile/node_modules/local-plugin/android/src/Plugin.java", "native plugin")
  await put("mobile/android/app/src/main/java/MainActivity.java", "native")
  await put("mobile/android/app/src/main/assets/capacitor.config.json", JSON.stringify(config))
  const writeApk = async (override = config) => {
    const zip = new JSZip()
    zip.file("assets/capacitor.config.json", JSON.stringify(override))
    zip.file("assets/public/index.html", "<!-- Generated by Cognia Android dev workflow. -->hello")
    await put(
      "mobile/android/app/build/outputs/apk/debug/app-debug.apk",
      await zip.generateAsync({ type: "nodebuffer" })
    )
  }
  await writeApk()
  return {
    root,
    put,
    env,
    config,
    writeApk,
    cache: devShellCache(root, env, { javaVersion: "javac 21" }),
  }
}

test("sealed APK survives offline outputs and JS/CSS edits while verifying its own bytes", async (t) => {
  const { root, cache, put } = await fixture(t)
  const inputs = await cache.fingerprint()
  assert.equal(await cache.find(inputs), null)
  const record = await cache.save(inputs, await cache.generated())
  assert.deepEqual(await cache.find(inputs), record)
  await put("app/page.tsx", "updated UI")
  await put("app/globals.css", "updated CSS")
  assert.equal(await cache.fingerprint(), inputs)
  await put("mobile/android/app/build/reports/random", "new build report")
  assert.equal(await cache.fingerprint(), inputs)
  const serialized = await readFile(
    path.join(root, ".cache/mobile-dev-shell/manifest.json"),
    "utf8"
  )
  assert.equal(serialized.includes("localhost"), false)
  assert.equal(serialized.includes("javac"), false)
  await put("mobile/android/app/src/main/assets/capacitor.config.json", "offline config")
  await put("mobile/android/capacitor.settings.gradle", "offline sync output")
  await put("mobile/android/app/build/outputs/apk/debug/app-debug.apk", "offline APK")
  assert.deepEqual(await cache.find(inputs), record)
  assert.equal(await cache.fingerprint(), inputs)
  assert.notEqual(record.apk, cache.sourceApk)
  await rm(record.apk)
  assert.equal(await cache.find(inputs), null)
})

test("native source, plugin bytes, config, lockfile, toolchain, and port invalidate reuse", async (t) => {
  const { root, cache, env, put } = await fixture(t)
  let prior = await cache.fingerprint()
  for (const file of [
    "mobile/android/app/src/main/java/MainActivity.java",
    "mobile/node_modules/local-plugin/android/src/Plugin.java",
    "mobile/capacitor.config.ts",
    "pnpm-lock.yaml",
    "jdk/release",
    "gradle-user/gradle.properties",
  ]) {
    await put(file, "changed")
    const next = await cache.fingerprint()
    assert.notEqual(next, prior, file)
    prior = next
  }
  assert.notEqual(
    await devShellCache(
      root,
      { ...env, COGNIA_MOBILE_DEV_URL: "http://localhost:4000" },
      { javaVersion: "javac 21" }
    ).fingerprint(),
    prior
  )
  assert.notEqual(
    await devShellCache(root, env, { javaVersion: "javac 21.1" }).fingerprint(),
    prior
  )
})

test("SDK metadata, active API bytes, and Gradle environment changes invalidate reuse", async (t) => {
  const { root, env, put } = await fixture(t)
  const sdkEnv = { ...env, ANDROID_HOME: path.join(root, "sdk") }
  const cache = devShellCache(root, sdkEnv, { javaVersion: "javac 21" })
  await put("mobile/android/variables.gradle", "ext { compileSdkVersion = 36 }")
  let prior = await cache.fingerprint()
  for (const name of [
    "sdk/platforms/android-36/source.properties",
    "sdk/platforms/android-36/android.jar",
    "sdk/build-tools/36.0.0/source.properties",
  ]) {
    await put(name, "changed")
    const next = await cache.fingerprint()
    assert.notEqual(next, prior)
    prior = next
  }
  assert.notEqual(
    await devShellCache(
      root,
      { ...sdkEnv, ORG_GRADLE_PROJECT_test: "changed" },
      { javaVersion: "javac 21" }
    ).fingerprint(),
    prior
  )
  assert.notEqual(
    await devShellCache(
      root,
      { ...sdkEnv, JAVA_OPTS: "-Dtest=changed" },
      { javaVersion: "javac 21" }
    ).fingerprint(),
    prior
  )
})

test("default, configured, and legacy debug signing key changes invalidate reuse without exposing bytes", async (t) => {
  const { root, env, put } = await fixture(t)
  t.mock.method(os, "homedir", () => path.join(root, "user"))
  const signingEnv = {
    ...env,
    ANDROID_USER_HOME: path.join(root, "android-user"),
    ANDROID_PREFS_ROOT: path.join(root, "prefs-user"),
    ANDROID_SDK_HOME: path.join(root, "legacy-user"),
  }
  const cache = devShellCache(root, signingEnv, { javaVersion: "javac 21" })
  for (const file of [
    "user/.android/debug.keystore",
    "android-user/debug.keystore",
    "prefs-user/.android/debug.keystore",
    "legacy-user/.android/debug.keystore",
  ]) {
    const missing = await cache.fingerprint()
    await put(file, "synthetic-private-key-one")
    const initial = await cache.fingerprint()
    assert.notEqual(initial, missing, `${file}: created`)
    await cache.save(initial, await cache.generated())
    await put(file, "synthetic-private-key-two")
    const changed = await cache.fingerprint()
    assert.notEqual(changed, initial, `${file}: replaced`)
    assert.equal(await cache.find(changed), null)
    await rm(path.join(root, file))
    assert.equal(await cache.fingerprint(), missing, `${file}: removed`)
  }
  assert.equal(
    (await readFile(path.join(root, ".cache/mobile-dev-shell/manifest.json"), "utf8")).includes(
      "synthetic-private-key"
    ),
    false
  )
})

test("signing initialization detects only the selected key and leaves creation to Gradle", async (t) => {
  const { root, env, put } = await fixture(t)
  t.mock.method(os, "homedir", () => path.join(root, "user"))
  const base = devShellCache(root, env, { javaVersion: "javac 21" })
  assert.equal(await base.needsSigningKey(), true)
  await put("user/.android/debug.keystore", "default signer")
  assert.equal(await base.needsSigningKey(), false)
  for (const [variable, relative] of [
    ["ANDROID_USER_HOME", "direct"],
    ["ANDROID_PREFS_ROOT", "prefs"],
    ["ANDROID_SDK_HOME", "legacy"],
  ]) {
    const directory = path.join(root, relative)
    const cache = devShellCache(
      root,
      { ...env, [variable]: directory },
      { javaVersion: "javac 21" }
    )
    if (variable !== "ANDROID_USER_HOME") {
      assert.equal(await cache.needsSigningKey(), false, "missing legacy parent falls back")
      await mkdir(directory)
    }
    assert.equal(
      await cache.needsSigningKey(),
      true,
      "default signer cannot mask selected missing key"
    )
    const key = `${relative}/${variable === "ANDROID_USER_HOME" ? "" : ".android/"}debug.keystore`
    await put(key, "configured signer")
    assert.equal(await cache.needsSigningKey(), false)
    await rm(path.join(root, key))
    assert.equal(await cache.needsSigningKey(), true)
  }
})

test("cache refuses mixed source/generated builds and offline APKs", async (t) => {
  const { cache, put, config, writeApk } = await fixture(t)
  const before = await cache.fingerprint()
  const outputs = await cache.generated()
  await put("mobile/android/app/src/main/java/MainActivity.java", "concurrent edit")
  await assert.rejects(cache.save(before, outputs), /mixed-source/)
  const current = await cache.fingerprint()
  await put("mobile/android/app/src/main/assets/extra.txt", "concurrent generated edit")
  await assert.rejects(cache.save(current, outputs), /mixed-source/)
  await writeApk({ ...config, server: {} })
  await assert.rejects(cache.save(current, await cache.generated()), /expected live-reload shell/)
  assert.equal(await cache.find(current), null)
})

test("missing and corrupted records rebuild; APK-only modification invalidates valid record", async (t) => {
  const { root, cache, put } = await fixture(t)
  const inputs = await cache.fingerprint()
  const cached = await cache.save(inputs, await cache.generated())
  await writeFile(cached.apk, "tamper")
  assert.equal(await cache.find(inputs), null)
  for (const content of ["not JSON", "null", "[]", "{}", "42"]) {
    await put(".cache/mobile-dev-shell/manifest.json", content)
    assert.equal(await cache.find(inputs), null)
  }
  await rm(path.join(root, ".cache/mobile-dev-shell/manifest.json"))
  assert.equal(await cache.find(inputs), null)
})

test("old cache versions, wrong inputs, malformed hashes, and linked cached APKs refuse reuse", async (t) => {
  const { root, cache } = await fixture(t)
  const inputs = await cache.fingerprint()
  const cached = await cache.save(inputs, await cache.generated())
  const manifest = path.join(root, ".cache/mobile-dev-shell/manifest.json")
  const original = await readFile(manifest, "utf8")
  for (const change of [
    { version: 1 },
    { generated: "invalid" },
    { apkHash: "../../outside" },
    { inputs: "stale" },
  ]) {
    await writeFile(manifest, JSON.stringify({ ...JSON.parse(original), ...change }))
    assert.equal(await cache.find(inputs), null)
  }
  await writeFile(manifest, original)
  await rm(cached.apk)
  await symlink(cache.sourceApk, cached.apk)
  assert.equal(await cache.find(inputs), null)
})

test("publication keeps one APK and cleans owned orphan files without touching other files", async (t) => {
  const { root, cache, put, writeApk, config } = await fixture(t)
  const inputs = await cache.fingerprint()
  const first = await cache.save(inputs, await cache.generated())
  await put(".cache/mobile-dev-shell/readme.txt", "user note")
  await put(`.cache/mobile-dev-shell/${"a".repeat(64)}.apk`, "orphan")
  await put(".cache/mobile-dev-shell/.publish-abcd.apk.tmp", "interrupted write")
  const changed = { ...config, appName: "new native config" }
  await put("mobile/android/app/src/main/assets/capacitor.config.json", JSON.stringify(changed))
  await writeApk(changed)
  const second = await cache.save(inputs, await cache.generated())
  assert.notEqual(first.apk, second.apk)
  assert.deepEqual(await cache.find(inputs), second)
  assert.deepEqual(
    (await readdir(path.join(root, ".cache/mobile-dev-shell"))).sort(),
    [path.basename(second.apk), "manifest.json", "readme.txt"].sort()
  )
})

test("failed staging writes or manifest publication preserve the previous verified APK", async (t) => {
  const { root, cache, env, put, writeApk, config } = await fixture(t)
  const inputs = await cache.fingerprint()
  const first = await cache.save(inputs, await cache.generated())
  const changed = { ...config, appName: "new native config" }
  await put("mobile/android/app/src/main/assets/capacitor.config.json", JSON.stringify(changed))
  await writeApk(changed)
  for (const failure of ["write", "publish"]) {
    const faulty = devShellCache(
      root,
      env,
      { javaVersion: "javac 21" },
      {
        writeFile: async (...args) => {
          if (failure === "write" && String(args[0]).endsWith(".json.tmp"))
            throw new Error("disk full")
          return writeFile(...args)
        },
        rename: async (from, to) => {
          if (failure === "publish" && to.endsWith("manifest.json"))
            throw new Error("publish failed")
          return rename(from, to)
        },
      }
    )
    await assert.rejects(faulty.save(inputs, await cache.generated()), /disk full|publish failed/)
    assert.deepEqual(await cache.find(inputs), first)
    assert.deepEqual(
      (await readdir(path.join(root, ".cache/mobile-dev-shell"))).sort(),
      [path.basename(first.apk), "manifest.json"].sort()
    )
  }
})

test("source or generated changes during staging cannot publish a verified cache", async (t) => {
  for (const source of [true, false]) {
    const { root, cache, env, put } = await fixture(t)
    const inputs = await cache.fingerprint()
    const outputs = await cache.generated()
    const faulty = devShellCache(
      root,
      env,
      { javaVersion: "javac 21" },
      {
        writeFile: async (...args) => {
          await writeFile(...args)
          if (String(args[0]).endsWith(".apk.tmp"))
            await put(
              source
                ? "mobile/android/app/src/main/java/MainActivity.java"
                : "mobile/android/app/src/main/assets/extra.txt",
              "concurrent edit"
            )
        },
      }
    )
    await assert.rejects(faulty.save(inputs, outputs), /before cache publication/)
    assert.equal(await cache.find(inputs), null)
    assert.deepEqual(await readdir(path.join(root, ".cache/mobile-dev-shell")), [])
  }
})

test("installed package must have exactly matching APK bytes; missing/unreadable/split/malicious paths fail closed", async () => {
  const hash = "a".repeat(64)
  const apk = "/data/app/~~id/com.cognia.mobile-id/base.apk"
  const invoke = async (listing, output) =>
    installedDevShellMatches(async (args) => {
      if (args.includes("path")) return listing
      if (output instanceof Error) throw output
      return output
    }, hash)
  assert.equal(await invoke(`package:${apk}`, `${hash}  ${apk}\n`), true)
  assert.equal(await invoke(`package:${apk}`, `${"b".repeat(64)}  ${apk}`), false)
  assert.equal(await invoke(`package:${apk}`, new Error("permission denied")), false)
  assert.equal(await invoke(`package:${apk}`, `${hash}  /different.apk`), false)
  for (const listing of [
    "",
    "package:/data/app/a;evil.apk",
    `package:${apk}\npackage:/data/app/split.apk`,
  ])
    assert.equal(await invoke(listing, `${hash}  ${apk}`), false)
  const calls = []
  assert.equal(
    await installedDevShellMatches(async (args) => {
      calls.push(args)
      if (args.includes("path")) return `package:${apk}`
      if (!args.includes("toybox")) throw new Error("command missing")
      return `${hash}  ${apk}`
    }, hash),
    true
  )
  assert.equal(calls.length, 3)
})
