import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@web/lib/utils"

/**
 * The site's one button.
 *
 * Generated by `shadcn add` and then rewritten onto the paper/ink token set:
 * the stock variant table is written against `--primary`, `--accent`,
 * `--background`, `--input`, `--ring` and `--secondary`, none of which exist in
 * `web/app/globals.css` (ADR-0092 §10 defines a bespoke semantic palette, not
 * the shadcn one), so the generated version would have rendered unstyled.
 *
 * Two things deliberately absent:
 *
 *  - **No focus ring.** `globals.css` sets `:focus-visible { outline: 2px solid
 *    var(--action) }` for the whole site; shadcn's `ring-[3px]` would be a
 *    second, competing focus system on one page.
 *  - **No `rounded-md`.** The radius scale here is `control` / `panel` /
 *    `stage` (spec §3.3), and `tailwind-merge` cannot resolve a conflict
 *    between `rounded-md` and `rounded-control` — see `lib/utils.test.ts`.
 */
const buttonVariants = cva(
  "inline-flex shrink-0 items-center justify-center gap-2 rounded-control font-medium whitespace-nowrap outline-none disabled:pointer-events-none disabled:opacity-40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        /** The single primary action. Spec §7 forbids competing top-level CTAs. */
        primary: "bg-ink text-paper transition-opacity hover:opacity-90",
        outline: "border border-hairline-strong text-ink transition-colors hover:bg-surface",
        ghost: "text-muted transition-colors hover:text-ink",
        /**
         * On the dark execution stage, which stays dark in both themes — so it
         * uses the `on-stage` tokens rather than `ink`/`paper`, which flip.
         */
        stage:
          "border border-on-stage-hairline text-on-stage-muted transition-colors hover:text-on-stage",
      },
      size: {
        sm: "h-8 px-3 text-xs",
        md: "h-10 px-4 text-sm",
        lg: "px-6 py-3 text-base",
      },
    },
    defaultVariants: {
      variant: "primary",
      size: "md",
    },
  }
)

function Button({
  className,
  variant = "primary",
  size = "md",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  // `asChild` is load-bearing here, not boilerplate: the primary CTA renders a
  // `SiteLink` (an `<a>`), and without Slot it would nest an anchor inside a
  // button — invalid markup that also breaks keyboard activation.
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
