"use client"

import * as React from "react"
import { type VariantProps } from "class-variance-authority"
import { ToggleGroup as ToggleGroupPrimitive } from "radix-ui"

import { cn } from "@web/lib/utils"
import { toggleVariants } from "@web/components/ui/toggle"

/**
 * Generated by `shadcn add` and trimmed to what this site uses.
 *
 * The stock version carries a `spacing` prop that drives a matrix of
 * `data-[spacing=0]:first:rounded-l-md` joins and `shadow-xs` — none of which
 * apply to a single hairline-bordered segmented control. What is kept is the
 * part that matters: Radix's roving tabindex and arrow-key navigation, which
 * the hand-rolled `role="radiogroup"` this replaces did not implement.
 */
function ToggleGroup({
  className,
  variant,
  size,
  children,
  ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Root> & VariantProps<typeof toggleVariants>) {
  return (
    <ToggleGroupPrimitive.Root
      data-slot="toggle-group"
      className={cn(
        "inline-flex h-8 w-fit items-center rounded-control border border-hairline p-0.5",
        className
      )}
      {...props}
    >
      <ToggleGroupContext.Provider value={{ variant, size }}>
        {children}
      </ToggleGroupContext.Provider>
    </ToggleGroupPrimitive.Root>
  )
}

const ToggleGroupContext = React.createContext<VariantProps<typeof toggleVariants>>({})

function ToggleGroupItem({
  className,
  children,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Item> & VariantProps<typeof toggleVariants>) {
  const context = React.useContext(ToggleGroupContext)

  return (
    <ToggleGroupPrimitive.Item
      data-slot="toggle-group-item"
      className={cn(
        toggleVariants({
          variant: context.variant ?? variant,
          size: context.size ?? size,
        }),
        className
      )}
      {...props}
    >
      {children}
    </ToggleGroupPrimitive.Item>
  )
}

export { ToggleGroup, ToggleGroupItem }
