"use client"

import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Toggle as TogglePrimitive } from "radix-ui"

import { cn } from "@web/lib/utils"

/**
 * Generated by `shadcn add` and rewritten onto the paper/ink token set — the
 * stock table targets `--muted-foreground`, `--accent`, `--input` and `--ring`,
 * which ADR-0092 §10's palette does not define.
 *
 * `segment` is the only variant the site uses: the theme control, whose
 * selected state is `ink` on `paper` (a 14.9:1 inversion) rather than a tinted
 * accent, so the pressed item is legible without relying on colour.
 */
const toggleVariants = cva(
  "inline-flex items-center justify-center gap-2 rounded-[6px] text-xs font-normal whitespace-nowrap transition-colors outline-none disabled:pointer-events-none disabled:opacity-40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        segment: "text-muted hover:text-ink data-[state=on]:bg-ink data-[state=on]:text-paper",
      },
      size: {
        sm: "px-2.5 py-1",
      },
    },
    defaultVariants: {
      variant: "segment",
      size: "sm",
    },
  }
)

function Toggle({
  className,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof TogglePrimitive.Root> & VariantProps<typeof toggleVariants>) {
  return (
    <TogglePrimitive.Root
      data-slot="toggle"
      className={cn(toggleVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Toggle, toggleVariants }
