// Generated by scripts/sync-version.mjs. Do not edit by hand.
// Run `node scripts/sync-version.mjs` after changing the package version.

/** The published version of `@cognia/agent`, sent to the host on initialize. */
export const SDK_VERSION = "0.1.0"

/** The npm package name, sent to the host on initialize. */
export const SDK_PACKAGE_NAME = "@cognia/agent"
