/**
 * Single source of truth for per-model pricing + cost computation, shared by
 * the GUI usage analytics (`session-analytics.ts`), the CLI footer/usage panel
 * (`cli/src/tui/format/usage.ts`), the workflow run aggregator, and the routing
 * engine's cost-aware ranking (`model-pricing.ts`).
 *
 * Before this module there were two disjoint pricing systems — one keyed off
 * the static `MODEL_PRICING`/CNY tables (UI display, returned only
 * `{input,output}`) and one off the built-in catalog (routing) — and neither
 * consulted the freshest source, the synced models.dev catalog. The CLI and
 * GUI therefore priced the same turn differently. This module collapses them.
 *
 * Resolution order (highest authority first); each layer is normalized to USD
 * and merged field-by-field, so a custom override of just the input rate still
 * inherits the catalog's cache rates:
 *   1. user custom-provider metadata pricing
 *   2. account-discovered model pricing (live /v1/models)
 *   3. models.dev catalog (freshest global metadata; carries cache/batch rates)
 *   4. static MODEL_PRICING / MODEL_PRICING_CNY tables (by model id)
 *   5. built-in PROVIDERS catalog
 *   6. bundled LiteLLM-derived catalog (787 models, offline floor)
 *
 * Layer 6 exists because layers 1–3 need network or account state and layers
 * 4–5 are hand-maintained — the static table went five months stale without
 * anything noticing. A model missing from every layer prices as "unknown", so
 * the floor is what keeps a fresh offline install from reporting real spend as
 * unpriced. It is generated by `pnpm pricing:sync` and gated by
 * `pnpm pricing:catalog:check`.
 *
 * Pure given the injected `catalog` reader; the default reads the in-memory
 * synced catalog so callers get "catalog-first" pricing without extra wiring.
 */

import { getModelConfig, type ModelPricing } from "@cognia/provider-types/provider"
import { getCatalogModelMetadata } from "@/lib/ai/providers/models-dev-sync"
import { MODEL_PRICING, MODEL_PRICING_CNY, CURRENCIES } from "@/types/system/usage"
import bundledCatalog from "./model-price-catalog.generated.json"

/**
 * Cache multipliers relative to the base input rate (Anthropic prompt-caching:
 * a read is billed at 0.1×, a 5-minute write at 1.25×, a 1-hour write at 2×).
 * Applied ONLY when no explicit cache rate is known for the model — when the
 * catalog carries real `cachedInputPer1M`/`cacheCreationPer1M` (OpenAI,
 * DeepSeek, Anthropic, …) those win, so non-Anthropic providers are priced by
 * their own cache economics.
 */
export const DEFAULT_CACHE_READ_MULT = 0.1
export const DEFAULT_CACHE_WRITE_5M_MULT = 1.25
export const DEFAULT_CACHE_WRITE_1H_MULT = 2

/**
 * Back-compat alias for the 5-minute write multiplier. Anthropic's default
 * cache TTL is 5 minutes, so an un-split `cacheCreationInputTokens` count is
 * priced at this rate.
 * @deprecated Prefer {@link DEFAULT_CACHE_WRITE_5M_MULT} /
 * {@link DEFAULT_CACHE_WRITE_1H_MULT} — collapsing the two under-bills 1-hour
 * cache writes by 37.5% of the correct figure.
 */
export const DEFAULT_CACHE_WRITE_MULT = DEFAULT_CACHE_WRITE_5M_MULT

/**
 * Ratio between the 1-hour and 5-minute cache-write rates (2 / 1.25). Used to
 * derive a 1-hour rate when the catalog knows only a single explicit
 * cache-creation rate and no base input rate to scale from.
 */
const CACHE_WRITE_1H_OVER_5M = DEFAULT_CACHE_WRITE_1H_MULT / DEFAULT_CACHE_WRITE_5M_MULT

/** Per-provider custom + discovered pricing seams (subset of the settings store). */
export interface PricingSettings {
  providerSettings?: Record<
    string,
    { discoveredModels?: Array<{ id: string; pricing?: Partial<ModelPricing> }> } | undefined
  >
  customProviders?: Array<{
    id: string
    customModelMetadata?: Record<string, { pricing?: Partial<ModelPricing> } | undefined>
  }>
}

/** Look up models.dev catalog pricing for a (provider, model). */
export type CatalogPricingLookup = (
  providerId: string,
  modelId: string
) => Partial<ModelPricing> | undefined

export interface ResolvePricingOptions {
  settings?: PricingSettings
  /** models.dev catalog seam; defaults to the in-memory synced catalog. */
  catalog?: CatalogPricingLookup
}

/** The non-token, per-single-unit rate fields of {@link ModelPricing}. */
const UNIT_PRICING_FIELDS = [
  "perPageUsd",
  "perCharUsd",
  "perContainerHourUsd",
  "freeContainerHoursPerMonth",
] as const

type UnitPricingField = (typeof UNIT_PRICING_FIELDS)[number]

/** The numeric per-1M-token rate fields of {@link ModelPricing}. */
const PRICING_FIELDS = [
  "promptPer1M",
  "completionPer1M",
  "cachedInputPer1M",
  "cacheCreationPer1M",
  "batchInputPer1M",
  "batchOutputPer1M",
  "audioInputPer1M",
  "audioOutputPer1M",
] as const

type PricingField = (typeof PRICING_FIELDS)[number]

/** Convert a pricing layer to USD (divides CNY values by the CNY→USD rate). */
function toUsd(p: Partial<ModelPricing> | undefined): Partial<ModelPricing> | undefined {
  if (!p) return undefined
  if (p.currency !== "CNY") return p
  const rate = CURRENCIES.CNY.rateFromUSD || 1
  const out: Partial<ModelPricing> = { currency: "USD" }
  for (const f of PRICING_FIELDS) {
    const v = p[f]
    if (typeof v === "number") out[f] = v / rate
  }
  for (const f of UNIT_PRICING_FIELDS) {
    const v = p[f]
    // A free-unit allowance is a COUNT, not a price — converting it would
    // silently shrink the included quota for CNY-denominated catalogs.
    if (typeof v === "number") {
      out[f] = f === "freeContainerHoursPerMonth" ? v : v / rate
    }
  }
  if (p.perRequestUsd) {
    const converted: Record<string, number> = {}
    for (const [tool, price] of Object.entries(p.perRequestUsd)) {
      if (typeof price === "number" && Number.isFinite(price)) converted[tool] = price / rate
    }
    out.perRequestUsd = converted
  }
  return out
}

/**
 * Bundled LiteLLM-derived layer — the offline floor.
 *
 * Keyed by provider then model id. Falls back to a scan across providers when
 * no `providerId` is in scope (the chat context popover has only a model id),
 * which is safe because the artifact stores one entry per bare model id.
 */
function bundledCatalogPricing(
  providerId: string | undefined,
  modelId: string
): Partial<ModelPricing> | undefined {
  const providers = (bundledCatalog as BundledCatalog).providers
  if (providerId) {
    const hit = providers[providerId]?.[modelId]
    if (hit) return { ...hit, currency: "USD" }
  }
  for (const models of Object.values(providers)) {
    const hit = models[modelId]
    if (hit) return { ...hit, currency: "USD" }
  }
  return undefined
}

/** Shape of `model-price-catalog.generated.json`, pinned by its own gate. */
interface BundledCatalog {
  source: string
  providers: Record<
    string,
    Record<
      string,
      {
        promptPer1M?: number
        completionPer1M?: number
        cachedInputPer1M?: number
        cacheCreationPer1M?: number
        maxInputTokens?: number
        maxOutputTokens?: number
      }
    >
  >
}

/** Static MODEL_PRICING / MODEL_PRICING_CNY layer for a model id (USD). */
function staticTablePricing(modelId: string): Partial<ModelPricing> | undefined {
  const usd = MODEL_PRICING[modelId]
  if (usd) return { promptPer1M: usd.input, completionPer1M: usd.output }
  const cny = MODEL_PRICING_CNY[modelId]
  if (cny) {
    const rate = CURRENCIES.CNY.rateFromUSD || 1
    return { promptPer1M: cny.input / rate, completionPer1M: cny.output / rate }
  }
  return undefined
}

/**
 * Field-merge pricing layers (highest priority first), normalizing each to USD.
 * Returns null when no layer carries a base (prompt/completion) rate — a
 * cache-only layer has no usable anchor, mirroring the catalog mapper's policy.
 *
 * Unset rates are left `undefined` (not coerced to 0) so the routing engine's
 * blended-ranking figure can reuse the present side, and so a genuinely-free
 * $0 model stays distinguishable from "rate unknown".
 */
export function mergePricingLayers(
  layers: Array<Partial<ModelPricing> | undefined>
): Partial<ModelPricing> | null {
  const merged: Partial<Record<PricingField, number>> = {}
  const mergedUnits: Partial<Record<UnitPricingField, number>> = {}
  const mergedRequests: Record<string, number> = {}
  for (const raw of layers) {
    const layer = toUsd(raw)
    if (!layer) continue
    for (const f of PRICING_FIELDS) {
      const v = layer[f]
      if (merged[f] === undefined && typeof v === "number") merged[f] = v
    }
    for (const f of UNIT_PRICING_FIELDS) {
      const v = layer[f]
      if (mergedUnits[f] === undefined && typeof v === "number") mergedUnits[f] = v
    }
    // Per-tool rates merge key-by-key like the scalar fields, so a custom
    // override of one server tool still inherits the catalog's rates for the
    // others.
    for (const [tool, price] of Object.entries(layer.perRequestUsd ?? {})) {
      if (mergedRequests[tool] === undefined && typeof price === "number") {
        mergedRequests[tool] = price
      }
    }
  }
  if (merged.promptPer1M === undefined && merged.completionPer1M === undefined) return null
  const result: Partial<ModelPricing> = { currency: "USD" }
  for (const f of PRICING_FIELDS) {
    if (merged[f] !== undefined) result[f] = merged[f]
  }
  for (const f of UNIT_PRICING_FIELDS) {
    if (mergedUnits[f] !== undefined) result[f] = mergedUnits[f]
  }
  if (Object.keys(mergedRequests).length > 0) result.perRequestUsd = mergedRequests
  return result
}

const defaultCatalogLookup: CatalogPricingLookup = (providerId, modelId) =>
  getCatalogModelMetadata(providerId, modelId)?.pricing

/**
 * Resolve the full USD pricing for a (provider, model), layering custom >
 * discovered > models.dev catalog > static tables > built-in catalog. Returns
 * null when no rate is known anywhere.
 */
export function resolveModelPricingUsd(
  providerId: string | undefined,
  modelId: string | undefined,
  opts: ResolvePricingOptions = {}
): Partial<ModelPricing> | null {
  if (!modelId) return null
  const catalog = opts.catalog ?? defaultCatalogLookup
  const layers: Array<Partial<ModelPricing> | undefined> = []
  if (providerId) {
    layers.push(
      opts.settings?.customProviders?.find((p) => p.id === providerId)?.customModelMetadata?.[
        modelId
      ]?.pricing
    )
    layers.push(
      opts.settings?.providerSettings?.[providerId]?.discoveredModels?.find((m) => m.id === modelId)
        ?.pricing
    )
    layers.push(catalog(providerId, modelId))
  }
  layers.push(staticTablePricing(modelId))
  if (providerId) layers.push(getModelConfig(providerId, modelId)?.pricing)
  layers.push(bundledCatalogPricing(providerId, modelId))
  return mergePricingLayers(layers)
}

/**
 * Non-token billable quantities for one turn. Zero/absent means "none".
 *
 * These exist because real charges are not all per-token: Anthropic bills web
 * search per request and code execution per container-hour, OCR providers bill
 * per page and TTS per character. Counting them only in tokens structurally
 * cannot represent that spend.
 */
export interface CostUnitQuantities {
  /**
   * Server-tool invocation counts keyed by normalized tool name, exactly as
   * `usage.server_tool_use` reports them after normalization
   * (`{ web_search: 3 }`).
   */
  requests?: Record<string, number>
  pages?: number
  characters?: number
  containerHours?: number
}

/** Token breakdown for {@link costFromTokensUsd}. All fields optional / default 0. */
export interface CostTokens {
  inputTokens?: number
  outputTokens?: number
  cacheReadInputTokens?: number
  /**
   * Cache-creation tokens with no known TTL. Priced at the 5-minute rate, which
   * is Anthropic's default TTL. Providers that report the TTL split should use
   * the two fields below instead — this one exists for legacy rows and for
   * providers with a single cache-write rate.
   */
  cacheCreationInputTokens?: number
  /** Cache-creation tokens written with a 5-minute TTL (`ephemeral_5m`). */
  cacheCreation5mInputTokens?: number
  /** Cache-creation tokens written with a 1-hour TTL (`ephemeral_1h`). */
  cacheCreation1hInputTokens?: number
}

/**
 * A turn's complete billable footprint: token counts plus the non-token units.
 * `costFromTokensUsd` accepts this, so a caller that has server-tool counts can
 * pass them without a second costing path.
 */
export interface CostUnits extends CostTokens, CostUnitQuantities {}

/** Costing knobs that depend on state the pricing module deliberately lacks. */
export interface CostOptions {
  /**
   * Container-hours still inside this month's included allowance. Only hours
   * beyond it are charged. Omitted ⇒ the model's full
   * `freeContainerHoursPerMonth` is assumed unused, which under-charges rather
   * than over-charges a user whose consumption is not being tracked yet.
   */
  freeContainerHoursRemaining?: number
}

/** Sum the USD charge for the non-token units of a turn. */
function unitCostUsd(
  units: CostUnitQuantities,
  pricing: Partial<ModelPricing>,
  opts: CostOptions
): number {
  let total = 0

  for (const [tool, count] of Object.entries(units.requests ?? {})) {
    if (typeof count !== "number" || !Number.isFinite(count) || count <= 0) continue
    const rate = pricing.perRequestUsd?.[tool]
    // An unpriced server tool contributes 0 rather than guessing a rate; the
    // `known` flag on `priceTokensForModel` is what tells the caller the figure
    // is incomplete.
    if (typeof rate === "number") total += count * rate
  }

  if (units.pages && pricing.perPageUsd) total += units.pages * pricing.perPageUsd
  if (units.characters && pricing.perCharUsd) total += units.characters * pricing.perCharUsd

  if (units.containerHours && pricing.perContainerHourUsd) {
    const allowance = Math.max(
      0,
      opts.freeContainerHoursRemaining ?? pricing.freeContainerHoursPerMonth ?? 0
    )
    const billable = Math.max(0, units.containerHours - allowance)
    total += billable * pricing.perContainerHourUsd
  }

  return total
}

/**
 * Cost of one turn (or session total) in USD from a token breakdown and a
 * resolved pricing record. Explicit cache rates are used when the pricing
 * carries them; otherwise cache reads/writes fall back to the input rate scaled
 * by the Anthropic multipliers. Returns 0 when pricing is null or all-zero.
 *
 * The two cache-write TTLs are billed differently (1.25× vs 2× base input), so
 * they are priced separately. When only an explicit single `cacheCreationPer1M`
 * is known, the 1-hour rate is derived from it by the same ratio the published
 * multipliers use, since no catalog currently publishes a distinct 1-hour rate.
 *
 * Accepts {@link CostUnits}, so non-token charges (server-tool invocations, OCR
 * pages, TTS characters, container-hours) are summed by the SAME call. There is
 * deliberately no second costing entry point for them — a parallel path is how
 * the repo ended up with four disagreeing pricing implementations.
 */
export function costFromTokensUsd(
  tokens: CostUnits,
  pricing: Partial<ModelPricing> | null,
  opts: CostOptions = {}
): number {
  if (!pricing) return 0
  const inRate = pricing.promptPer1M || 0
  const outRate = pricing.completionPer1M || 0
  const readRate = pricing.cachedInputPer1M ?? inRate * DEFAULT_CACHE_READ_MULT
  const write5mRate = pricing.cacheCreationPer1M ?? inRate * DEFAULT_CACHE_WRITE_5M_MULT
  const write1hRate =
    inRate > 0 ? inRate * DEFAULT_CACHE_WRITE_1H_MULT : write5mRate * CACHE_WRITE_1H_OVER_5M
  const units = unitCostUsd(tokens, pricing, opts)
  // An all-zero token rate table still bills its non-token units: a $0-token
  // model that charges $10/1k searches is real, and returning 0 here would hide
  // that spend entirely.
  if (inRate === 0 && outRate === 0 && readRate === 0 && write5mRate === 0) return units
  return (
    ((tokens.inputTokens ?? 0) * inRate +
      (tokens.outputTokens ?? 0) * outRate +
      (tokens.cacheReadInputTokens ?? 0) * readRate +
      ((tokens.cacheCreationInputTokens ?? 0) + (tokens.cacheCreation5mInputTokens ?? 0)) *
        write5mRate +
      (tokens.cacheCreation1hInputTokens ?? 0) * write1hRate) /
      1_000_000 +
    units
  )
}

/**
 * Convenience: resolve pricing for a (provider, model) and price a turn's full
 * billable footprint in one call. Returns `{ cost, known }` so callers can
 * distinguish a genuine $0 (free model) from "no pricing data" (`known: false`).
 */
export function priceTokensForModel(
  providerId: string | undefined,
  modelId: string | undefined,
  tokens: CostUnits,
  opts?: ResolvePricingOptions & CostOptions
): { cost: number; known: boolean } {
  const pricing = resolveModelPricingUsd(providerId, modelId, opts)
  return {
    cost: costFromTokensUsd(tokens, pricing, {
      freeContainerHoursRemaining: opts?.freeContainerHoursRemaining,
    }),
    known: pricing !== null,
  }
}
