/**
 * The pre-turn gate for project-claim recall.
 *
 * Four checks, all deterministic, all of the form "recall CANNOT help here" —
 * never "recall PROBABLY will not help here". That distinction is the whole
 * design of this file, so it is worth being explicit about what is deliberately
 * absent.
 *
 * WHAT THIS DOES NOT DO: decide whether the user's question is self-contained.
 * That reads like the obviously useful gate and it is a trap. Answering it needs
 * a classifier, i.e. an LLM call on the hottest path in the app, plus its own
 * PII gate and its own outbound provider call — to save a BM25 scan over a few
 * hundred rows. The cure costs an order of magnitude more than the disease.
 *
 * ESCALATION IS THE MODEL'S JOB, not this gate's. The model is the only thing in
 * the loop that has read the conversation, so the host's role is to make the
 * deep path available and cheap (register `project_history_search` when there is
 * a workspace) rather than to predict the need in advance. The one signal worth
 * adding is `weak` from `applyProjectContinuityContext` — and that can only be
 * known AFTER retrieving, which is exactly why it is a hint in the output and
 * not a decision here.
 *
 * Pure: no I/O, no model calls.
 */

import { meaningfulTerms } from "../retrieve/retriever"

export type ProjectRecallSkipReason =
  /** Claims are scoped to a workspace; without one there is nothing to scope to. */
  | "no_workspace"
  /** The user turned the section off. */
  | "disabled"
  /** Incognito: this context neither reads nor writes memory. */
  | "temporary"
  /** Nothing to match on — every token was a stopword or punctuation. */
  | "no_query_terms"
  /** Not a person asking a question: a slash-command expansion, a system turn. */
  | "system_turn"

export interface ProjectRecallGateInput {
  userMessage: string
  projectId?: string
  enableProjectContinuity: boolean
  temporary: boolean
  /**
   * True when this turn's text was generated by the app rather than typed —
   * slash-command expansions, retry scaffolding, connector relays. Recall
   * against machine-authored text matches the scaffolding, not the question.
   */
  systemGenerated?: boolean
}

export type ProjectRecallGateResult =
  { allowed: true } | { allowed: false; reason: ProjectRecallSkipReason }

export function evaluateProjectRecallGate(input: ProjectRecallGateInput): ProjectRecallGateResult {
  if (!input.enableProjectContinuity) return { allowed: false, reason: "disabled" }
  if (input.temporary) return { allowed: false, reason: "temporary" }
  if (!input.projectId) return { allowed: false, reason: "no_workspace" }
  if (input.systemGenerated) return { allowed: false, reason: "system_turn" }
  // Reuses the retriever's own tokenizer + stopword list rather than a second
  // one: a gate that disagreed with the retriever about what a term is would
  // skip turns the retriever could have answered.
  if (meaningfulTerms(input.userMessage).size === 0) {
    return { allowed: false, reason: "no_query_terms" }
  }
  return { allowed: true }
}
