import assert from "node:assert/strict"
import { existsSync, readFileSync } from "node:fs"
import { test } from "node:test"

import {
  BASELINE_FILE,
  RULES,
  countOffenders,
  diffAgainstBaseline,
  isExempt,
  scanRepository,
} from "./check-identity-vocabulary.mjs"

test("a qualified name is not an offence — that is the whole fix", () => {
  assert.equal(countOffenders("lib/x.ts", "const localAccountId = 1"), null)
  assert.equal(countOffenders("lib/x.ts", "const cogniaAccountId = 1"), null)
  assert.equal(countOffenders("lib/x.ts", "const providerAccountId = 1"), null)
  assert.equal(countOffenders("crates/x.rs", "let local_account_id = 1;"), null)
})

test("a bare account id is counted, once per occurrence", () => {
  assert.deepEqual(countOffenders("lib/x.ts", "accountId; accountId"), { bareAccountId: 2 })
  assert.deepEqual(countOffenders("crates/x.rs", "account_id, account_id"), {
    bareAccountIdRust: 2,
  })
})

test("each rule only applies to its own extensions", () => {
  // `account_id` inside TypeScript is somebody else's wire format, not our name.
  assert.equal(countOffenders("lib/x.ts", "const a = row.account_id"), null)
  assert.equal(countOffenders("crates/x.rs", "let accountId = 1;"), null)
})

test("tests, stories, typings and generated mirrors are exempt", () => {
  for (const path of [
    "lib/x.test.ts",
    "components/x.test.tsx",
    "components/x.stories.tsx",
    "types/x.d.ts",
    "lib/x.generated.ts",
  ]) {
    assert.ok(isExempt(path), `${path} should be exempt`)
    assert.equal(countOffenders(path, "accountId"), null)
  }
  assert.equal(countOffenders("lib/x.ts", "// @generated by foo\naccountId"), null)
})

test("the baseline ratchets: growth fails, shrinkage passes", () => {
  const baseline = { "lib/a.ts": { bareAccountId: 3 } }

  assert.deepEqual(diffAgainstBaseline({ "lib/a.ts": { bareAccountId: 3 } }, baseline), [])
  assert.deepEqual(diffAgainstBaseline({ "lib/a.ts": { bareAccountId: 1 } }, baseline), [])
  assert.deepEqual(diffAgainstBaseline({}, baseline), [])

  const grew = diffAgainstBaseline({ "lib/a.ts": { bareAccountId: 4 } }, baseline)
  assert.equal(grew.length, 1)
  assert.match(grew[0], /grew 3 → 4/)
})

test("a file the baseline never saw may not introduce one at all", () => {
  const problems = diffAgainstBaseline({ "lib/brand-new.ts": { bareAccountId: 1 } }, {})
  assert.equal(problems.length, 1)
  assert.match(problems[0], /baseline does not cover/)
})

test("every problem names the rule's remedy, so the message is actionable", () => {
  const problems = diffAgainstBaseline({ "lib/a.ts": { bareAccountId: 1 } }, {})
  assert.match(problems[0], /localAccountId/)
  const rustProblems = diffAgainstBaseline({ "crates/a.rs": { bareAccountIdRust: 1 } }, {})
  assert.match(rustProblems[0], /local_account_id/)
})

test("every rule declares a global pattern, or counting silently returns 1", () => {
  for (const rule of RULES) {
    assert.ok(rule.pattern.global, `${rule.id} must use the /g flag`)
    assert.ok(rule.hint.length > 0, `${rule.id} must tell the reader what to write instead`)
  }
})

test("the committed baseline matches the tree — the gate is green as shipped", () => {
  assert.ok(existsSync(BASELINE_FILE), "baseline must be committed alongside the gate")
  const baseline = JSON.parse(readFileSync(BASELINE_FILE, "utf8"))
  assert.equal(baseline.version, 1)
  assert.deepEqual(diffAgainstBaseline(scanRepository(), baseline.entries), [])
})

test("the baseline is non-trivial, so a broken scan cannot pass as clean", () => {
  const baseline = JSON.parse(readFileSync(BASELINE_FILE, "utf8"))
  const files = Object.keys(baseline.entries).length
  assert.ok(files > 100, `expected the recorded debt, saw ${files} files`)
  assert.equal(
    baseline.total,
    Object.values(baseline.entries).reduce(
      (sum, counts) => sum + Object.values(counts).reduce((inner, n) => inner + n, 0),
      0
    )
  )
})
