/**
 * Type definitions for the Interactive AI Shell.
 *
 * The AI Shell is a side-panel conversation that interprets natural language
 * intent into multi-step terminal execution plans. The user types what they
 * want to achieve (e.g. "deploy to staging"), and the system generates a
 * plan of shell commands that can be reviewed, edited, and executed one by
 * one or all at once.
 */

/** Status of the AI Shell panel within the terminal dock. */
export type AiShellPanelState = "closed" | "open"

/** Role in the AI Shell conversation history. */
export type AiShellRole = "user" | "assistant" | "system"

/** A single message in the AI Shell conversation. */
export interface AiShellMessage {
  id: string
  role: AiShellRole
  content: string
  timestamp: number
}

/** Execution status for an individual step in the plan. */
export type StepStatus =
  | "pending" // not yet started
  | "running" // currently executing in the PTY
  | "succeeded" // exited with code 0
  | "failed" // exited with non-zero code
  | "skipped" // user chose to skip
  | "cancelled" // user cancelled mid-execution

/** A single executable step within an execution plan. */
export interface ExecutionStep {
  /** Monotonically increasing id within a plan (0-based). */
  index: number
  /** The shell command to execute. User-editable before execution. */
  command: string
  /** Short human-readable description of what this step does. */
  description: string
  /** Current execution status. */
  status: StepStatus
  /** Exit code from the PTY (set after execution completes). */
  exitCode: number | null
  /** Captured output snippet (last N lines) for error diagnosis. */
  outputSnippet: string | null
  /** Whether this step is considered "dangerous" (destructive, network, etc.). */
  requiresConfirmation: boolean
}

/** The overall plan status. */
export type PlanStatus =
  | "generating" // LLM is still streaming the plan
  | "ready" // plan is complete, awaiting user action
  | "executing" // steps are being run
  | "completed" // all steps finished (some may have failed)
  | "cancelled" // user cancelled the plan
  | "error" // plan generation failed

/** A complete execution plan generated by the AI. */
export interface ExecutionPlan {
  /** Unique plan id (nanoid). */
  id: string
  /** The user intent that triggered this plan. */
  intent: string
  /** Ordered list of steps to execute. */
  steps: ExecutionStep[]
  /** Overall plan status. */
  status: PlanStatus
  /** Error message if status is "error". */
  error?: string
  /** Timestamp when the plan was created. */
  createdAt: number
}

/**
 * Context assembled from the terminal state for the LLM to reason about.
 * Redacted through the PII gate before any model call.
 */
export interface AiShellContext {
  /** Current working directory. */
  cwd: string | null
  /** Shell name (bash, zsh, fish, etc.). */
  shell: string
  /** Current git branch (if in a git repo). */
  gitBranch: string | null
  /** Recent terminal output (last 50 lines, capped). */
  recentOutput: string
  /** Recent command history (last 10 commands). */
  recentCommands: string[]
  /** Operating system / platform identifier. */
  platform: string
}

/** Error advisory: when a step fails, the AI can suggest a fix. */
export interface ErrorAdvisory {
  /** The step that failed. */
  stepIndex: number
  /** Explanation of what likely went wrong. */
  diagnosis: string
  /** Suggested fix command(s). Can be empty if no fix is possible. */
  suggestedFix: string | null
  /** Whether the user should retry the same command after the fix. */
  retryAfterFix: boolean
}

/** Options for the plan generator. */
export interface PlanGeneratorOptions {
  /** Maximum number of steps allowed in a plan. */
  maxSteps?: number
  /** Additional instructions to include in the system prompt. */
  extraInstructions?: string
  /** Abort signal. */
  signal?: AbortSignal
}

/** Options for the plan executor. */
export interface PlanExecutorOptions {
  /** Timeout per step in milliseconds. Defaults to 60_000. */
  stepTimeoutMs?: number
  /** Whether to auto-skip confirmable steps or pause for approval. */
  autoConfirm?: boolean
  /** Abort signal. */
  signal?: AbortSignal
}

/** Callback fired when a step changes status during execution. */
export type StepProgressCallback = (
  stepIndex: number,
  status: StepStatus,
  exitCode: number | null,
  outputSnippet: string | null
) => void

/** Callback fired when plan generation streams a partial update. */
export type PlanStreamCallback = (partial: Partial<ExecutionPlan>) => void

/**
 * The session interface that the plan executor needs to write commands
 * and observe their completion. Minimal contract decoupled from xterm.
 */
export interface AiShellSession {
  /** Write text to the PTY (no automatic newline — include \r if needed). */
  write(data: string): void
  /**
   * Register a callback for the next OSC 633 prompt_start event (command
   * completed). Returns an unsubscribe function. If shell integration is
   * not available, the callback fires after a fallback timeout.
   */
  onNextPrompt(cb: () => void): () => void
  /** Register a callback for the next command_end event with exit code. */
  onCommandEnd(cb: (exitCode: number | null) => void): () => void
  /** Get recent output lines since last command start (for error diagnosis). */
  getRecentOutput(maxLines?: number): string
}
