// Re-export shim: canonical source moved to @cognia/provider-core (Stage 2).
export {
  OpenRouterError,
  buildChatRequestBody,
  buildChatRequestHeaders,
  buildProviderOrderingHeader,
  createApiKey,
  deleteApiKey,
  formatCredits,
  formatUsage,
  getAllUsageHistory,
  getApiKey,
  getCredits,
  getEnabledBYOKProviders,
  getModel,
  getModelProvider,
  getUsageHistory,
  groupModelsByProvider,
  isModelFree,
  isProvisioningKey,
  isValidOpenRouterKey,
  listApiKeys,
  listModels,
  maskApiKey,
  parseModelPricing,
  sortModelsByProvider,
  updateApiKey,
} from "@cognia/provider-core/providers/openrouter"
export type {
  OpenRouterRequestConfig,
  UsageHistoryOptions,
} from "@cognia/provider-core/providers/openrouter"
