"""RepoWiki — repository documentation, generated by an agent, read in Cognia.

The wiki generator itself is vendored from RepoWiki (MIT) under ``repowiki/``,
algorithms and tests intact. Only three layers were replaced, all of them in
``repowiki/host.py``: model calls go through ``ctx.agent``, storage lands in the
plugin's own data directory instead of ``~/.repowiki``, and file enumeration
goes through ``ctx.workspace`` so the host's containment rules and its refusal
to hand over credential files apply.

This module is the surface: the tools an agent (or the panel, next batch) calls.
State is deliberately in-process and keyed by project id — a scan is expensive
and the result is large, so re-deriving it per tool call would be the wrong
trade; the durable copies are the analyzer cache and the RAG snapshot on disk.
"""

from __future__ import annotations

import cognia
from cognia import get_config, progress, tool

from repowiki.config import Config
from repowiki.core.rag import format_context
from repowiki.export.html import export_html
from repowiki.export.json_export import export_json
from repowiki.export.markdown import export_markdown
from repowiki.host import configure_paths, release_workspace
from repowiki.pipeline import ScanResult, build_index, reading_order, scan
from repowiki.project import project_id_for

#: project_id -> the most recent scan. Bounded by how many repositories the
#: user actually opens, which is small; a scan holds file contents, so this is
#: not something to let grow without a reason.
_SCANS: dict[str, ScanResult] = {}
_INDEXES: dict[str, object] = {}


def _config() -> Config:
    return Config.from_host(get_config())


async def on_startup() -> None:
    """Point storage at the plugin's own data directory.

    Asked for rather than guessed: ``ctx.fs.getDataDir()`` is the same
    directory ``ctx.fs`` is jailed to, so the two SQLite files land beside
    whatever else this plugin writes and are reclaimed when it is uninstalled.
    Nothing in the package has a default path any more, so a missing call here
    fails loudly at the first cache write instead of leaving a stray file in
    the user's home directory.
    """
    configure_paths(await cognia.ctx.fs.getDataDir())


def on_config_updated(config: dict) -> None:
    # Tuning knobs are read per call, so nothing to invalidate — except a RAG
    # index built with different chunk sizes, which would answer with chunks
    # the new settings would never have produced.
    _INDEXES.clear()


async def on_shutdown() -> None:
    """Release every checkout we cloned; leave the user's own folders alone."""
    for result in list(_SCANS.values()):
        if result.handle.ephemeral:
            try:
                await release_workspace(result.handle)
            except Exception:  # noqa: BLE001 — shutdown is best-effort
                pass
    _SCANS.clear()
    _INDEXES.clear()


def _require_scan(project_id: str) -> ScanResult:
    result = _SCANS.get(project_id)
    if result is None:
        raise ValueError(
            f"No wiki for '{project_id}'. Run repowiki_scan first — "
            f"known: {', '.join(sorted(_SCANS)) or 'none'}"
        )
    return result


@tool(
    name="repowiki_scan",
    description=(
        "Generate a wiki for a repository. Accepts a local path inside an open "
        "workspace, or a git URL / owner-repo to clone. Returns a summary; the "
        "pages are read with repowiki_get_page."
    ),
    parameters={
        "source": {
            "type": "string",
            "required": True,
            "description": "Local path, git URL, or owner/repo",
        },
        "since": {
            "type": "string",
            "required": False,
            "description": "Git ref; only re-analyse modules changed since it",
        },
    },
)
async def repowiki_scan(source: str, since: str = "") -> dict:
    cfg = _config()
    steps = {"done": 0}

    def report(message: str) -> None:
        # The analyzer emits one line per stage and per module, so the count is
        # unknown up front; report a message with no percentage rather than a
        # made-up one that jumps backwards when a module finishes early.
        steps["done"] += 1
        progress(message=message)

    result = await scan(source, config=cfg, since=since, on_progress=report)
    _SCANS[result.project_id] = result
    _INDEXES.pop(result.project_id, None)
    return result.to_summary()


@tool(
    name="repowiki_map",
    description=(
        "Rank a scanned repository's files by dependency PageRank. No model "
        "calls. This is the reading order: what to open first."
    ),
    parameters={
        "projectId": {"type": "string", "required": True},
        "top": {"type": "number", "required": False, "description": "How many files (default 25)"},
    },
)
def repowiki_map(projectId: str, top: float = 25) -> dict:
    result = _require_scan(projectId)
    return {"projectId": projectId, "entries": reading_order(result, top=max(1, int(top)))}


@tool(
    name="repowiki_get_page",
    description="Read one page of a generated wiki, as markdown.",
    parameters={
        "projectId": {"type": "string", "required": True},
        "pageId": {"type": "string", "required": True, "description": "Page id, e.g. 'index'"},
    },
)
def repowiki_get_page(projectId: str, pageId: str) -> dict:
    result = _require_scan(projectId)
    page = result.wiki.get_page(pageId)
    if page is None:
        known = ", ".join(p.id for p in result.wiki.pages)
        raise ValueError(f"No page '{pageId}'. Known pages: {known}")
    return {
        "projectId": projectId,
        "id": page.id,
        "title": page.title,
        "parentId": page.parent_id,
        "content": page.content,
    }


@tool(
    name="repowiki_search",
    description=(
        "Search a scanned repository's code and wiki pages. Hybrid TF-IDF + "
        "BM25 retrieval, no embedding call. Returns cited excerpts."
    ),
    parameters={
        "projectId": {"type": "string", "required": True},
        "query": {"type": "string", "required": True},
        "topK": {"type": "number", "required": False},
    },
)
async def repowiki_search(projectId: str, query: str, topK: float = 0) -> dict:
    result = _require_scan(projectId)
    cfg = _config()
    rag = _INDEXES.get(projectId)
    if rag is None:
        rag = await build_index(result, config=cfg)
        _INDEXES[projectId] = rag

    chunks = rag.retrieve(
        query,
        top_k=int(topK) or cfg.rag_top_k,
        min_score=cfg.rag_min_score,
    )
    return {
        "projectId": projectId,
        "query": query,
        "context": format_context(chunks),
        "citations": [
            {
                "path": chunk.file_path,
                "startLine": chunk.line_start,
                "endLine": chunk.line_end,
                "kind": chunk.kind,
            }
            for chunk in chunks
        ],
    }


@tool(
    name="repowiki_export",
    description=(
        "Write a scanned wiki to disk as markdown, json, or one self-contained "
        "HTML file. The HTML makes no external request and runs no script."
    ),
    parameters={
        "projectId": {"type": "string", "required": True},
        "format": {
            "type": "string",
            "required": True,
            "description": "markdown | json | html",
        },
        "outputPath": {
            "type": "string",
            "required": True,
            "description": "Destination file (json/html) or directory (markdown)",
        },
    },
)
def repowiki_export(projectId: str, format: str, outputPath: str) -> dict:
    result = _require_scan(projectId)
    kind = format.strip().lower()
    if kind in ("markdown", "md"):
        export_markdown(result.wiki, outputPath)
    elif kind == "json":
        export_json(result.wiki, outputPath)
    elif kind == "html":
        export_html(result.wiki, outputPath)
    else:
        raise ValueError(f"Unknown export format '{format}'. Use markdown, json, or html.")
    return {"projectId": projectId, "format": kind, "outputPath": outputPath}


@tool(
    name="repowiki_list",
    description="List the repositories scanned in this session and their page counts.",
)
def repowiki_list() -> dict:
    return {
        "projects": [
            {
                "projectId": pid,
                "projectName": result.wiki.project_name,
                "root": result.handle.root,
                "origin": result.handle.origin,
                "pageCount": len(result.wiki.pages),
            }
            for pid, result in sorted(_SCANS.items())
        ]
    }


@tool(
    name="repowiki_project_id",
    description=(
        "Resolve a repository source to its stable project id without scanning "
        "it — the id that keys the cache and the saved search index."
    ),
    parameters={"source": {"type": "string", "required": True}},
)
def repowiki_project_id(source: str) -> dict:
    return {"source": source, "projectId": project_id_for(source)}
