"""RepoWiki — repository documentation, generated by an agent, read in Cognia.

The wiki generator itself is vendored from RepoWiki (MIT) under ``repowiki/``,
algorithms and tests intact. Only three layers were replaced, all of them in
``repowiki/host.py``: model calls go through ``ctx.agent``, storage lands in the
plugin's own data directory instead of ``~/.repowiki``, and file enumeration
goes through ``ctx.workspace`` so the host's containment rules and its refusal
to hand over credential files apply.

This module is the surface: the tools an agent (or the panel, next batch) calls.
State is deliberately in-process and keyed by project id — a scan is expensive
and the result is large, so re-deriving it per tool call would be the wrong
trade; the durable copies are the analyzer cache and the RAG snapshot on disk.
"""

from __future__ import annotations

import logging

import cognia
from cognia import get_config, hook, progress, tool

from repowiki.config import Config
from repowiki.core.rag import format_context
from repowiki.export.html import export_html
from repowiki.export.json_export import export_json
from repowiki.export.markdown import export_markdown
from repowiki.host import configure_paths, release_workspace
from repowiki.panel import (
    ACTION_OPEN_CITATION,
    ACTION_OPEN_PAGE,
    ACTION_RESCAN,
    ACTION_SELECT_PROJECT,
    DEFAULT_LABELS,
    build_panel,
)
from repowiki.pipeline import ScanResult, build_index, reading_order, scan, staleness
from repowiki.project import project_id_for

logger = logging.getLogger(__name__)

#: project_id -> the most recent scan. Bounded by how many repositories the
#: user actually opens, which is small; a scan holds file contents, so this is
#: not something to let grow without a reason.
_SCANS: dict[str, ScanResult] = {}
_INDEXES: dict[str, object] = {}


#: App locale -> the language the prompts ask the model to write in. The
#: manifest's `language` setting overrides it; "auto" defers to this.
_LOCALE_TO_LANGUAGE = {"en": "en", "zh-CN": "zh", "zh-TW": "zh", "ja": "ja", "ko": "ko"}

#: Resolved once per host process. `ctx.i18n` is an RPC away, and a wiki whose
#: language flipped mid-scan because the user changed the app's language would
#: be worse than one that is consistently the language it started in.
_LOCALE: str = ""
_LABELS: dict[str, str] = dict(DEFAULT_LABELS)


def _config() -> Config:
    cfg = Config.from_host(get_config())
    if cfg.language in ("", "auto"):
        # Decision 26: the wiki follows the app unless the user says otherwise.
        cfg.language = _LOCALE_TO_LANGUAGE.get(_LOCALE, "en")
    return cfg


async def _resolve_locale_and_labels() -> None:
    """Read the app's language, and translate the panel chrome once.

    `ctx.i18n.t` resolves against this plugin's own manifest bundle, so these
    are the plugin's strings — not the app's — and a key the host cannot
    resolve comes back as the key itself. That is why the fallback is per key:
    a partial bundle must leave the other six in English rather than painting
    raw dotted keys into the panel.

    Failure is not fatal. A headless host with no i18n namespace gets an
    English panel, which is the same panel it had before this existed.

    Called again when a panel opens, because the user can change the app's
    language while the plugin is loaded and ``i18n.onLocaleChange`` registers a
    host-side callback — which is precisely what cannot cross a stdio boundary
    (ADR-0145). Re-asking at the moment the panel is about to be painted is the
    poll that replaces the subscription we cannot have.
    """
    global _LOCALE
    try:
        _LOCALE = str(await cognia.ctx.i18n.getCurrentLocale() or "")
    except Exception as exc:  # noqa: BLE001 — degrade to English, never abort
        logger.info("i18n.getCurrentLocale unavailable (%s); panel stays English", exc)
        return
    for key, fallback in DEFAULT_LABELS.items():
        try:
            value = await cognia.ctx.i18n.t(key)
        except Exception as exc:  # noqa: BLE001
            logger.info("i18n.t(%s) failed: %s", key, exc)
            continue
        # `t` echoes the key back when nothing resolved it; that is not a label.
        if isinstance(value, str) and value and value != key:
            _LABELS[key] = value


async def on_startup() -> None:
    """Point storage at the plugin's own data directory.

    Asked for rather than guessed: ``ctx.fs.getDataDir()`` is the same
    directory ``ctx.fs`` is jailed to, so the two SQLite files land beside
    whatever else this plugin writes and are reclaimed when it is uninstalled.
    Nothing in the package has a default path any more, so a missing call here
    fails loudly at the first cache write instead of leaving a stray file in
    the user's home directory.
    """
    configure_paths(await cognia.ctx.fs.getDataDir())
    await _resolve_locale_and_labels()


def on_config_updated(config: dict) -> None:
    # Tuning knobs are read per call, so nothing to invalidate — except a RAG
    # index built with different chunk sizes, which would answer with chunks
    # the new settings would never have produced.
    _INDEXES.clear()


async def on_shutdown() -> None:
    """Release every checkout we cloned; leave the user's own folders alone."""
    for result in list(_SCANS.values()):
        if result.handle.ephemeral:
            try:
                await release_workspace(result.handle)
            except Exception:  # noqa: BLE001 — shutdown is best-effort
                pass
    _SCANS.clear()
    _INDEXES.clear()


def _require_scan(project_id: str) -> ScanResult:
    result = _SCANS.get(project_id)
    if result is None:
        raise ValueError(
            f"No wiki for '{project_id}'. Run repowiki_scan first — "
            f"known: {', '.join(sorted(_SCANS)) or 'none'}"
        )
    return result


@tool(
    name="repowiki_scan",
    description=(
        "Generate a wiki for a repository. Accepts a local path inside an open "
        "workspace, or a git URL / owner-repo to clone. Returns a summary; the "
        "pages are read with repowiki_get_page."
    ),
    parameters={
        "source": {
            "type": "string",
            "required": True,
            "description": "Local path, git URL, or owner/repo",
        },
        "since": {
            "type": "string",
            "required": False,
            "description": "Git ref; only re-analyse modules changed since it",
        },
    },
)
async def repowiki_scan(source: str, since: str = "") -> dict:
    cfg = _config()
    steps = {"done": 0}

    def report(message: str) -> None:
        # The analyzer emits one line per stage and per module, so the count is
        # unknown up front; report a message with no percentage rather than a
        # made-up one that jumps backwards when a module finishes early.
        steps["done"] += 1
        progress(message=message)

    result = await scan(source, config=cfg, since=since, on_progress=report)
    _SCANS[result.project_id] = result
    _INDEXES.pop(result.project_id, None)
    return result.to_summary()


@tool(
    name="repowiki_map",
    description=(
        "Rank a scanned repository's files by dependency PageRank. No model "
        "calls. This is the reading order: what to open first."
    ),
    parameters={
        "projectId": {"type": "string", "required": True},
        "top": {"type": "number", "required": False, "description": "How many files (default 25)"},
    },
)
def repowiki_map(projectId: str, top: float = 25) -> dict:
    result = _require_scan(projectId)
    return {"projectId": projectId, "entries": reading_order(result, top=max(1, int(top)))}


@tool(
    name="repowiki_get_page",
    description="Read one page of a generated wiki, as markdown.",
    parameters={
        "projectId": {"type": "string", "required": True},
        "pageId": {"type": "string", "required": True, "description": "Page id, e.g. 'index'"},
    },
)
def repowiki_get_page(projectId: str, pageId: str) -> dict:
    result = _require_scan(projectId)
    page = result.wiki.get_page(pageId)
    if page is None:
        known = ", ".join(p.id for p in result.wiki.pages)
        raise ValueError(f"No page '{pageId}'. Known pages: {known}")
    return {
        "projectId": projectId,
        "id": page.id,
        "title": page.title,
        "parentId": page.parent_id,
        "content": page.content,
    }


@tool(
    name="repowiki_search",
    description=(
        "Search a scanned repository's code and wiki pages. Hybrid TF-IDF + "
        "BM25 retrieval, no embedding call. Returns cited excerpts."
    ),
    parameters={
        "projectId": {"type": "string", "required": True},
        "query": {"type": "string", "required": True},
        "topK": {"type": "number", "required": False},
    },
)
async def repowiki_search(projectId: str, query: str, topK: float = 0) -> dict:
    result = _require_scan(projectId)
    cfg = _config()
    rag = _INDEXES.get(projectId)
    if rag is None:
        rag = await build_index(result, config=cfg)
        _INDEXES[projectId] = rag

    chunks = rag.retrieve(
        query,
        top_k=int(topK) or cfg.rag_top_k,
        min_score=cfg.rag_min_score,
    )
    return {
        "projectId": projectId,
        "query": query,
        "context": format_context(chunks),
        "citations": [
            {
                "path": chunk.file_path,
                "startLine": chunk.line_start,
                "endLine": chunk.line_end,
                "kind": chunk.kind,
            }
            for chunk in chunks
        ],
    }


@tool(
    name="repowiki_export",
    description=(
        "Write a scanned wiki to disk as markdown, json, or one self-contained "
        "HTML file. The HTML makes no external request and runs no script."
    ),
    parameters={
        "projectId": {"type": "string", "required": True},
        "format": {
            "type": "string",
            "required": True,
            "description": "markdown | json | html",
        },
        "outputPath": {
            "type": "string",
            "required": True,
            "description": "Destination file (json/html) or directory (markdown)",
        },
    },
)
def repowiki_export(projectId: str, format: str, outputPath: str) -> dict:
    result = _require_scan(projectId)
    kind = format.strip().lower()
    if kind in ("markdown", "md"):
        export_markdown(result.wiki, outputPath)
    elif kind == "json":
        export_json(result.wiki, outputPath)
    elif kind == "html":
        export_html(result.wiki, outputPath)
    else:
        raise ValueError(f"Unknown export format '{format}'. Use markdown, json, or html.")
    return {"projectId": projectId, "format": kind, "outputPath": outputPath}


@tool(
    name="repowiki_list",
    description="List the repositories scanned in this session and their page counts.",
)
def repowiki_list() -> dict:
    return {
        "projects": [
            {
                "projectId": pid,
                "projectName": result.wiki.project_name,
                "root": result.handle.root,
                "origin": result.handle.origin,
                "pageCount": len(result.wiki.pages),
            }
            for pid, result in sorted(_SCANS.items())
        ]
    }


@tool(
    name="repowiki_project_id",
    description=(
        "Resolve a repository source to its stable project id without scanning "
        "it — the id that keys the cache and the saved search index."
    ),
    parameters={"source": {"type": "string", "required": True}},
)
def repowiki_project_id(source: str) -> dict:
    return {"source": source, "projectId": project_id_for(source)}


# ---------------------------------------------------------------------------
# Panel
# ---------------------------------------------------------------------------
#
# The reader is a declarative `kind: "a2ui"` context panel: the manifest names
# a surface and a build tool, the host calls the tool when the panel is first
# shown, and this pushes a component tree. There is no JavaScript anywhere in
# the path, which is the whole reason that panel class exists.
#
# Which wiki a panel shows is per-surface state, because two panels can be open
# on two different resources at once and a single "current page" would make one
# of them follow the other.

_PANEL_STATE: dict[str, dict] = {}

#: Last freshness answer per project id. Keyed by project, not by surface: two
#: panels on the same wiki are looking at the same checkout, and asking git the
#: same question twice would be the only difference.
_FRESHNESS: dict[str, dict] = {}


def _panel_state(surface_id: str) -> dict:
    return _PANEL_STATE.setdefault(surface_id, {"projectId": "", "pageId": "index"})


async def _refresh_freshness(project_id: str) -> dict | None:
    """Recompute and cache whether ``project_id``'s wiki is still current.

    Called when a panel opens, when it switches repository, and after a rescan
    — the three moments the user is actually looking at the badge. Not on every
    page click: a git diff per click buys nothing, because reading page 4 of a
    wiki cannot change the repository it was built from.
    """
    result = _SCANS.get(project_id)
    if result is None:
        _FRESHNESS.pop(project_id, None)
        return None
    summary = (await staleness(result)).to_summary()
    _FRESHNESS[project_id] = summary
    return summary


def _project_for_resource(resource: dict | None) -> str:
    """Pick the wiki a freshly-opened panel should show.

    A scan of the resource's own root wins; otherwise the only scan there is,
    if there is exactly one. With several and no match the panel opens empty
    rather than guessing — showing the wrong repository's architecture page is
    worse than showing none.
    """
    root = ((resource or {}).get("projectRoot") or (resource or {}).get("rootPath") or "").strip()
    if root:
        for pid, result in _SCANS.items():
            if result.handle.root == root:
                return pid
    return next(iter(_SCANS)) if len(_SCANS) == 1 else ""


async def _push_panel(surfaceId: str, *, create: bool = False) -> dict:
    """Render the current panel state onto its surface."""
    state = _panel_state(surfaceId)
    result = _SCANS.get(state["projectId"])
    pages = (
        [
            {"id": p.id, "title": p.title, "parentId": p.parent_id, "content": p.content}
            for p in result.wiki.pages
        ]
        if result
        else []
    )
    active = next((p for p in pages if p["id"] == state["pageId"]), pages[0] if pages else None)
    if active:
        state["pageId"] = active["id"]

    components = build_panel(
        project_name=result.wiki.project_name if result else "RepoWiki",
        pages=pages,
        active_page=active,
        project_root=result.handle.root if result else "",
        warnings=list(result.warnings) if result else [],
        projects=[
            {"projectId": pid, "projectName": scan_result.wiki.project_name}
            for pid, scan_result in sorted(_SCANS.items())
        ],
        staleness=_FRESHNESS.get(state["projectId"]) if result else None,
        labels=_LABELS,
    )

    if create:
        await cognia.ctx.a2ui.createSurface(surfaceId, "panel", {"title": "RepoWiki"})
    await cognia.ctx.a2ui.updateComponents(surfaceId, components)
    # Surfaces are created `ready: false`; without this the panel spins forever.
    await cognia.ctx.a2ui.setReady(surfaceId)
    return {"surfaceId": surfaceId, "projectId": state["projectId"], "pageId": state["pageId"]}


@tool(
    name="repowiki_build_panel",
    description=(
        "Build the reader panel's surface. Invoked by the host when the panel "
        "is first shown for a resource."
    ),
    parameters={
        "surfaceId": {"type": "string", "required": True},
        "resource": {"type": "object", "required": False},
    },
)
async def repowiki_build_panel(surfaceId: str, resource: dict | None = None) -> dict:
    state = _panel_state(surfaceId)
    if not state["projectId"]:
        state["projectId"] = _project_for_resource(resource)
    await _resolve_locale_and_labels()
    await _refresh_freshness(state["projectId"])
    return await _push_panel(surfaceId, create=True)


@tool(
    name="repowiki_panel_context",
    description=(
        "Text the panel's side conversation is grounded in. Invoked by the "
        "host at send time."
    ),
    parameters={"resource": {"type": "object", "required": False}},
)
def repowiki_panel_context(resource: dict | None = None) -> dict:
    """A few KB, not the whole wiki.

    Decision from the design pass: the overview, the page list, and the top of
    the reading order — enough for the model to know what exists and what to
    ask for — plus the reminder that `repowiki_search` is how it gets the rest.
    Pasting every page would blow the context budget on a medium repository and
    still be worse than a search.
    """
    project_id = _project_for_resource(resource)
    result = _SCANS.get(project_id)
    if result is None:
        return {"text": "No wiki has been generated for this repository yet."}

    overview = result.wiki.get_page("index")
    lines = [
        f"# {result.wiki.project_name}",
        "",
        (overview.content if overview else "").strip(),
        "",
        "## Pages",
        *(f"- `{page.id}` — {page.title}" for page in result.wiki.pages),
        "",
        "## Entry points (dependency PageRank)",
        *(
            f"- {entry['path']} ({entry['language']}, {entry['lines']} lines)"
            for entry in reading_order(result, top=10)
        ),
        "",
        "Call `repowiki_search` for anything else; it returns cited excerpts. "
        "Call `repowiki_get_page` with a page id above to read a full page.",
    ]
    # A model answering from a wiki that no longer matches the code, without
    # saying so, is the same defect as a badge that never appears. The panel
    # already computed this; reading the cache costs nothing.
    freshness = _FRESHNESS.get(project_id)
    if freshness and freshness.get("stale"):
        lines.insert(
            1,
            f"> This wiki is out of date: {freshness.get('changedCount', 0)} file(s) "
            "changed since it was built. Say so when an answer depends on code "
            "that may have moved.",
        )
    elif freshness and not freshness.get("known"):
        lines.insert(
            1,
            "> Whether this wiki is current could not be determined "
            f"({freshness.get('reason') or 'no reason reported'}).",
        )
    return {"text": "\n".join(lines), "projectId": project_id}


@hook("onA2UIAction")
async def repowiki_panel_action(payload):
    """Clicks in the panel come back here — the return trip, still no JS.

    `onA2UIAction` is a broadcast: every plugin's hook sees every surface's
    actions, which is why the action names are namespaced and why a surface
    this plugin does not own is ignored rather than answered.
    """
    if not isinstance(payload, dict):
        return payload
    action = payload.get("action") or ""
    surface_id = payload.get("surfaceId") or ""
    if not action.startswith("repowiki:") or not surface_id.startswith("cognia-repowiki:"):
        return payload

    data = payload.get("data") or {}
    state = _panel_state(surface_id)

    if action == ACTION_OPEN_PAGE:
        state["pageId"] = str(data.get("nodeId") or state["pageId"])
        await _push_panel(surface_id)
    elif action == ACTION_SELECT_PROJECT:
        state["projectId"] = str(data.get("value") or data.get("nodeId") or "")
        state["pageId"] = "index"
        await _refresh_freshness(state["projectId"])
        await _push_panel(surface_id)
    elif action == ACTION_RESCAN:
        result = _SCANS.get(state["projectId"])
        if result:
            await repowiki_scan(result.handle.root)
            await _refresh_freshness(state["projectId"])
            await _push_panel(surface_id)
    elif action == ACTION_OPEN_CITATION:
        path = str(data.get("path") or "")
        if path:
            # The editor is the point: a citation the reader cannot open is a
            # footnote. `openFile` wants an ABSOLUTE path — a relative one
            # would resolve against whichever editor mounted last — and
            # `reveal` because this jump *is* what the user clicked.
            await cognia.ctx.editor.openFile(
                path,
                {"line": int(data.get("line") or 1), "reveal": True},
            )
    return payload
