#!/usr/bin/env node
/**
 * Regenerate src/version.ts from package.json.
 *
 * The client sends its own version in `initialize`, and the host records it in
 * the audit log. A hardcoded string there is a lie the moment the package is
 * bumped, so the constant is generated and `version.test.ts` fails the build if
 * this script was not re-run.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const manifest = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8"))
const target = join(packageRoot, "src", "version.ts")

const contents = `// Generated by scripts/sync-version.mjs. Do not edit by hand.
// Run \`node scripts/sync-version.mjs\` after changing the package version.

/** The published version of \`@cognia/agent\`, sent to the host on initialize. */
export const SDK_VERSION = ${JSON.stringify(manifest.version)}

/** The npm package name, sent to the host on initialize. */
export const SDK_PACKAGE_NAME = ${JSON.stringify(manifest.name)}
`

const existing = (() => {
  try {
    return readFileSync(target, "utf8")
  } catch {
    return null
  }
})()

if (existing === contents) {
  process.stdout.write(`[agent-sdk] version.ts already at ${manifest.version}\n`)
} else {
  writeFileSync(target, contents)
  process.stdout.write(`[agent-sdk] version.ts -> ${manifest.version}\n`)
}
