/**
 * Generate the next D1 migration for Better Auth's schema.
 *
 *   pnpm schema:generate <name>      e.g. pnpm schema:generate better_auth_schema
 *
 * D1 is reachable only from a Worker, so Better Auth's CLI cannot introspect
 * it. Instead this script replays every checked-in migration into an
 * in-memory `node:sqlite` database, asks Better Auth what the configuration
 * (`authOptions`) still needs, and writes exactly that SQL as the next
 * numbered file in `migrations/`. `test/schema-drift.test.ts` fails when a
 * configuration change was not followed by a generated migration.
 *
 * Provider credentials do not change the schema; dummies keep every plugin on.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { DatabaseSync } from "node:sqlite"

import { getMigrations } from "better-auth/db/migration"

import { authOptions } from "../src/auth"
import { readConfig } from "../src/config"

const root = resolve(import.meta.dirname, "..")
const migrationsDir = join(root, "migrations")
const name = (process.argv[2] ?? "").trim()
if (!/^[a-z0-9_]+$/.test(name)) {
  console.error("usage: pnpm schema:generate <snake_case_name>")
  process.exit(2)
}

const files = readdirSync(migrationsDir)
  .filter((file) => /^\d{4}_.+\.sql$/.test(file))
  .sort()
const db = new DatabaseSync(":memory:")
db.exec("PRAGMA foreign_keys = ON")
for (const file of files) db.exec(readFileSync(join(migrationsDir, file), "utf8"))

const config = readConfig({
  DB: undefined as never,
  SERVICE_ENV: "test",
  BASE_URL: "https://id.test",
  SYNC_AUDIENCE: "https://sync.cognia.cn",
  WEB_ORIGINS: "https://app.test",
  BETTER_AUTH_SECRETS: `1:${"x".repeat(48)}`,
  FEISHU_APP_ID: "cli_dummy",
  FEISHU_APP_SECRET: "dummy",
  GITHUB_CLIENT_ID: "dummy",
  GITHUB_CLIENT_SECRET: "dummy",
  GOOGLE_CLIENT_ID: "dummy",
  GOOGLE_CLIENT_SECRET: "dummy",
})
const { toBeCreated, toBeAdded, compileMigrations } = await getMigrations(
  authOptions(config, db as unknown as D1Database)
)
if (toBeCreated.length === 0 && toBeAdded.length === 0) {
  console.log("schema is up to date; nothing to generate")
  process.exit(0)
}
const sql = await compileMigrations()
const next = String((files.length ? Number(files.at(-1)!.slice(0, 4)) : 0) + 1).padStart(4, "0")
const target = join(migrationsDir, `${next}_${name}.sql`)
writeFileSync(
  target,
  `-- Generated by scripts/generate-schema.ts from src/auth.ts (Better Auth schema). Do not edit.\n${sql.trim()}\n`
)
console.log(
  `wrote ${target}\n  create: ${toBeCreated.map((table) => table.table).join(", ") || "-"}\n  add: ${toBeAdded.map((table) => table.table).join(", ") || "-"}`
)
