import type {
  SreLogEvidence,
  SreMetricEvidence,
  SreRunbookEvidence,
  SreTraceSpanEvidence,
} from "./evidence"

export const FIXTURE_TRACE_ID = "9aa10000000000000000000000000001"
export const FIXTURE_REQUEST_ID = "req_timeout_001"
export const FIXTURE_START = "2026-08-04T12:02:00.000Z"
export const FIXTURE_END = "2026-08-04T12:05:20.000Z"

export const FIXTURE_ALERT = {
  time: "2026-08-04T12:02:10.003Z",
  severity: "warning",
  service: "gateway",
  message: "gateway provider timeout and fallback increased",
  provider: "qwen-vllm-a",
  model: "qwen3-32b",
}

export const LOG_EVIDENCE: SreLogEvidence[] = [
  {
    id: "log_001",
    source: "logs",
    sourceKind: "json",
    time: "2026-08-04T12:02:09.113Z",
    service: "gateway",
    component: "gateway",
    level: "info",
    eventName: "request.accepted",
    traceId: FIXTURE_TRACE_ID,
    requestId: FIXTURE_REQUEST_ID,
    raw: {
      ts: "2026-08-04T12:02:09.113Z",
      level: "info",
      service: "gateway",
      event: "request.accepted",
      trace_id: FIXTURE_TRACE_ID,
      request_id: FIXTURE_REQUEST_ID,
      tenant_id: "t-001",
      user_id: "u-123",
      api_key_id: "ak_789",
      surface: "responses",
      model: "qwen3-32b",
      stream: true,
    },
    parsed: { model: "qwen3-32b", surface: "responses", stream: true },
  },
  {
    id: "log_002",
    source: "logs",
    sourceKind: "json",
    time: "2026-08-04T12:02:09.121Z",
    service: "gateway",
    component: "router",
    level: "info",
    eventName: "route.selected",
    traceId: FIXTURE_TRACE_ID,
    requestId: FIXTURE_REQUEST_ID,
    raw: {
      ts: "2026-08-04T12:02:09.121Z",
      level: "info",
      service: "gateway",
      event: "route.selected",
      trace_id: FIXTURE_TRACE_ID,
      model: "qwen3-32b",
      strategy: "least_gpu_cache",
      candidates: ["qwen-vllm-a", "qwen-vllm-b"],
      selected_provider: "qwen-vllm-a",
      reason: "lowest_load",
    },
    parsed: { provider: "qwen-vllm-a", strategy: "least_gpu_cache" },
  },
  {
    id: "log_003",
    source: "logs",
    sourceKind: "json",
    time: "2026-08-04T12:02:54.305Z",
    service: "gateway",
    component: "provider",
    level: "error",
    eventName: "provider.timeout",
    traceId: FIXTURE_TRACE_ID,
    requestId: FIXTURE_REQUEST_ID,
    raw: {
      ts: "2026-08-04T12:02:54.305Z",
      level: "error",
      service: "gateway",
      event: "provider.timeout",
      trace_id: FIXTURE_TRACE_ID,
      provider: "qwen-vllm-a",
      model: "qwen3-32b",
      error_class: "timeout",
      attempt: 1,
      upstream_latency_ms: 45184,
    },
    parsed: { provider: "qwen-vllm-a", errorClass: "timeout", attempt: 1, latencyMs: 45184 },
  },
  {
    id: "log_004",
    source: "logs",
    sourceKind: "json",
    time: "2026-08-04T12:02:54.312Z",
    service: "gateway",
    component: "gateway",
    level: "warn",
    eventName: "provider.fallback",
    traceId: FIXTURE_TRACE_ID,
    requestId: FIXTURE_REQUEST_ID,
    raw: {
      ts: "2026-08-04T12:02:54.312Z",
      level: "warn",
      service: "gateway",
      event: "provider.fallback",
      trace_id: FIXTURE_TRACE_ID,
      from_provider: "qwen-vllm-a",
      to_provider: "qwen-vllm-b",
      error_class: "timeout",
      attempt: 2,
    },
    parsed: { fromProvider: "qwen-vllm-a", toProvider: "qwen-vllm-b", attempt: 2 },
  },
  {
    id: "log_005",
    source: "logs",
    sourceKind: "json",
    time: "2026-08-04T12:05:15.400Z",
    service: "gateway",
    component: "gateway",
    level: "info",
    eventName: "request.completed",
    traceId: FIXTURE_TRACE_ID,
    requestId: FIXTURE_REQUEST_ID,
    raw: {
      ts: "2026-08-04T12:05:15.400Z",
      level: "info",
      service: "gateway",
      event: "request.completed",
      trace_id: FIXTURE_TRACE_ID,
      response_id: "resp_timeout_001",
      provider: "qwen-vllm-b",
      status: 200,
      latency_ms: 186287,
      upstream_latency_ms: 140312,
      prompt_tokens: 60798,
      completion_tokens: 977,
      cached_tokens: 54912,
    },
    parsed: { provider: "qwen-vllm-b", status: 200, latencyMs: 186287 },
  },
  {
    id: "log_vllm_001",
    source: "logs",
    sourceKind: "text",
    time: "2026-08-04T12:02:20.000Z",
    service: "vllm-server",
    component: "vllm-scheduler",
    level: "warn",
    eventName: "vllm.queue_wait_warning",
    raw: "WARNING 08-04 12:02:20 scheduler.py:391] Sequence group waiting too long in queue",
    parsed: { symptom: "queue_wait" },
  },
]

export const TRACE_EVIDENCE: SreTraceSpanEvidence[] = [
  {
    id: "span_001",
    source: "trace",
    traceId: FIXTURE_TRACE_ID,
    spanId: "span-root",
    service: "gateway",
    component: "gateway",
    name: "POST /v1/responses",
    startTime: "2026-08-04T12:02:09.113Z",
    endTime: "2026-08-04T12:05:15.400Z",
    durationMs: 186287,
    status: "ok",
    attributes: {
      "http.route": "/v1/responses",
      "llm.model": "qwen3-32b",
      "http.status_code": 200,
    },
    raw: "POST /v1/responses service=gateway 186287ms",
  },
  {
    id: "span_002",
    source: "trace",
    traceId: FIXTURE_TRACE_ID,
    spanId: "span-provider-a",
    parentSpanId: "span-root",
    service: "gateway",
    component: "provider",
    name: "provider.call qwen-vllm-a",
    startTime: "2026-08-04T12:02:09.190Z",
    endTime: "2026-08-04T12:02:54.305Z",
    durationMs: 45115,
    status: "error",
    attributes: { "llm.provider": "qwen-vllm-a", "error.type": "timeout", attempt: 1 },
    raw: "provider.call qwen-vllm-a service=gateway 45115ms error=timeout",
  },
  {
    id: "span_003",
    source: "trace",
    traceId: FIXTURE_TRACE_ID,
    spanId: "span-vllm-enqueue",
    parentSpanId: "span-provider-a",
    service: "vllm-server",
    component: "vllm-scheduler",
    name: "vllm.scheduler.enqueue",
    startTime: "2026-08-04T12:02:09.220Z",
    endTime: "2026-08-04T12:02:11.320Z",
    durationMs: 2100,
    status: "ok",
    attributes: { "llm.provider": "qwen-vllm-a", "llm.model": "qwen3-32b" },
    raw: "vllm.scheduler.enqueue service=vllm-server 2100ms",
  },
  {
    id: "span_004",
    source: "trace",
    traceId: FIXTURE_TRACE_ID,
    spanId: "span-vllm-decode",
    parentSpanId: "span-provider-a",
    service: "vllm-server",
    component: "vllm-decode",
    name: "vllm.decode",
    startTime: "2026-08-04T12:02:12.000Z",
    endTime: "2026-08-04T12:02:54.120Z",
    durationMs: 42120,
    status: "error",
    attributes: {
      "llm.provider": "qwen-vllm-a",
      "error.type": "timeout",
      "llm.model": "qwen3-32b",
    },
    raw: "vllm.decode service=vllm-server 42120ms error=timeout",
  },
  {
    id: "span_005",
    source: "trace",
    traceId: FIXTURE_TRACE_ID,
    spanId: "span-provider-b",
    parentSpanId: "span-root",
    service: "gateway",
    component: "provider",
    name: "provider.call qwen-vllm-b",
    startTime: "2026-08-04T12:02:54.340Z",
    endTime: "2026-08-04T12:05:14.652Z",
    durationMs: 140312,
    status: "ok",
    attributes: { "llm.provider": "qwen-vllm-b", attempt: 2, "http.status_code": 200 },
    raw: "provider.call qwen-vllm-b service=gateway 140312ms ok",
  },
]

export const METRIC_EVIDENCE: SreMetricEvidence[] = [
  {
    id: "metric_001",
    source: "metrics",
    job: "gateyes-gateway",
    metric: "gateway_llm_fallbacks_total",
    timeRange: [FIXTURE_START, FIXTURE_END],
    service: "gateway",
    labels: { from_provider: "qwen-vllm-a", to_provider: "qwen-vllm-b", reason: "timeout" },
    value: 17,
    valueKind: "counter_delta",
    interpretation: "fallback_spike",
    raw: 'gateway_llm_fallbacks_total{from_provider="qwen-vllm-a",to_provider="qwen-vllm-b",reason="timeout"} 17',
  },
  {
    id: "metric_002",
    source: "metrics",
    job: "vllm",
    metric: "vllm:num_requests_waiting",
    timeRange: [FIXTURE_START, FIXTURE_END],
    service: "vllm-server",
    labels: { model_name: "Qwen/Qwen3-32B" },
    value: 3,
    unit: "requests",
    valueKind: "gauge",
    interpretation: "queue_pressure",
    raw: 'vllm:num_requests_waiting{model_name="Qwen/Qwen3-32B"} 3',
  },
  {
    id: "metric_003",
    source: "metrics",
    job: "vllm",
    metric: "vllm:gpu_cache_usage_perc",
    timeRange: [FIXTURE_START, FIXTURE_END],
    service: "vllm-server",
    labels: { model_name: "Qwen/Qwen3-32B" },
    value: 0.72,
    valueKind: "gauge",
    interpretation: "gpu_cache_pressure",
    raw: 'vllm:gpu_cache_usage_perc{model_name="Qwen/Qwen3-32B"} 0.72',
  },
]

export const RUNBOOK_EVIDENCE: SreRunbookEvidence[] = [
  {
    id: "runbook_001",
    source: "runbook",
    title: "qwen-vLLM timeout fallback runbook",
    service: "gateway",
    raw: [
      "# qwen-vLLM timeout fallback runbook",
      "- Check vLLM waiting queue and decode latency before changing fallback thresholds.",
      "- Confirm fallback provider health before raising upstream timeout.",
      "- Do not restart or scale production from the SRE Agent.",
    ].join("\n"),
    parsed: { provider: "qwen-vllm-a", remediation: "read_only_diagnosis" },
  },
]
