import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import { build } from "esbuild"
import JSZip from "jszip"

const pluginRoot = dirname(fileURLToPath(import.meta.url))

/**
 * Local-only state that must never reach the install ZIP even if someone
 * hand-edits `bundle_include`: dependencies installed by the Pi package
 * `prepare` step, the provisioned toolchain (~2.9 GB) and render helper, and
 * workbench state directories.
 */
export const FORBIDDEN_BUNDLE_SEGMENTS = Object.freeze([
  "node_modules",
  ".latexwb",
  ".latexwb-materialize",
])
export const FORBIDDEN_BUNDLE_PREFIXES = Object.freeze([
  "vendor/runtime/toolchain/",
  "vendor/runtime/render/",
  "dist/",
])

/** Refuse allowlist entries that are absolute, escape the plugin, or name local-only state. Pure. */
export function assertBundleAllowlist(entries) {
  for (const entry of entries) {
    if (entry.startsWith("/") || /^[A-Za-z]:/.test(entry) || entry.split("/").includes("..")) {
      throw new Error(`bundle_include entry escapes the plugin directory: ${entry}`)
    }
    if (
      entry.split("/").some((segment) => FORBIDDEN_BUNDLE_SEGMENTS.includes(segment)) ||
      FORBIDDEN_BUNDLE_PREFIXES.some((prefix) => entry.startsWith(prefix))
    ) {
      throw new Error(`bundle_include entry names local-only state: ${entry}`)
    }
  }
}

/**
 * Build the standalone CommonJS entry and the explicitly allowlisted install
 * ZIP: plugin.json, the compiled `main`, and exactly the `bundle_include`
 * files (docs, `pi/` glue, `skills/`, the untouched `vendor/` snapshot).
 * The allowlist itself is generated by `scripts/sync-vendor.mjs`.
 */
export async function buildPlugin({ outputDirectory = resolve(pluginRoot, "dist") } = {}) {
  const manifestBytes = await readFile(resolve(pluginRoot, "plugin.json"))
  const manifest = JSON.parse(manifestBytes.toString("utf8"))
  assertBundleAllowlist(manifest.bundle_include)
  const result = await build({
    entryPoints: [resolve(pluginRoot, "src/index.ts")],
    bundle: true,
    format: "cjs",
    platform: "neutral",
    target: "es2022",
    // The host loader hands out its own `@cognia/plugin-sdk` instance
    // (`lib/plugin/core/shared-modules.ts`); inlining it would bundle the
    // host's capability layer into the plugin.
    external: ["@cognia/plugin-sdk"],
    write: false,
  })
  const bundle = result.outputFiles[0].contents
  const archive = new JSZip()
  const fileOptions = { date: new Date("1980-01-01T00:00:00Z"), createFolders: false }
  archive.file("plugin.json", manifestBytes, fileOptions)
  archive.file(manifest.main, bundle, fileOptions)
  for (const name of manifest.bundle_include) {
    // The CLI entry carries a shebang and an executable bit upstream; ZIP
    // installs do not need it (`node <file>` runs it), so modes are not kept.
    archive.file(name, await readFile(resolve(pluginRoot, name)), fileOptions)
  }
  const zipBytes = await archive.generateAsync({ type: "nodebuffer", compression: "DEFLATE" })
  await mkdir(outputDirectory, { recursive: true })
  const entryPath = resolve(outputDirectory, "index.js")
  const archivePath = resolve(outputDirectory, `${manifest.id}-${manifest.version}.zip`)
  await writeFile(entryPath, bundle)
  await writeFile(archivePath, zipBytes)
  return { entryPath, archivePath }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  buildPlugin()
    .then(({ archivePath }) => {
      console.log(`Built ${archivePath}`)
    })
    .catch((error) => {
      console.error(error)
      process.exitCode = 1
    })
}
