import * as sdk from "./index"
import type { AuthSession, ParsedDeepLink, PkceFlowConfig, PkceTokenResult } from "./index"

const rootBarrel = sdk as Record<string, unknown>

describe("plugin-sdk root barrel", () => {
  it("re-exports the legacy define helper surface from the package root", () => {
    const helperExports = [
      "defineMcpServerPreset",
      "defineNativeAnthropicTool",
      "defineSkill",
      "defineSubagent",
      "defineAgentTeamTemplate",
      "defineCharacterPack",
      "defineWorkflowTemplate",
      "defineAgentTool",
      "defineTool",
      "defineGuardrail",
      "defineContextProvider",
      "defineA2UIComponent",
      "defineA2UITemplate",
      "defineAiProvider",
      "defineCliTool",
      "defineCommand",
      "defineLspServer",
      "defineMode",
      "defineOcrProvider",
      "defineScheduledTask",
      "defineWorkspaceBackend",
      "defineMessageRenderer",
      "defineDensityPreset",
      "defineChatMiddleware",
      "defineModalMount",
      "defineTerminalCompletionProvider",
      "defineRoutingStrategy",
      "defineDeploymentFilter",
      "defineProtocolAdapter",
      "defineToolRoute",
      "defineViewContainer",
      "defineView",
      "defineTreeDataProvider",
      "defineWebview",
      "defineAuthProvider",
      "defineUriHandler",
      "defineTheme",
      "defineThemePack",
      "defineFontContribution",
      "defineWallpaper",
      "defineConnector",
      "defineWorkflowNode",
      "defineWorkflowTrigger",
      "defineExporter",
      "defineImporter",
      "defineConfiguration",
      "defineQuickAction",
      "defineExternalAgentPreset",
      "defineExternalAgentAdapter",
      "defineSharedMemoryAdapter",
      "defineBalanceAdapter",
      "defineLimitsSource",
      "defineImRateSource",
      "defineCompactionStrategy",
      "defineTrayItem",
    ]

    for (const helperExport of helperExports) {
      expect(typeof rootBarrel[helperExport]).toBe("function")
    }
  })

  it("keeps auth and agent SDK convenience exports on the package root", () => {
    expect(typeof sdk.runPkceAuthFlow).toBe("function")
    expect(typeof sdk.__makeSession).toBe("function")
    expect(typeof sdk.createPiiRedactionGate).toBe("function")
    expect(typeof sdk.createPiiOutputGuardrail).toBe("function")
  })

  it("re-exports registry-backed capability API functions from the package root", () => {
    const registryExports = [
      "registerBalanceAdapter",
      "unregisterBalanceAdaptersByPlugin",
      "listBalanceAdapterEntries",
      "registerLimitsSource",
      "unregisterLimitsSourcesByPlugin",
      "listLimitsSourceEntries",
      "registerImRateSource",
      "unregisterImRateSourcesByPlugin",
      "listImRateSourceEntries",
      "registerCompactionStrategy",
      "unregisterCompactionStrategiesByPlugin",
      "listCompactionStrategyEntries",
      "registerSharedMemoryAdapter",
      "unregisterSharedMemoryAdaptersByPlugin",
      "listSharedMemoryAdapterEntries",
      "registerQuickAction",
      "listQuickActions",
      "dispatchUri",
      "registerUriHandler",
      "registerAuthenticationProvider",
      "getSession",
      "registerMessagePartRenderer",
      "listMessagePartRenderers",
      "registerViewContainer",
      "getViewContainerSnapshot",
      "registerView",
      "listViewsForContainer",
      "registerWebview",
      "postMessageToWebview",
      "registerRoutingStrategy",
      "listRoutingStrategies",
      "registerDeploymentFilter",
      "listDeploymentFilters",
      "registerProtocolAdapter",
      "listProtocolAdapters",
      "registerToolRoutesForPlugin",
      "makeToolRouteId",
      "registerTerminalCompletionProvider",
      "listTerminalCompletionProviders",
      "getTerminalCompletions",
      "registerTerminalCompletionProvidersForPlugin",
      "registerPluginCommandRules",
      "getPluginCommandRulesets",
      "classifyCommandSafety",
      "registerWorkspaceBackendsForPlugin",
      "registerWorkspaceBackend",
      "createWorkspaceAPI",
      "registerModalMountsForPlugin",
      "registerDeclaredModal",
      "createModalAPI",
      "registerTrayItem",
      "listTrayItems",
      "createTrayAPI",
      "registerPluginTheme",
      "listPluginThemes",
      "registerThemePack",
      "listThemePacks",
      "applyPluginFonts",
      "listFonts",
      "applyPluginWallpapers",
      "listPluginWallpapers",
      "registerDensityPreset",
      "applyDensityPresetVars",
      "registerAiProvidersForPlugin",
      "unregisterAiProvidersForPlugin",
      "createAIProviderAPI",
      "getCustomAIProviders",
      "registerOcrProvidersForPlugin",
      "unregisterOcrProvidersForPlugin",
      "createOcrAPI",
      "clearOcrProvidersForPlugin",
      "registerOcrProvider",
      "createOcrRegistry",
      "registerNodeExecutor",
      "unregisterNodeExecutor",
      "getExecutor",
      "listRegisteredKinds",
      "subscribeNodeRegistry",
      "registerPluginTrigger",
      "unregisterPluginTrigger",
      "getPluginTrigger",
      "listPluginTriggers",
      "startPluginTriggerInstance",
      "subscribePluginTriggerRegistry",
      "setTriggerMuted",
      "isTriggerMuted",
      "subscribeTriggerMuteChanges",
      "createExportAPI",
      "clearCustomExporters",
      "createImportAPI",
      "clearCustomImporters",
      "registerChatMiddlewaresForPlugin",
      "unregisterChatMiddlewaresForPlugin",
      "createChatAPI",
      "clearChatMiddlewaresForPluginContext",
      "registerChatMiddleware",
      "unregisterChatMiddleware",
      "clearChatMiddlewaresForPlugin",
      "listActiveChatMiddlewares",
      "listAllChatMiddlewares",
      "getChatMiddleware",
      "recordMiddlewareFailure",
      "recordMiddlewareSuccess",
      "resetChatMiddlewareBreaker",
      "subscribeChatMiddlewareRegistry",
      "executeCliTool",
      "registerCommand",
      "unregisterCommand",
      "unregisterCommandsByPlugin",
      "getCommand",
      "getCommands",
      "listCommandsByPlugin",
      "executeCommand",
      "subscribeCommandRegistry",
      "registerExternalAgentAdaptersForPlugin",
      "unregisterExternalAgentAdaptersForPlugin",
      "registerPluginProtocolAdapter",
      "unregisterPluginProtocolAdaptersByPlugin",
      "getPluginProtocolAdapterOwner",
      "getPluginProtocolAdapterProtocols",
      "listPluginProtocolAdapters",
      "onProtocolAdapterRegistryChange",
      "registerExternalAgentPreset",
      "unregisterExternalAgentPreset",
      "unregisterExternalAgentPresetsByPlugin",
      "getDynamicExternalAgentPresetEntry",
      "listDynamicExternalAgentPresetEntries",
      "listExternalAgentPresetIds",
      "getExternalAgentPresetConfig",
      "createAgentFromPreset",
      "isFromPreset",
      "configureLspRegistry",
      "registerLspServer",
      "unregisterLspServer",
      "unregisterByOwner",
      "listLspServers",
      "getLspServerForLanguage",
      "registerPluginLspServers",
      "lspServerKey",
      "getAgentMode",
      "getAgentModeByType",
      "toTaskTrigger",
      "registerScheduledTasksForPlugin",
      "unregisterScheduledTasksForPlugin",
      "registerScheduledTaskDefsForPlugin",
      "unregisterScheduledTaskDefsByPlugin",
      "listScheduledTaskDefs",
      "subscribeScheduledTaskDefs",
      "registerPluginTaskHandler",
      "unregisterPluginTaskHandler",
      "getPluginTaskHandler",
      "hasPluginTaskHandler",
      "getPluginTaskHandlerNames",
      "clearPluginTaskHandlers",
    ]

    for (const registryExport of registryExports) {
      expect(typeof rootBarrel[registryExport]).toBe("function")
    }
  })

  it("exposes the legacy type-only auth and deep-link contracts", () => {
    const assertSdkTypes = <
      _T extends ParsedDeepLink | PkceFlowConfig | PkceTokenResult | AuthSession,
    >(): void => undefined

    expect(assertSdkTypes).toBeDefined()
  })
})
