/**
 * `@cognia/plugin-sdk` — root barrel.
 *
 * Convenience surface that re-exports every subpath. Plugin authors who
 * want to pick a single import path can write
 *   import { definePlugin, defineNativeAnthropicTool } from "@cognia/plugin-sdk"
 * but the recommended pattern is to import from the specific subpath
 * (`@cognia/plugin-sdk/manifest`, `/context`, `/api/...`, etc.) so the
 * bundled type surface stays narrow.
 *
 * The SDK owns the `define-*` authoring helpers and re-exports the host
 * runtime registries, messaging contracts, plugin point contracts, and
 * canonical plugin type tree. See `README.md` for the subpath table.
 */

export * from "./manifest"
export * from "./context"
export * from "./api/native-anthropic-tool"
export * from "./api/skill"
export * from "./api/mcp-server-preset"
export * from "./api/connector"
export * from "./api/character-pack"
export * from "./api/workflow"
export * from "./api/subagent"
export * from "./api/agent-team-template"
export * from "./api/workflow-template"
export * from "./api/agent-tool"
export * from "./api/guardrail"
export * from "./api/context-provider"
export * from "./api/balance-adapter"
export * from "./api/compaction-strategy"
export * from "./api/im-rate-source"
export * from "./api/limits-source"
export * from "./api/shared-memory-adapter"
export * from "./api/auth-provider"
export * from "./api/message-renderer"
export * from "./api/quick-action"
export * from "./api/uri-handler"
export * from "./api/view-container"
export * from "./api/view"
export * from "./api/webview"
export * from "./api/routing-strategy"
export * from "./api/deployment-filter"
export * from "./api/protocol-adapter"
export * from "./api/tool-route"
export * from "./api/terminal-completion"
export * from "./api/command-safety"
export * from "./api/workspace-backend"
export * from "./api/modal-mount"
export * from "./api/tray-item"
export * from "./api/theme"
export * from "./api/theme-pack"
export * from "./api/font-contribution"
export * from "./api/wallpaper"
export * from "./api/density-preset"
export * from "./api/ai-provider"
export * from "./api/ocr-provider"
export * from "./api/pet"
export * from "./api/workflow-node"
export * from "./api/workflow-trigger"
export * from "./api/exporter"
export * from "./api/importer"
export * from "./api/a2ui-component"
export * from "./api/a2ui-template"
export * from "./api/chat-middleware"
export * from "./api/cli-tool"
export * from "./api/command"
export * from "./api/configuration"
export * from "./api/external-agent-adapter"
export * from "./api/external-agent-preset"
export * from "./api/lsp-server"
export * from "./api/mode"
export * from "./api/scheduled-task"
export * from "./api/tool"
export * from "./events"
export * from "./hooks"
export * from "./permissions"
export * from "./extensions"
export * from "./contracts"

export { defineMcpServerPreset } from "./define/define-mcp-server-preset"
export { defineNativeAnthropicTool } from "./define/define-native-anthropic-tool"
export { defineSkill } from "./define/define-skill"
export { defineSubagent } from "./define/define-subagent"
export { defineAgentTeamTemplate } from "./define/define-agent-team-template"
export { defineCharacterPack } from "./define/define-character-pack"
export { defineWorkflowTemplate } from "./define/define-workflow-template"
export { defineAgentTool } from "./define/define-agent-tool"
export { defineTool } from "./define/define-tool"
export { defineGuardrail } from "./define/define-guardrail"
export { defineContextProvider } from "./define/define-context-provider"
export { defineA2UIComponent } from "./define/define-a2ui-component"
export { defineA2UITemplate } from "./define/define-a2ui-template"
export { defineAiProvider } from "./define/define-ai-provider"
export { defineCliTool } from "./define/define-cli-tool"
export { defineCommand } from "./define/define-command"
export { defineLspServer } from "./define/define-lsp-server"
export { defineMode } from "./define/define-mode"
export { defineOcrProvider } from "./define/define-ocr-provider"
export { definePetAchievement } from "./define/define-pet-achievement"
export { definePetItem } from "./define/define-pet-item"
export { defineScheduledTask } from "./define/define-scheduled-task"
export { defineWorkspaceBackend } from "./define/define-workspace-backend"
export { defineMessageRenderer } from "./define/define-message-renderer"
export { defineDensityPreset } from "./define/define-density-preset"
export { defineChatMiddleware } from "./define/define-chat-middleware"
export { defineModalMount } from "./define/define-modal-mount"
export { defineTerminalCompletionProvider } from "./define/define-terminal-completion"
export { defineRoutingStrategy } from "./define/define-routing-strategy"
export { defineDeploymentFilter } from "./define/define-deployment-filter"
export { defineProtocolAdapter } from "./define/define-protocol-adapter"
export { defineToolRoute } from "./define/define-tool-route"
export { defineViewContainer } from "./define/define-view-container"
export { defineView, defineTreeDataProvider } from "./define/define-view"
export type { TreeDataProvider, PluginTreeNode, PluginViewProps } from "@/types/plugin/plugin-view"
export { defineWebview } from "./define/define-webview"
export type { PluginWebviewHandle, PluginWebviewMessage } from "@/types/plugin/plugin-webview"
export { defineAuthProvider } from "./define/define-auth-provider"
export { defineUriHandler } from "./define/define-uri-handler"
export { defineTheme } from "./define/define-theme"
export { defineThemePack } from "./define/define-theme-pack"
export { defineFontContribution } from "./define/define-font-contribution"
export { defineWallpaper } from "./define/define-wallpaper"
export { defineConnector } from "./define/define-connector"
export { defineWorkflowNode } from "./define/define-workflow-node"
export { defineWorkflowTrigger } from "./define/define-workflow-trigger"
export { defineExporter } from "./define/define-exporter"
export { defineImporter } from "./define/define-importer"
export { defineConfiguration } from "./define/define-configuration"
export { defineQuickAction } from "./define/define-quick-action"
export { defineExternalAgentPreset } from "./define/define-external-agent-preset"
export { defineExternalAgentAdapter } from "./define/define-external-agent-adapter"
export { defineSessionImporter } from "./define/define-session-importer"
export { defineSharedMemoryAdapter } from "./define/define-shared-memory-adapter"
export { defineBalanceAdapter } from "./define/define-balance-adapter"
export { defineLimitsSource } from "./define/define-limits-source"
export { defineImRateSource } from "./define/define-im-rate-source"
export { defineCompactionStrategy } from "./define/define-compaction-strategy"
export { defineTrayItem } from "./define/define-tray-item"
export type { ParsedDeepLink } from "@/lib/plugin/uri/parse-deep-link"
export { runPkceAuthFlow } from "@/lib/plugin/auth/auth-pkce-flow"
export type { PkceFlowConfig, PkceTokenResult } from "@/lib/plugin/auth/auth-pkce-flow"
export { __makeSession } from "@/lib/plugin/auth/auth-provider-registry"
export type { AuthSession } from "@/lib/plugin/auth/auth-provider-registry"
export { createPiiRedactionGate } from "@/lib/plugin/agent-sdk/pii-gate"
export { createPiiOutputGuardrail } from "@/lib/plugin/agent-sdk/guardrails"
