/**
 * Plugin config codegen (Raycast-style typed config accessors).
 *
 * Given a plugin manifest's `configSchema` (the
 * `{ type: "object", properties, required }` shape from
 * `types/plugin/plugin.ts:PluginConfigSchema`), generate a typed view of the
 * plugin's persisted config for both SDKs:
 *
 *   - TypeScript: a `PluginConfig` interface + `asPluginConfig()` cast helper
 *     + `CONFIG_DEFAULTS`, written to `config.generated.ts`.
 *   - Python:     a `PluginConfig` TypedDict + `as_plugin_config()` helper +
 *     `CONFIG_DEFAULTS`, written to `config_generated.py`.
 *
 * Pure string builders (no fs) so they unit-test without a filesystem; the
 * CLI wrapper (`plugin-codegen.mjs`) wires them to disk.
 */

const GENERATED_HEADER_TS =
  "// AUTO-GENERATED by `pnpm plugin:codegen` from plugin.json#configSchema.\n" +
  "// Do not edit by hand — re-run codegen after changing the manifest.\n"

const GENERATED_HEADER_PY =
  "# AUTO-GENERATED by `pnpm plugin:codegen` from plugin.json#configSchema.\n" +
  "# Do not edit by hand — re-run codegen after changing the manifest.\n"

/** Map one config property to a TypeScript type expression. */
export function tsTypeForProperty(prop) {
  if (!prop || typeof prop !== "object") return "unknown"
  if (Array.isArray(prop.enum) && prop.enum.length > 0) {
    return prop.enum.map((value) => JSON.stringify(value)).join(" | ")
  }
  switch (prop.type) {
    case "string":
      return "string"
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "array":
      return prop.items ? `${tsTypeForProperty(prop.items)}[]` : "unknown[]"
    case "object":
      if (prop.properties && Object.keys(prop.properties).length > 0) {
        const fields = Object.entries(prop.properties)
          .map(([key, child]) => `${tsPropKey(key)}: ${tsTypeForProperty(child)}`)
          .join("; ")
        return `{ ${fields} }`
      }
      return "Record<string, unknown>"
    default:
      return "unknown"
  }
}

/** Map one config property to a Python type expression. */
export function pyTypeForProperty(prop) {
  if (!prop || typeof prop !== "object") return "Any"
  if (Array.isArray(prop.enum) && prop.enum.length > 0) {
    return `Literal[${prop.enum.map((value) => pyLiteral(value)).join(", ")}]`
  }
  switch (prop.type) {
    case "string":
      return "str"
    case "number":
      return "float"
    case "boolean":
      return "bool"
    case "array":
      return prop.items ? `List[${pyTypeForProperty(prop.items)}]` : "List[Any]"
    case "object":
      // Nested objects collapse to a plain dict to avoid TypedDict explosion;
      // the top-level shape is what authors read.
      return "Dict[str, Any]"
    default:
      return "Any"
  }
}

function tsPropKey(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
}

function pyLiteral(value) {
  if (typeof value === "string") return JSON.stringify(value)
  if (value === true) return "True"
  if (value === false) return "False"
  if (value === null) return "None"
  return String(value)
}

/** Split a config schema into ordered [key, prop, required] tuples. */
function schemaEntries(configSchema) {
  const properties = (configSchema && configSchema.properties) || {}
  const required = new Set((configSchema && configSchema.required) || [])
  return Object.entries(properties).map(([key, prop]) => [key, prop, required.has(key)])
}

/** Collect default values declared on the schema's top-level properties. */
function collectDefaults(configSchema) {
  const out = {}
  for (const [key, prop] of schemaEntries(configSchema)) {
    if (prop && Object.prototype.hasOwnProperty.call(prop, "default")) {
      out[key] = prop.default
    }
  }
  return out
}

/** Generate the TypeScript `config.generated.ts` body. */
export function generateTsConfig(configSchema) {
  const entries = schemaEntries(configSchema)
  const lines = [GENERATED_HEADER_TS, ""]

  if (entries.length === 0) {
    lines.push("export type PluginConfig = Record<string, never>")
  } else {
    lines.push("export interface PluginConfig {")
    for (const [key, prop, required] of entries) {
      const desc = prop && (prop.description || prop.title)
      if (desc) lines.push(`  /** ${String(desc).replace(/\*\//g, "*\\/")} */`)
      lines.push(`  ${tsPropKey(key)}${required ? "" : "?"}: ${tsTypeForProperty(prop)}`)
    }
    lines.push("}")
  }

  lines.push("")
  lines.push("/** Typed view of the plugin's persisted config (e.g. ctx.settings values). */")
  lines.push("export function asPluginConfig(config: Record<string, unknown>): PluginConfig {")
  lines.push("  return config as PluginConfig")
  lines.push("}")

  const defaults = collectDefaults(configSchema)
  lines.push("")
  lines.push("/** Default values declared in the manifest's configSchema. */")
  lines.push(
    `export const CONFIG_DEFAULTS: Partial<PluginConfig> = ${JSON.stringify(defaults, null, 2)}`
  )

  return lines.join("\n") + "\n"
}

/** Generate the Python `config_generated.py` body. */
export function generatePyConfig(configSchema) {
  const entries = schemaEntries(configSchema)
  const required = entries.filter(([, , isReq]) => isReq)
  const optional = entries.filter(([, , isReq]) => !isReq)

  const lines = [GENERATED_HEADER_PY, "", "from __future__ import annotations", ""]
  lines.push("from typing import Any, Dict, List, Literal, TypedDict", "")

  if (entries.length === 0) {
    lines.push("class PluginConfig(TypedDict, total=False):", "    pass")
  } else if (required.length > 0 && optional.length > 0) {
    // Mixed required/optional → base (total=True) + derived (total=False),
    // the 3.9-compatible idiom (NotRequired is 3.11+).
    lines.push("class _PluginConfigRequired(TypedDict):")
    for (const [key, prop] of required) lines.push(`    ${key}: ${pyTypeForProperty(prop)}`)
    lines.push("")
    lines.push("class PluginConfig(_PluginConfigRequired, total=False):")
    for (const [key, prop] of optional) lines.push(`    ${key}: ${pyTypeForProperty(prop)}`)
  } else if (optional.length === 0) {
    lines.push("class PluginConfig(TypedDict):")
    for (const [key, prop] of required) lines.push(`    ${key}: ${pyTypeForProperty(prop)}`)
  } else {
    lines.push("class PluginConfig(TypedDict, total=False):")
    for (const [key, prop] of optional) lines.push(`    ${key}: ${pyTypeForProperty(prop)}`)
  }

  lines.push("")
  lines.push('def as_plugin_config(config: Dict[str, Any]) -> "PluginConfig":')
  lines.push('    """Typed view of the plugin\'s persisted config (cognia.get_config())."""')
  lines.push("    return config  # type: ignore[return-value]")

  const defaults = collectDefaults(configSchema)
  lines.push("")
  lines.push("#: Default values declared in the manifest's configSchema.")
  lines.push(`CONFIG_DEFAULTS: Dict[str, Any] = ${pyDict(defaults)}`)

  return lines.join("\n") + "\n"
}

/** Render a JSON-ish object as a Python dict literal. */
function pyDict(obj) {
  const keys = Object.keys(obj)
  if (keys.length === 0) return "{}"
  const body = keys.map((key) => `    ${JSON.stringify(key)}: ${pyValue(obj[key])},`).join("\n")
  return `{\n${body}\n}`
}

function pyValue(value) {
  if (Array.isArray(value)) return `[${value.map(pyValue).join(", ")}]`
  if (value && typeof value === "object") return pyDict(value)
  return pyLiteral(value)
}

/**
 * Build the generated artifacts for a manifest. Returns a file map keyed by
 * the path relative to the plugin dir. The Python artifact is emitted only for
 * python-type plugins; the TS artifact for everything else.
 */
export function generateConfigArtifacts(manifest) {
  const configSchema = manifest && manifest.configSchema
  const isPython = manifest && manifest.type === "python"
  return isPython
    ? { "config_generated.py": generatePyConfig(configSchema) }
    : { "config.generated.ts": generateTsConfig(configSchema) }
}
