#!/usr/bin/env node
/**
 * `pnpm plugin:create` — scaffold a new Cognia plugin (TypeScript or Python).
 *
 * The pure core `buildPluginFiles(options)` returns a `{ relPath: content }`
 * file map (manifest + entry + co-located test + generated config types) so it
 * unit-tests without a filesystem. The CLI `main()` collects options from
 * flags / interactive prompts and writes the map to disk.
 *
 * Templates:
 *   - frontend (TypeScript): plugin.json + src/index.ts + src/index.test.ts
 *   - python:               plugin.json + main.py   + test_main.py
 * Both get a generated `config.generated.ts` / `config_generated.py` when the
 * manifest carries a `configSchema` (reused from `config-codegen.mjs`).
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { createInterface } from "node:readline/promises"
import { stdin, stdout } from "node:process"
import { pathToFileURL } from "node:url"

import { generateConfigArtifacts } from "./config-codegen.mjs"

/** Convert an arbitrary name to a kebab-case plugin id. */
export function slugify(value) {
  return String(value)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

const PLUGIN_TYPES = new Set(["frontend", "python"])

/** A sample config schema so a fresh plugin demonstrates the codegen wiring. */
export const SAMPLE_CONFIG_SCHEMA = {
  type: "object",
  properties: {
    greeting: {
      type: "string",
      title: "Greeting",
      description: "Prefix used by the greet tool.",
      default: "Hello",
    },
    shout: {
      type: "boolean",
      title: "Shout",
      description: "Uppercase every greeting.",
      default: false,
    },
  },
}

/** Fill defaults + validate. Returns a normalized options object. */
export function normalizeOptions(options = {}) {
  const name = (options.name || "").trim() || "My Plugin"
  const id = slugify(options.id || name) || "my-plugin"
  const type = options.type || "frontend"
  if (!PLUGIN_TYPES.has(type)) {
    throw new Error(`unknown plugin type "${type}" — expected "frontend" or "python"`)
  }
  const capabilities =
    options.capabilities && options.capabilities.length > 0 ? options.capabilities : ["tools"]
  const withConfig = options.withConfig !== false
  return {
    id,
    name,
    description: options.description || `${name} — a Cognia plugin.`,
    type,
    capabilities,
    author: options.author || "you",
    license: options.license || "MIT",
    configSchema: withConfig ? options.configSchema || SAMPLE_CONFIG_SCHEMA : undefined,
  }
}

function buildManifest(opts) {
  const base = {
    id: opts.id,
    name: opts.name,
    version: "0.1.0",
    description: opts.description,
    type: opts.type,
    capabilities: opts.capabilities,
    author: opts.author,
    license: opts.license,
    engines:
      opts.type === "python" ? { cognia: ">=0.1.0", python: ">=3.9" } : { cognia: ">=0.1.0" },
  }
  if (opts.type === "python") {
    base.pythonMain = "main.py"
    base.permissions = ["python:execute"]
  } else {
    base.main = "src/index.ts"
    base.activationEvents = ["startup"]
  }
  if (opts.configSchema) base.configSchema = opts.configSchema
  base.runtimeCompatibility =
    opts.type === "python"
      ? {
          tauri: { availability: "supported" },
          browser: {
            availability: "blocked",
            reason: "Python plugins run in the desktop subprocess host.",
          },
        }
      : {
          browser: { availability: "supported", entrypoint: "src/index.ts" },
          tauri: { availability: "supported", entrypoint: "src/index.ts" },
        }
  return base
}

function frontendIndex(opts) {
  const hasConfig = Boolean(opts.configSchema)
  const configImport = hasConfig ? '\nimport { asPluginConfig } from "./config.generated"\n' : ""
  const configHint = hasConfig
    ? "\n    // Typed config: const config = asPluginConfig(/* raw config object */)\n" +
      "    void asPluginConfig\n"
    : ""
  return `/**
 * ${opts.name} — Cognia plugin.
 *
 * Generated by \`pnpm plugin:create\`. Implement \`activate()\` to register
 * tools, commands, or other capability contributions via \`ctx\`.
 */

import { definePlugin } from "@cognia/plugin-sdk/manifest"
import type { PluginManifest } from "@cognia/plugin-sdk/manifest"
${configImport}
export const manifest: PluginManifest = {
  id: "${opts.id}",
  name: ${JSON.stringify(opts.name)},
  version: "0.1.0",
  type: "frontend",
  capabilities: ${JSON.stringify(opts.capabilities)},
  main: "src/index.ts",
} as PluginManifest

export default definePlugin({
  manifest,
  activate: async (ctx) => {
    ctx.logger.info(\`\${manifest.name} activated\`)
${configHint}  },
})
`
}

function frontendEvals(opts) {
  return `# AI-tool evals for ${opts.name}. Run with \`pnpm plugin:eval <path-to-this-plugin>\`.
#
# Offline cases (default, CI) verify the tool CONTRACT against \`evals.harness.mjs\`
# (a runtime-free stand-in, since the real entry imports the app). Online cases
# (\`--online\`, run inside the app) verify the model SELECTS the right tool.
#
# Replace \`echo\` below with your plugin's real tool once you register one.
evals:
  - name: "echo returns the input"
    prompt: "Echo the word ping"
    args:
      text: "ping"
    expect:
      callsTool: echo
      output:
        includes: "ping"
`
}

function frontendEvalsHarness(opts) {
  return `/**
 * Runtime-free offline eval harness for ${opts.name}.
 *
 * \`pnpm plugin:eval\` cannot load the real entry (it imports the app), so map
 * each tool name to a deterministic stand-in here. Keep the output shape in
 * lockstep with the real tool so contract drift is caught in CI.
 *
 * @param {string} name
 * @param {Record<string, unknown>} args
 * @returns {Promise<unknown>}
 */
export async function invokeTool(name, args) {
  if (name === "echo") {
    return String(args.text ?? "")
  }
  throw new Error(\`unknown tool: \${name}\`)
}
`
}

function frontendTest(opts) {
  return `import definition from "./index"

describe("${opts.id}", () => {
  it("exposes a manifest with the expected id and capabilities", () => {
    expect(definition.manifest.id).toBe("${opts.id}")
    expect(definition.manifest.capabilities).toContain(${JSON.stringify(opts.capabilities[0])})
  })

  it("activates without throwing and logs activation", async () => {
    const logs: string[] = []
    const logger = {
      info: (m: string) => logs.push(m),
      debug: () => {},
      warn: () => {},
      error: () => {},
    }
    await definition.activate({ logger } as never)
    expect(logs.some((line) => line.includes("activated"))).toBe(true)
  })
})
`
}

function pythonMain(opts) {
  const configHint = opts.configSchema
    ? "# Typed config: `from config_generated import asPluginConfig` (see config_generated.py).\n"
    : ""
  return `"""${opts.name} — Cognia Python plugin.

Generated by \`pnpm plugin:create\`. Add \`@tool\` functions and optional
\`on_startup\` / \`on_config_updated\` / \`on_shutdown\` lifecycle hooks.
"""

${configHint}from cognia import get_config, tool


@tool(description="Greet someone using the configured greeting.")
def greet(name: str):
    greeting = get_config().get("greeting", "Hello")
    message = f"{greeting}, {name}!"
    return message.upper() if get_config().get("shout") else message
`
}

function pythonTest(opts) {
  return `"""Tests for the ${opts.id} plugin."""

import cognia
import main  # noqa: F401  (importing registers the plugin's tools)


def test_greet_uses_the_configured_greeting():
    runtime = cognia.get_active_runtime()
    runtime.push_config({"greeting": "Hi"})
    assert runtime.call_tool("greet", {"name": "world"}) == "Hi, world!"


def test_greet_can_shout():
    runtime = cognia.get_active_runtime()
    runtime.push_config({"greeting": "Yo", "shout": True})
    assert runtime.call_tool("greet", {"name": "world"}) == "YO, WORLD!"
`
}

/** Build the full file map for a new plugin (pure — no fs). */
export function buildPluginFiles(rawOptions) {
  const opts = normalizeOptions(rawOptions)
  const manifest = buildManifest(opts)
  const files = { "plugin.json": JSON.stringify(manifest, null, 2) + "\n" }

  if (opts.type === "python") {
    files["main.py"] = pythonMain(opts)
    files["test_main.py"] = pythonTest(opts)
  } else {
    files["src/index.ts"] = frontendIndex(opts)
    files["src/index.test.ts"] = frontendTest(opts)
    files["evals.yaml"] = frontendEvals(opts)
    files["evals.harness.mjs"] = frontendEvalsHarness(opts)
  }

  if (opts.configSchema) {
    Object.assign(files, generateConfigArtifacts(manifest))
  }
  return { options: opts, files }
}

/** Write a file map under targetDir. Injectable fs for tests. */
export function writePluginFiles({
  files,
  targetDir,
  mkdir = (dir) => mkdirSync(dir, { recursive: true }),
  writeFile = (path, content) => writeFileSync(path, content),
  exists = (path) => existsSync(path),
  force = false,
}) {
  const written = []
  for (const [rel, content] of Object.entries(files)) {
    const dest = join(targetDir, rel)
    if (!force && exists(dest)) {
      throw new Error(`refusing to overwrite existing file: ${dest} (pass --force to override)`)
    }
    mkdir(dirname(dest))
    writeFile(dest, content)
    written.push(dest)
  }
  return written
}

// -- CLI --------------------------------------------------------------------

function parseArgs(argv) {
  const flags = {}
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg === "--yes" || arg === "-y") flags.yes = true
    else if (arg === "--force") flags.force = true
    else if (arg === "--no-config") flags.withConfig = false
    else if (arg.startsWith("--")) {
      const key = arg.slice(2)
      const value = argv[i + 1]
      flags[key] = value
      i += 1
    }
  }
  if (typeof flags.capabilities === "string") {
    flags.capabilities = flags.capabilities
      .split(",")
      .map((c) => c.trim())
      .filter(Boolean)
  }
  return flags
}

async function promptMissing(flags) {
  if (flags.yes) return flags
  const rl = createInterface({ input: stdin, output: stdout })
  try {
    const name = flags.name || (await rl.question("Plugin name: ")) || "My Plugin"
    const type =
      flags.type || (await rl.question("Type (frontend/python) [frontend]: ")) || "frontend"
    return { ...flags, name, type }
  } finally {
    rl.close()
  }
}

async function main(argv) {
  const flags = parseArgs(argv)
  const collected = await promptMissing(flags)
  const { options, files } = buildPluginFiles(collected)
  const targetDir = resolve(flags.dir || options.id)
  const written = writePluginFiles({ files, targetDir, force: flags.force })
  console.log(`Created plugin "${options.name}" (${options.type}) in ${targetDir}:`)
  for (const path of written) console.log(`  + ${path}`)
  console.log(
    `\nNext: cd ${targetDir} && ${options.type === "python" ? "python -m pytest" : "pnpm test"}`
  )
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error.message)
    process.exitCode = 1
  })
}
