/**
 * Extract A2UI surfaces from an assistant response and project them into
 * `MessageSegment.a2ui` segments suitable for `OutboundRequest`.
 *
 * Why this lives here, not in `lib/claude/run-and-capture.ts`: the chat
 * page consumes A2UI parts as renderer-side React state, but the
 * IM-connector outbound path needs them as transferable message segments.
 * This module bridges the two — given the captured assistant reply, it
 * walks any A2UI surfaces it produced (via `a2ui_create_surface` /
 * `a2ui_update_components` tool calls) and converts each into a
 * `MessageSegment.a2ui` along with a `plainTextMirror` fallback.
 */

import type {
  A2UIMessageSegment,
  A2UISegmentContent,
  MessageSegment,
} from "@/types/connectors/segment"
import { generatePlainTextMirror } from "@/lib/connectors/adapters/_shared/a2ui-mapper"

/**
 * Minimal shape of a captured assistant reply we need to read. Kept
 * structurally compatible with `CapturedAssistantReply` from
 * `lib/claude/run-and-capture.ts` so we can accept either object directly.
 */
export interface AssistantReplyForExtraction {
  /** Plain markdown text portion of the assistant reply. */
  text: string
  /** A2UI surfaces created during this reply, keyed by surfaceId. */
  a2uiSurfaces?: Record<string, A2UISegmentContent>
  /** Surface ids in the order the assistant created/updated them. */
  a2uiSurfaceOrder?: string[]
}

/**
 * Convert the assistant's reply into a list of message segments ready for
 * the outbound runner.
 *
 *   - A2UI surfaces become {type: "a2ui"} segments in the order they were
 *     created/updated. Each segment carries a fresh `plainTextMirror`
 *     either taken from the surface's `widget.fallbackText` (when the
 *     model provided one) or generated by `generatePlainTextMirror`.
 *   - The remaining markdown text is appended as a single
 *     {type: "markdown"} segment when non-empty. Adapters that don't
 *     support markdown will degrade per their capability matrix.
 *
 * When the reply has no A2UI surfaces, the output is just
 * `[{type: "markdown", md: text}]` (or `[{type: "text", text}]` for an
 * empty/whitespace-only reply — we still want to fire the outbound so
 * the user knows the assistant responded).
 */
export function assistantReplyToSegments(reply: AssistantReplyForExtraction): MessageSegment[] {
  const segments: MessageSegment[] = []
  const surfaces = reply.a2uiSurfaces ?? {}
  const order = reply.a2uiSurfaceOrder ?? Object.keys(surfaces)

  for (const surfaceId of order) {
    const content = surfaces[surfaceId]
    if (!content) continue
    segments.push(buildA2UISegment(surfaceId, content))
  }

  const trimmed = reply.text.trim()
  if (trimmed.length > 0) {
    // Keep markdown semantics — adapters that don't render markdown will
    // degrade via `defaultDegradeChain("markdown") → ["markdown", "text"]`.
    segments.push({ type: "markdown", md: reply.text })
  } else if (segments.length === 0) {
    // Reply with no text AND no surfaces: emit an empty text segment so
    // the outbound runner has at least one segment to dispatch (it would
    // otherwise reject the OutboundRequest as malformed).
    segments.push({ type: "text", text: "" })
  }

  return segments
}

/**
 * Build a single A2UI segment from a surface payload. Used directly by
 * `lib/connectors/scheduled-outbound.ts` for surfaces emitted outside
 * the normal assistant reply path (e.g., a connector-triggered surface
 * push from a workflow node).
 */
export function buildA2UISegment(
  surfaceId: string,
  content: A2UISegmentContent
): A2UIMessageSegment {
  const widget = (content.widget ?? {}) as Record<string, unknown>
  const providedMirror = typeof widget.fallbackText === "string" ? widget.fallbackText.trim() : ""
  const plainTextMirror =
    providedMirror.length > 0 ? providedMirror : generatePlainTextMirror(content)
  return {
    type: "a2ui",
    surfaceId,
    content,
    plainTextMirror,
  }
}
