/**
 * Extract A2UI surfaces from an assistant response and project them into
 * `MessageSegment.a2ui` segments suitable for `OutboundRequest`.
 *
 * Why this lives here, not in `lib/claude/run-and-capture.ts`: the chat
 * page consumes A2UI parts as renderer-side React state, but the
 * IM-connector outbound path needs them as transferable message segments.
 * This module bridges the two — given the captured assistant reply, it
 * walks A2UI surfaces produced by tool calls or emitted as JSON in the
 * assistant's text and converts each into a
 * `MessageSegment.a2ui` along with a `plainTextMirror` fallback.
 */

import type {
  A2UIMessageSegment,
  A2UISegmentContent,
  MessageSegment,
} from "@/types/connectors/segment"
import { generatePlainTextMirror } from "@/lib/connectors/adapters/_shared/a2ui-mapper"
import { trackInboxEvent } from "@/lib/telemetry/inbox-events"
import { parseA2UIInput } from "@/lib/a2ui/parser"
import { deepMerge, isA2UIDataModel, isSafeDataModelKey } from "@/lib/a2ui/data-model"
import { getComponentChildReferences, hasComponentReferenceCycle } from "@/lib/a2ui/component-tree"
import type { A2UIComponent } from "@/types/a2ui/schema"

/**
 * Minimal shape of a captured assistant reply we need to read. Kept
 * structurally compatible with `CapturedAssistantReply` from
 * `lib/claude/run-and-capture.ts` so we can accept either object directly.
 */
export interface AssistantReplyForExtraction {
  /** Plain markdown text portion of the assistant reply. */
  text: string
  /** A2UI surfaces created during this reply, keyed by surfaceId. */
  a2uiSurfaces?: Record<string, A2UISegmentContent>
  /** Surface ids in the order the assistant created/updated them. */
  a2uiSurfaceOrder?: string[]
  telemetry?: { adapterId: string; platform: string }
}

/**
 * Convert the assistant's reply into a list of message segments ready for
 * the outbound runner.
 *
 *   - A2UI surfaces become {type: "a2ui"} segments in the order they were
 *     created/updated. Each segment carries a fresh `plainTextMirror`
 *     either taken from the surface's `widget.fallbackText` (when the
 *     model provided one) or generated by `generatePlainTextMirror`.
 *   - Textual A2UI payloads render in place among the surrounding markdown.
 *     Unrelated code fences and malformed payloads remain intact. Adapters
 *     that don't support markdown degrade per their capability matrix.
 *
 * When the reply has no A2UI surfaces, the output is just
 * `[{type: "markdown", md: text}]` (or `[{type: "text", text}]` for an
 * empty/whitespace-only reply — we still want to fire the outbound so
 * the user knows the assistant responded).
 */
export function assistantReplyToSegments(reply: AssistantReplyForExtraction): MessageSegment[] {
  const segments: MessageSegment[] = []
  const surfaces = reply.a2uiSurfaces ?? {}
  const order = reply.a2uiSurfaceOrder ?? Object.keys(surfaces)

  for (const surfaceId of order) {
    const content = surfaces[surfaceId]
    if (!content) continue
    segments.push(buildA2UISegment(surfaceId, content, reply.telemetry))
  }

  const emittedIds = new Set(segments.map((segment) => (segment as A2UIMessageSegment).surfaceId))
  const appendText = (text: string) => {
    if (text.trim()) segments.push({ type: "markdown", md: text })
  }
  const appendSurfaces = (parsed: Map<string, A2UISegmentContent>) => {
    for (const [surfaceId, content] of parsed) {
      // Tool snapshots are authoritative when the assistant also prints the surface.
      if (!emittedIds.has(surfaceId)) {
        segments.push(buildA2UISegment(surfaceId, content, reply.telemetry))
        emittedIds.add(surfaceId)
      }
    }
  }

  // Match every fenced language so JSON inside another code sample is not consumed.
  const fences = /```([^\n`]*)\r?\n([\s\S]*?)```/g
  let cursor = 0
  let hasFence = false
  for (const match of reply.text.matchAll(fences)) {
    hasFence = true
    if (!/^(?:a2ui|json)?$/i.test(match[1].trim())) continue
    const parsed = parseReplySurfaces(match[2])
    if (!parsed) continue
    appendText(reply.text.slice(cursor, match.index))
    appendSurfaces(parsed)
    cursor = match.index + match[0].length
  }
  const raw = !hasFence ? parseReplySurfaces(reply.text) : null
  if (raw) appendSurfaces(raw)
  else appendText(reply.text.slice(cursor))
  if (segments.length === 0) {
    // Reply with no text AND no surfaces: emit an empty text segment so
    // the outbound runner has at least one segment to dispatch (it would
    // otherwise reject the OutboundRequest as malformed).
    segments.push({ type: "text", text: "" })
  }

  return segments
}

/** Parse only complete JSON payloads; malformed output remains visible as markdown. */
function parseReplySurfaces(text: string): Map<string, A2UISegmentContent> | null {
  const trimmed = text.trim()
  if (!trimmed.startsWith("{") && !trimmed.startsWith("[")) return null
  try {
    const parsed = parseA2UIInput(JSON.parse(trimmed))
    if (!parsed.messages.length || parsed.errors.length) return null
    const surfaces = new Map<string, A2UISegmentContent>()
    for (const message of parsed.messages) {
      const id = message.surfaceId
      if (typeof id !== "string" || !id) return null
      if (message.type === "deleteSurface") {
        surfaces.delete(id)
        continue
      }
      const surface = surfaces.get(id) ?? { components: {}, dataModel: {}, rootId: "root" }
      if (message.type === "createSurface") {
        surfaces.set(id, {
          components: {},
          dataModel: {},
          rootId: "root",
          surfaceType: message.surfaceType,
          title: message.title,
          catalogId: message.catalogId,
          widget: message.widget ? { ...message.widget } : undefined,
        })
      } else if (message.type === "updateComponents") {
        const components = { ...surface.components }
        for (const component of message.components) {
          if (
            !component ||
            typeof component.id !== "string" ||
            !isSafeDataModelKey(component.id) ||
            typeof component.component !== "string"
          )
            return null
          components[component.id] = component
        }
        surfaces.set(id, {
          ...surface,
          components,
          rootId: Object.hasOwn(components, "root") ? "root" : Object.keys(components)[0],
        })
      } else if (message.type === "dataModelUpdate") {
        if (!isA2UIDataModel(message.data)) return null
        surfaces.set(id, {
          ...surface,
          dataModel:
            message.merge === false ? message.data : deepMerge(surface.dataModel, message.data),
        })
      }
    }
    if (!surfaces.size) return null
    for (const surface of surfaces.values()) {
      const components = surface.components as Record<string, A2UIComponent>
      if (!components[surface.rootId] || hasComponentReferenceCycle(components, surface.rootId))
        return null
      if (
        Object.values(components).some((component) =>
          getComponentChildReferences(component).some((ref) => !Object.hasOwn(components, ref.id))
        )
      )
        return null
    }
    return surfaces
  } catch {
    return null
  }
}

/**
 * Build a single A2UI segment from a surface payload. Used directly by
 * `lib/connectors/scheduled-outbound.ts` for surfaces emitted outside
 * the normal assistant reply path (e.g., a connector-triggered surface
 * push from a workflow node).
 */
export function buildA2UISegment(
  surfaceId: string,
  content: A2UISegmentContent,
  telemetry?: { adapterId: string; platform: string }
): A2UIMessageSegment {
  const widget = (content.widget ?? {}) as Record<string, unknown>
  const providedMirror = typeof widget.fallbackText === "string" ? widget.fallbackText.trim() : ""
  const plainTextMirror =
    providedMirror.length > 0 ? providedMirror : generatePlainTextMirror(content)
  if (providedMirror.length === 0 && telemetry) {
    void trackInboxEvent("a2ui.downgrade", {
      adapterId: telemetry.adapterId,
      fields: { platform: telemetry.platform, reason: "missing_fallback_text", surfaceId },
      at: Date.now(),
    })
  }
  return {
    type: "a2ui",
    surfaceId,
    content,
    plainTextMirror,
  }
}
