/**
 * Agent-trace span model — OTel GenAI-aligned, persisted to Dexie.
 *
 * Field names are kept short and JS-friendly (`requestModel`, not
 * `gen_ai.request.model`) so existing code reads cleanly. The mapping to
 * OpenTelemetry attribute keys lives in `lib/agent-trace/span-to-otlp.ts`
 * (Phase 2). Phase 1 only emits to Dexie via `agent-trace-transport.ts`,
 * but the data shape is forward-compatible.
 *
 * W3C trace identifiers: `traceId` is 32 hex chars (16 bytes), `spanId` is
 * 16 hex chars (8 bytes), both lower-case. Generated by
 * `lib/agent-trace/emitter.ts` from `crypto.getRandomValues`.
 */

/** Top-level OTel `gen_ai.operation.name`. */
export type SpanOperationName =
  | "invoke_agent"
  | "execute_tool"
  | "chat"
  | "invoke_workflow"
  | "retrieval"

/** OTel `gen_ai.provider.name` plus our vendor extensions. */
export type SpanProviderName =
  | "anthropic"
  | "openai"
  | "cognia.plugin"
  | "cognia.team"
  | "cognia.connector"
  | "cognia.workflow"

/** Surface that produced the span — drives the agent-trace UI grouping. */
export type SpanSurface = "chat" | "agent-team" | "plugin-hook" | "connector" | "workflow"

/** Mid-span discrete event recorded via `recordEvent`. */
export interface SpanEvent {
  name: string
  at: number
  attributes?: Record<string, unknown>
}

/** Token usage block — mirrors Anthropic `usage`, including cache fields. */
export interface SpanUsage {
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
}

/** Optional Agent Team handoff payload captured on the dispatcher side. */
export interface SpanHandoff {
  fromAgent: string
  toAgent: string
  reason?: string
}

/**
 * One persisted span. `endTime`/`durationMs` are set on `endSpan`; the row
 * is written exactly once at end time (mid-span events live in `events[]`).
 *
 * Indexed in Dexie v55 by: `id` (primary), `sessionId`,
 * `[sessionId+startTime]`, `traceId`, `[traceId+startTime]`, `parentSpanId`,
 * `surface`.
 */
export interface AgentTraceSpan {
  /** Primary key — same as `spanId`. */
  id: string

  /** Owning workspace id — Workspace isolation column (Dexie v86); inherits the session's project. */
  projectId?: string

  // W3C identifiers.
  traceId: string
  spanId: string
  parentSpanId?: string

  // Timing.
  startTime: number
  endTime?: number
  durationMs?: number

  // OTel core.
  operationName: SpanOperationName
  providerName: SpanProviderName

  // Optional model / agent / tool identity.
  requestModel?: string
  responseModel?: string
  agentId?: string
  agentName?: string
  toolName?: string

  // Usage / cost (LLM spans).
  usage?: SpanUsage
  costUsdEstimate?: number
  finishReasons?: string[]

  // Error info.
  errorType?: string
  errorMessage?: string

  // Vendor (`cognia.*`).
  sessionId: string
  surface: SpanSurface
  pluginId?: string
  handoff?: SpanHandoff

  // Mid-span events.
  events?: SpanEvent[]

  // Opt-in content. Captured only when
  // `transports.agentTrace.captureContent === true`, and only after the
  // payload passes `lib/twin/ingest/redact.ts:hasNoLeakingPii`.
  inputPreview?: string
  outputPreview?: string

  // Free-form vendor metadata bag.
  metadata?: Record<string, unknown>
}

/** Discriminator key embedded in `StructuredLogEntry.data` so transports can
 * detect span-shaped entries without sniffing other fields. */
export const AGENT_TRACE_SPAN_KIND = "agent-trace-span" as const

/** Marker the trace transport scans for. */
export interface AgentTraceSpanLogPayload {
  kind: typeof AGENT_TRACE_SPAN_KIND
  span: AgentTraceSpan
}
